### ISSUE TITLE
Sample Code For Batch Upload Includes Undeclared Variable

### ISSUE THREAD

**Issue by dougdenney** [dropbox/dropbox-sdk-obj-c#100]
In the sample code provided for batch uploads

```
NSMutableDictionary<NSURL *, DBFILESCommitInfo *> *uploadFilesUrlsToCommitInfo = [NSMutableDictionary new];
DBFILESCommitInfo *commitInfo =
    [[DBFILESCommitInfo alloc] initWithPath:@"/output/path/in/Dropbox"];
[uploadFilesUrlsToCommitInfo setObject:commitInfo forKey:@"/local/path/to/my/file"];

[_tester.files batchUploadFiles:uploadFilesUrlsToCommitInfo
                            queue:nil
                    progressBlock:^(int64_t uploaded, int64_t total, int64_t expectedTotal) {
    NSLog(@"Uploaded: %lld  UploadedTotal: %lld  ExpectedToUploadTotal: %lld", uploaded, total, expectedTotal);
} responseBlock:^(DBFILESUploadSessionFinishBatchJobStatus *result, DBASYNCPollError *routeError, DBRequestError *error) {
    if (result) {
      NSLog(@"%@\n", result);
    } else {
      NSLog(@"%@  %@\n", routeError, error);
    }
}];
```

Has the variable _tester which isn't declared anywhere.

What should this be?

**Comment by greg-db** [comment]
Apologies for the confusion! That should be your [`DBUserClient`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBUserClient.html) instance. We'll get that fixed up in the sample code.

**Comment by dougdenney** [comment]
Thanks for responding. I did figure out what it was supposed to be.

The couple of other issues I saw:

- _tester.files should be client.filesRoutes
- [uploadFilesUrlsToCommitInfo setObject:commitInfo forKey:@"/local/path/to/my/file"]; should really be         [uploadFilesUrlsToCommitInfo setObject:commitInfo forKey: [NSURL fileURLWithPath: @"/local/path/to/my/file"]];. The key is a NSURL and not a NSString.
