### ISSUE TITLE
dbfilewritemode doesn't work for dbbatchuploadtask 

### ISSUE THREAD

**Issue by fans3210** [dropbox/dropbox-sdk-obj-c#102]
tested with uploading multiple mp3s (file names are: 1.mp3, 2.mp3 ....).

I set dbfilewritemode to 'add' with autorename set to YES. I tried the code and executed it twice. For the first execution, all the 6 mp3 files were successfully uploaded. But After I executed the code once again, nothing was changed on dropbox server even though I didn't get any error in the completion block. The 'lastmodified' timestamp for each mp3 file was still the one for the first execution

```
    for (NSInteger i = 1; i <= 6; i++) {
        
        NSString *anMp3FilePath = [[NSBundle mainBundle] pathForResource:[NSString stringWithFormat:@"%ld", i] ofType:@"mp3"];
        NSURL *anMp3FileUrl = [NSURL fileURLWithPath:anMp3FilePath];
        NSString *fileName = [NSString stringWithFormat:@"%ld.mp3", i];        
    DBFILESCommitInfo *commitInfo = [[DBFILESCommitInfo alloc] initWithPath:[NSString stringWithFormat:@"/test/testmp3folder/%@", fileName] mode:[[DBFILESWriteMode alloc] initWithAdd] autorename:@(YES) clientModified:nil mute:nil];
        
        [fileUploadingMutDict setObject:commitInfo forKey:anMp3FileUrl];
    }

//custom upload func
    [self dbUploadWithCommitDict:fileUploadingMutDict];
```

**Comment by scobbe** [comment]
@fans3210: Thanks for reaching out. Just want to confirm that you're using the latest version of the SDK (v3.0.3).

I'll need to double check this, but in the event that `autorename` is set to `YES`, and the files you are uploading have the same name and byte content, I'm pretty sure Dropbox server treats it as a no-op, meaning no error or different file modified time, which would account for what you've been experiencing.

Let me get back to you tomorrow on this one for sure, though.

**Comment by fans3210** [comment]
@scobbe . Thanks for the quick reply. Yes the version is 3.0.3.

And you are right, the byte content of each file doesn't have any change. I'm uploading exact the same files every time during testing.

**Comment by scobbe** [comment]
@fans3210: Ok, yes, I've confirmed that this is in fact the case. You can read more in the documentation [here](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESWriteMode.html).

Let us know if you run into any other issues, or if you have any feedback on the SDK.
