### ISSUE TITLE
macOS: Dropbox login does not work anymore. Username and Password text fields do not respont

### ISSUE THREAD

**Issue by SDPrio** [dropbox/dropbox-sdk-obj-c#103]
A couple of weeks ago I updated my existing macOS app from Dropbox Core API v1 to API v2. Everything worked fine, but since yesterday some users report, that they cannot connect the app to Dropbox anymore.

I call `[DropboxClientsManager authorizeFromControllerDesktop:controller:openURL:browserAuth:]` using `browserAuth:false` to connect to Dropbox. This uses the Dropbox app if installed or the browser login as fall back, if the Dropbox App is not installed. It seems that the problem only occurs, if the Dropbox app is installed and thus used for authentication. Authentication over the browser works just fine.

The App will show the login page and let the user enter his e-mail address and password. Problem is, that **the login button is not enabled anymore once the user entered the credentials**. Thus the login cannot be completed and it is not possible to establish the connection. 

Something is broken on the Dropbox apps login page. The placeholder textes "E-Mail" and "Password" are not removed from the text fields when the users starts typing, so that the placeholders overlap the entered username and password. Its seems that the text fields do not recognize the data at all.

How to solve this?

**Comment by scobbe** [comment]
@SDPrio: Thanks for reaching out, and sorry that you're running into issues.

Would it be possible for you to post a screenshot of the issue?

**Comment by SDPrio** [comment]
Sure:
![dropbox](https://cloud.githubusercontent.com/assets/2169234/23521584/ea670f46-ff7f-11e6-97ad-b6ebcfd33c1e.png)

As you can see, the login button ("Anmelden") is still disabled, although username and password have been entered. Additionally the placeholders are still visible and overlap the username and password.

**Comment by greg-db** [comment]
Thanks! That's helpful. For reference, can you let us know what version(s) of macOS you're seeing this on, and what version of Safari is installed? (I know you're not seeing this in Safari itself, per your screenshot, but I believe the same browser engine is used.) Thanks in advance!

**Comment by SDPrio** [comment]
Currently  I am using Safari Version 10.0.3 (11602.4.8.0.1) on macOS 10.11.6, but since several users have reported this issue, I assume that also other versions might be effected.

**Comment by greg-db** [comment]
Thanks! We just made a change that may fix this. Can you try again and let me know if you're still seeing it?

**Comment by SDPrio** [comment]
The problem is solved! Thank you very much for the prompt service!

**Comment by scobbe** [comment]
No problem! Let us know if anything else comes up.

**Comment by SDPrio** [comment]
Unfortunately a user reports, that the problem still occurs on his system:
macOS Sierra 10.12.3 including all updates.
Safari 10.0.3 (12602.4.8).

**Comment by greg-db** [comment]
Thanks for following up @SDPrio . I just tested with those versions, and I can't reproduce the issue. I suspect the user may still be seeing this due to some cached resources from the time of the issue. Please have them try again in a little while, or have them clear their cache.

**Comment by SDPrio** [comment]
Do you mean the Safari cache or some system cache?

**Comment by greg-db** [comment]
I meant the Safari cache, which would hopefully clear any cache the in-app browser is using as well. If that doesn't help, we'll have to investigate further. In that case, it would be helpful to know if this does or doesn't fail in Safari itself for the user as well.

**Comment by SDPrio** [comment]
Latest feedback from the user: He experiences the problem only on his iMac while on his MacBook (same OS X + Safari version) everything is fine. After switching from Safari to Chrome as default browser the login also works on iMac. I have no idea if he performed any additional steps (e.g. clearing Safari cache) but is seems to be a very limited problem. 

I will let you know if I get any further information. For know the problem seems to be solved.
