### ISSUE TITLE
DBClientsManager class name is actually DropboxClientsManager?...

### ISSUE THREAD

**Issue by drivefast** [dropbox/dropbox-sdk-obj-c#104]
I think it's just a documentation issue, right?

**Comment by greg-db** [comment]
`DropboxClientsManager` was renamed to `DBClientsManager` in [release 3.0.0](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.0):

>Here are the interface-breaking name changes:
>
>Basic use cases:
...
>`DropboxClientsManager` class --> `DBClientsManager`
