### ISSUE TITLE
URGENT: Provide "Server_Modified" property for DBFILESMetadata class

### ISSUE THREAD

**Issue by eyeamit** [dropbox/dropbox-sdk-obj-c#105]
Please provide "server_Modified" property for DBFILESMetadata class. Only available for DBFILESFileMetadata. Not for other DBFILESMetadata types (DBFILESFolderMetada and DBFILESDeletedMetadata). 

In API V1 it was available for DBMetadata (which covered all files, folders, deleted folders). 

In API V2 can't create directories using attribute "server_modified" with key NSModificationDate. Please prove "Server_Modified" property to DBFILESMetadata. URGENT!!

**Comment by greg-db** [comment]
Thanks! I'm also sending this along as a request for modified times on non-file metadata, but I can't make any promises as to if or when that would be implemented and released.

**Comment by eyeamit** [comment]
Dear Gregory,
No need for this feature enhancement. Sync is working properly without any issue with no need for modified times on non-file metadata. You were right servermodified property is not good for tracking changes in a folder. Cursor helped a lot. I am closing this topic. Thank You
