### ISSUE TITLE
user authorization using tokenID within same app session leads to exception

### ISSUE THREAD

**Issue by truebucha** [dropbox/dropbox-sdk-obj-c#107]
I am authorizing app using `[DBClientsManager setupWith`... only once during life cycle.

Than am using `reauthorizeClient` when user log out the app and log in again

```
+ (BOOL)reauthorizeClient:(NSString *)tokenUid {
  NSAssert(![DBOAuthManager sharedOAuthManager], @"Only call "[DBClientsManager setupWith...]" once"); have an exception

  DBAccessToken *accessToken = [[DBOAuthManager sharedOAuthManager] getAccessToken:tokenUid];
  if (accessToken) {
    [[self class] setupAuthorizedClient:accessToken];
    return YES;
  }

  return NO;}
```

What I am doing wrong?

**Comment by scobbe** [comment]
@truebucha: Sorry, this is a bug that is fixed on master and will be fixed in the latest version, which should be released in the hour. Thanks for your patience and sorry for the inconvenience!

Will update the thread when I've pushed out the update.

**Comment by scobbe** [comment]
@truebucha: This should be fixed now in the [latest version of the SDK](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.4).

Thanks for your patience and sorry for the trouble. Let us know if anything else comes up.
