### ISSUE TITLE
Can't Download File From Dropbox

### ISSUE THREAD

**Issue by j-cimb-barker** [dropbox/dropbox-sdk-obj-c#109]
Hello,

I am using the following code to download files using the Vs2 API:

```
[[client.filesRoutes downloadData:filePath]
    setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *error,
                       NSData *fileContents) {
      if (result) {
        NSLog(@"%@\n", result);
        NSString *dataStr = [[NSString alloc] initWithData:fileContents encoding:NSUTF8StringEncoding];
        NSLog(@"%@\n", dataStr);
      } else {
        NSLog(@"%@\n%@\n", routeError, error);
      }
    }];
```

I receive the error:

```
2017-03-16 15:58:35.759 xctest[78431:5712864] (null)
DropboxClientError[{
    NSError = "Error Domain=NSURLErrorDomain Code=-1 \"unknown error\" UserInfo={NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/download, NSLocalizedDescription=unknown error, NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/download}";
}];

```
I have checked and the file at filePath exists. Is there anything I am missing...?

Kind regards,

Joel

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://www.dropboxforum.com/t5/API-support/Can-t-Download-File-From-Dropbox-downloadData-With-Objective-C/m-p/211957#M10699](https://www.dropboxforum.com/t5/API-support/Can-t-Download-File-From-Dropbox-downloadData-With-Objective-C/m-p/211957#M10699) ]

Thanks for the report. I unfortunately can't reproduce this error though, and your code looks correct.

The error message itself is unfortunately also not very helpful, as it seems to be a catch-all error for unknown NSURL issues:
> Returned when the URL Loading system encounters an error that it cannot interpret.

You mentioned that you're seeing this for both uploading and downloading, but not other calls. Uploading and downloading use api-content.dropbox.com whereas most other calls use api.dropbox.com. Is there anything on your network connection (firewall, anti-virus, proxy, etc.) that may be interfering with api-content.dropbox.com but not api.dropbox.com? (E.g., perhaps one is whitelisted somewhere but the other isn't.)

**Comment by j-cimb-barker** [comment]
Hello, Thanks for replying. I think it's because I am using a token obtained from the App Web Console during testing. I am switching to obtaining the token via the App. I will let you know if this improves the issue.

**Comment by greg-db** [comment]
Access tokens acquired via the App Console or via the app's authorization flow should be functionality equivalent. Let us know what you find though.

**Comment by j-cimb-barker** [comment]
I found out this was due to the way I was setting up DBUserClient. I switched to:

`DBUserClient *client = [DBClientsManager authorizedClient];`

and it solved the problem.
