### ISSUE TITLE
The authentication webpage isn't closed automatically after login successfully

### ISSUE THREAD

**Issue by linhongyi** [dropbox/dropbox-sdk-obj-c#110]
After I login dropbox successfully,
the authentication webpage isn't closed automatically. It don't have any actions after clicking button.
How do I let close webpage automatically? Thanks for your help.

**Comment by greg-db** [comment]
HI @linhongyi , I'm not sure I follow. Can you share the code you're using and a screenshot of the issue? Thanks in advance!

**Comment by linhongyi** [comment]
First, I listen the event as the following.

  [[NSAppleEventManager sharedAppleEventManager] setEventHandler:self
                                                           andSelector:@selector(handleAppleEvent:withReplyEvent:)
                                                         forEventClass:kInternetEventClass
                                                            andEventID:kAEGetURL];
To Login 

    [DBClientsManager authorizeFromControllerDesktop:[NSWorkspace sharedWorkspace]
                                               controller:self.viewcontroller.contentViewController
                                                  openURL:^(NSURL *url){
                                          
                                                      [[NSWorkspace sharedWorkspace] openURL:url];
                                                  }
                                              browserAuth:YES];

I login by authentication web page successfully. 

The authentication web page isn’t closed. I can click these buttons, but no response yet.

![2017-03-20 9 38 23 2](https://cloud.githubusercontent.com/assets/2688050/24086951/4a955b80-0d53-11e7-99a3-9c2f0d598a8f.png)

**Comment by greg-db** [comment]
Thanks! That's helpful.

When the user clicks the button to authorize your app, they should get automatically sent back to your app. There are a few additional things you need to configure to make that work though, that you didn't mention above:

Make sure you've registered your URL scheme with your app key under `CFBundleURLTypes` in your app's plist, as covered here:

https://github.com/dropbox/dropbox-sdk-obj-c#configure-your-project

Also, make sure you've implemented `handleAppleEvent` as shown here:

https://github.com/dropbox/dropbox-sdk-obj-c#macos-4

With those pieces in place, the user should automatically get sent back to your app after authorizing your app. (Let us know if that's still not working for you after you finish implementing those as covered in the readme though.)

Anyway, regarding the issue of the page staying open, that's a page in the user's own browser, so there isn't a good way to close it. If you'd prefer though, you can instead use this in `authorizeFromControllerDesktop` to not use the external browser:
`browserAuth:NO`

**Comment by linhongyi** [comment]
Thanks for your help.  It's ok for me to login dropbox by browser or in app. 

Maybe, we could set the webpage to go to the dropbox home page (https://www.dropbox.com/) after signing the account. The user isn't confused on the staying webpage.

**Comment by greg-db** [comment]
Thanks for the suggestion!

To clarify though, is the app authorization flow itself working properly for you now?

**Comment by linhongyi** [comment]
The app authorization flow is perfectly working for myself. thanks!!!!
