### ISSUE TITLE
Checking isAuthorized fails due to DBUserClient shadowing transportClient property

### ISSUE THREAD

**Issue by ramonpoca** [dropbox/dropbox-sdk-obj-c#112]
Upon resuming an authorized session in the simulator, calling 
```objc
 [DBClientsManager setupWithAppKey:theClientID];
...
BOOL authorized = [DBClientsManager authorizedClient].isAuthorized
```
was returning `authorized == NO` incorrectly. 

This is due to  `DBUserClient.m` redeclaring as an instance variable:
```objc
@implementation DBUserClient {
  DBTransportDefaultClient *_transportClient;
}
```
a property that is declared in `DBUserBaseClient`:
```objc
@property (nonatomic, readonly) id<DBTransportClient> _Nonnull transportClient;
```

The instance variable clobbers the synthesized property, generating two different instance variables. `setupWithAppKey` initializes the `DBUserBaseClient` one, but leaves the `DBUserClient` as `nil`. This causes the check for authorization to fail.

I've implemented a (quite contrived) patch that declares `_transportClient` as `@protected` in the parent class (see [this SO question](http://stackoverflow.com/questions/11047351/workaround-to-accomplish-protected-properties-in-objective-c)).

```objc
//  DBUserBaseClient.h
@interface DBUserBaseClient : NSObject {
    @protected
    id<DBTransportClient> _transportClient;
}
...
// DBUserBaseClient.m

@interface DBUserBaseClient ()
@property (nonatomic, readonly) id<DBTransportClient> _Nonnull transportClient;
@end

@implementation DBUserBaseClient 
@synthesize transportClient = _transportClient;
...


// DBUserClient.h

@interface DBUserBaseClient ()
@property (nonatomic, readonly) id<DBTransportClient> _Nonnull transportClient;
@end

@interface DBUserClient : DBUserBaseClient
...
```

**Comment by scobbe** [comment]
@ramonpoca: This is a great find. Thank you for bringing this to our attention. This should be fixed in the [v3.0.5](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.5) version of the SDK.

Let us know if you spot anything else!
