### ISSUE TITLE
Unsafe for App Extensions

### ISSUE THREAD

**Issue by tobihagemann** [dropbox/dropbox-sdk-obj-c#113]
With version 2.x this SDK was safe to use in app extensions. I've noticed that, beginning with 3.0.0, this is not the case anymore.

I'm getting an error in [DBOfficialAppConnector-iOS.m#L177](https://github.com/dropbox/dropbox-sdk-obj-c/blob/18a5c95f5794db5e68065ea3ed7fe3a05ec935d5/Source/ObjectiveDropboxOfficial/Platform/ObjectiveDropboxOfficial_iOS/OfficialPartners/OpenWith/DBOfficialAppConnector-iOS.m#L177) with message:

> 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

I remember seeing this comment: https://github.com/dropbox/dropbox-sdk-obj-c/issues/78#issuecomment-271954435

I find it interesting, because there was an example for app extension safety: [DBOAuthMobile-iOS.m#L25](https://github.com/dropbox/dropbox-sdk-obj-c/blob/bf9c5dca9d602bf0b95a6bf26e05d7eb2787bcbd/Source/ObjectiveDropboxOfficial/ObjectiveDropboxOfficial_iOS/DBOAuthMobile-iOS.m#L25)

I haven't looked into the details on how it's done, but I hope we can make this SDK safe to use in app extensions again. :smile:

**Comment by tobihagemann** [comment]
Oh, this line of code is even more interesting: [DBOAuthMobile-iOS.m#L108](https://github.com/dropbox/dropbox-sdk-obj-c/blob/18a5c95f5794db5e68065ea3ed7fe3a05ec935d5/Source/ObjectiveDropboxOfficial/Platform/ObjectiveDropboxOfficial_iOS/DBOAuthMobile-iOS.m#L108)

Maybe it can be reused in `DBOfficialAppConnector-iOS.m` somehow?

**Comment by greg-db** [comment]
Thanks! We'll look into it.

**Comment by scobbe** [comment]
@tobihagemann: Apologies for the inconvenience. This should be fixed by 9ab686 on `master` now.

A new release will follow shortly. Thank you, and let us know if you spot anything else.

**Comment by tobihagemann** [comment]
Awesome! Thanks for the quick response and solution! :+1:

**Comment by scobbe** [comment]
Ok, this should be fixed in [3.0.7](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.7) now.
