### ISSUE TITLE
Cocoa pods not working for 3.0

### ISSUE THREAD

**Issue by ghouse1** [dropbox/dropbox-sdk-obj-c#114]
Am trying to use cocopods,  pod 'ObjectiveDropboxOfficial', '~> 3.0', but am receiving following error while installing pod.

![screen shot 2017-03-23 at 6 47 30 pm](https://cloud.githubusercontent.com/assets/2462284/24256532/7aa88ec0-0ff9-11e7-829e-b9b255ba5f1d.png)

**Comment by scobbe** [comment]
@ghouse1: Any reason you're pulling version 3.0.0? Why not the latest version?

```
target '<YOUR_PROJECT_NAME>' do
    pod 'ObjectiveDropboxOfficial'
end
```

**Comment by tobihagemann** [comment]
Just dropping by, because I've noticed this "error" as well at some point. Have you tried `pod repo update` as suggested in the message you've just posted? 😅

**Comment by ghouse1** [comment]
@tobihagemann 
you are right after updating the `pod repo update` ,  now i can able to install 3.0 version.

@scobbe 
When i choose like  
`target '<YOUR_PROJECT_NAME>' do
    pod 'ObjectiveDropboxOfficial'
end`
it is installing old version with 1.xx.xx. So i choose 3.xx.xx

**Comment by scobbe** [comment]
@ghouse1: That's strange. At least use the latest version (3.0.5)!
