### ISSUE TITLE
file not found #import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h>

### ISSUE THREAD

**Issue by ml1426** [dropbox/dropbox-sdk-obj-c#115]
I followed these instruction down to "Create your project". Everything worked fine as it is. At the step "**Initialize a DBUserClient instance**", when I insert the snippet 
`#import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h>`
into AppDelegate.m, there is an error: 
` <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h> file not found`
I checked on Pods/Pods/ObjectiveDropboxOfficial of project folder, there was `ObjectiveDropboxOfficial.h` file in there. Did I miss any thing? 
my Xcode is 8.2.1 and, iOS target is 9.0.
I did CocoaPods method to integrate Dropbox Objective-C SDK. 
Please give me any advice. Thanks.

**Comment by ml1426** [comment]
It fixed. 
I try to reinstall Cocoapods, and change in pod file:
Before: 
`platform :ios, '10.0'
target 'Prj168Onair' do
  use_frameworks!
  pod 'ObjectiveDropboxOfficial'
end`
After:
` use_frameworks!
target 'Prj168Onair' do
  platform :ios, '10.0'
  pod 'ObjectiveDropboxOfficial'
end
`
 I deleted MyProject.xcworkspace and do `pod install` again. It now gets free error of  `<ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h> file not found`

**Comment by Dirk23** [comment]
Sorry to reopen this, but i tried the same as @ml1426 but for me the error does not get removed. I try to convert from API1 to the newest so i deleted .xcworkspace file, ran `pod install`, clean builded my Project and still error.

What did i miss?

**Comment by Dirk23** [comment]
Ok, deleting the Pod Folder in my project and the .xcworkspace file the `pod install` did the trick!
