### ISSUE TITLE
How to download file shared to me?

### ISSUE THREAD

**Issue by Daivest** [dropbox/dropbox-sdk-obj-c#116]
Hello!
i fetch files shared to me with
`[client.sharingRoutes listReceivedFiles];`
it gives me
`NSArray<DBSHARINGSharedFileMetadata *> *sharedFiles = result.entries;`
but it's `pathDisplay == nil`, and i can't download it as i download my own files...

i tried it with `NSURLSessionDownloadTask` with `previewURL`, but it download just HTML page, not my file.
try it with `dl=0` and with `dl=1`, at the end of url

so, how can i download file shared to me?

**Comment by greg-db** [comment]
You can use the [`DBSHARINGSharedFileMetadata.linkMetadata.url`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGSharedContentLinkMetadata.html#/c:objc(cs)DBSHARINGSharedContentLinkMetadata(py)url) with [`getSharedLinkFileUrl`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGRoutes.html#/c:objc(cs)DBSHARINGRoutes(im)getSharedLinkFileUrl:overwrite:destination:) to get the file data, like:

    // or whichever one you are interested in
    if (response.entries.firstObject) {

        [[client.sharingRoutes getSharedLinkFileData:response.entries.firstObject.linkMetadata.url] setResponseBlock:^(DBSHARINGSharedLinkMetadata *response, DBSHARINGGetSharedLinkFileError *routeError, DBRequestError *error, NSData *fileData) {
            if (response) {
                NSLog(@"%@", response);
                NSLog(@"Got file data with length: %lu", (unsigned long)fileData.length);
            } else {
                NSLog(@"%@", routeError);
                NSLog(@"%@", error);
            }

        }];

    }

**Comment by Daivest** [comment]
thank you, Greg!
