### ISSUE TITLE
Xcode 8.3 now shows a lot of "retain self" warnings in code

### ISSUE THREAD

**Issue by Solublepeter** [dropbox/dropbox-sdk-obj-c#121]
With the release of Xcode 8.3 warning messages for retain errors in blocks are more prevalent.

We now see a lot of 
"Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behaviour" 
messages coming from the Dropbox iOS code.

Please check and amend the relevant code to prevent those warning messages.

**Comment by greg-db** [comment]
Thanks for letting us know! We'll look into it.

**Comment by scobbe** [comment]
@Solublepeter: Thanks for bringing this to our attention. Fix is landed on master, with package manager release to follow tonight.

Let us know if you spot anything else. Have a great day!

**Comment by Solublepeter** [comment]
Great, thanks.

Cheers

Peter Johnson
Soluble Apps

Mailshot support is powered by our unique "FAQ: Email Composer" app. https://appsto.re/gb/YHN8K.i

Mobile email made easier.

**Comment by scobbe** [comment]
Ok, this should be fixed in [3.0.7](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.7) now.
