### ISSUE TITLE
Warning message for block variable names that shadow existing variables

### ISSUE THREAD

**Issue by Solublepeter** [dropbox/dropbox-sdk-obj-c#122]
In Xcode 8.3 a warning message is now generated when a block variable name matches an existing variable defined outside the block.

Please rename these local variables to avoid warning messages, checking for underlying issues.

**Comment by greg-db** [comment]
Thanks for letting us know! We'll look into it.

**Comment by scobbe** [comment]
@Solublepeter: Thanks for bringing this to our attention. Fix is landed on master, with package manager release to follow tonight.

Let us know if you spot anything else. Have a great day!

**Comment by scobbe** [comment]
Ok, this should be fixed in [3.0.7](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.7) now.
