### ISSUE TITLE
DBGlobalErrorResponseHandler.h file not found

### ISSUE THREAD

**Issue by jim-rhoades** [dropbox/dropbox-sdk-obj-c#123]
I've followed the instructions for adding the Dropbox API to my project via Carthage, but when I try to build the project I get an error on DBSDKImportsShared.h which says "DBGlobalErrorResponseHandler.h file not found."

It looks like the global response handling code was recently added, but maybe those new files are not being included in the framework when building via Carthage somehow?

Or am I missing something obvious?

**Comment by scobbe** [comment]
@jim-rhoades: Ah sorry about this. The `DBGlobalErrorResponseHandler.h` file was marked as "project" not "public".

It is fixed now on master ([here](https://github.com/dropbox/dropbox-sdk-obj-c/commit/b1a7abf7fd3d1e1eecfc2871cf3090cfa3c74fb4)). I will push out a release today, and re-ping this thread.

**Comment by scobbe** [comment]
Ok, this should be fixed in [3.0.7](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.7) now.

**Comment by jim-rhoades** [comment]
Thanks @scobbe !
