### ISSUE TITLE
missed ObjectiveDropboxOfficial/DBSDKImports-macOS.h

### ISSUE THREAD

**Issue by truebucha** [dropbox/dropbox-sdk-obj-c#127]
I tried to implement mac os framework using this framework and found that

s.dependency 'ObjectiveDropboxOfficial', '= 3.0.10' leads to 
#import <ObjectiveDropboxOfficial/DBSDKImports-macOS.h> not found in the imported pods folder

For some reason the Platform folder contains only ObjectiveDropboxOfficial_iOS and missing ObjectiveDropboxOfficial_macOS.
Am I doing something wrong?

**Comment by scobbe** [comment]
@truebucha: Thanks for reaching out. I am unable to reproduce your issue:

![image](https://cloud.githubusercontent.com/assets/17483354/24769964/31001bd4-1abd-11e7-9119-93423f052c34.png)

I am using the following Podfile (which I just added to the README documentation):

```
platform :osx, '10.10'
use_frameworks!

target '<PROJECT_NAME>' do
    pod 'ObjectiveDropboxOfficial'
end

```

Please let me know if you still experience this issue using the above Podfile. Please also ensure that you have the `.xcworkspace` not the `.xcodeproj` file open.

**Comment by truebucha** [comment]
Sorry for inconvenience. I found that pod wan't update repo that previously was set up only for iOS version so I should remove Pod directory and Podfile.lock completely and do pod install once again.
isuue resolved.
