### ISSUE TITLE
in Examples method "progress:" now named "setProgressBlock"

### ISSUE THREAD

**Issue by svendback** [dropbox/dropbox-sdk-obj-c#128]
https://github.com/dropbox/dropbox-sdk-obj-c: The current examples name progress as method for getting updates on a download

**Comment by greg-db** [comment]
@svendback You only linked to the root of the project. Can you link to where specifically you're having an issue? Thanks in advance!

**Comment by scobbe** [comment]
As of [v3.0.11](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.11) I've confirmed that all examples are updated. However, I did not see any with `progress:`, so perhaps you were using an older version of the SDK?
