### ISSUE TITLE
Safariservices framework isn't available on macOS 10.11

### ISSUE THREAD

**Issue by linhongyi** [dropbox/dropbox-sdk-obj-c#132]
The Safariservices framework is only supported on macOS 10.12+.

We could find the document on the website (https://developer.apple.com/reference/safariservices).

There is not a Safariservices framework on the some macOS 10.11 machines, so the project isn't not work.

**Comment by scobbe** [comment]
@linhongyi: Thanks for reaching out, and sorry for the inconvenience.

This issue is fixed in the [latest version of the SDK](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.12).
