### ISSUE TITLE
Question: Dropbox sync API (ab)using the main thread?

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#133]
Suddenly after releasing our app on the store, it seems hundreds are complaining the app has suddenly frozen on them and the background sync is making the app hang and stall. I suspect Dropbox API 2 is doing something on the main thread?

I *think* I saw somewhere in the code where it sends notifications to the main thread but it should never be doing this. Like before, it should use the thread the request came from and not route it to the main thread. We're doing some heavy lifting in the background sync thread (since we have dozens of files to download and upload during sync) and for some-reason the new change is causing issues.

I'm sorry I'm raising an issue without much investigation, but we're certain the only big change was to move from v1 to v2 as the rest of our code remains thoroughly tested. I'll check back once I figure out what's happening, but after viewing some videos of users showcasing the issue, it seems even though our sync code's executing nicely in the background, the UI hangs completely during sync.

**Comment by guidedways** [comment]
Too early to say - sorry, I'm closing this for now.

**Comment by scobbe** [comment]
@guidedways: Certainly let us know if you determine that the SDK is causing you issues. The only thing I can think of is the default setting of the `transportClient` delegate is to use the main thread as a dispatcher [here](https://github.com/dropbox/dropbox-sdk-obj-c/blob/33dc18a6593477d0c850d34dd58ecb6b502336d0/Source/ObjectiveDropboxOfficial/Shared/Handwritten/Networking/DBTransportDefaultClient.m#L29).

Could this be the source of your issue?

**Comment by guidedways** [comment]
Thanks @scobbe was about to update you :) That was it! I *just* updated my code to specifically use a custom `NSOperationQueue` with quality of service set to background / utility :) I didn't realize the importance of the property as a bunch of our beta testers didn't stumble on this issue, yet a number of App Store users saw the app freeze randomly.

**Comment by scobbe** [comment]
@guidedways: Ah I'm really sorry for the trouble. I wouldn't have expected this to be an issue, but I guess it's not too hard to imagine with a high-volume of traffic there being a real problem.

Should the default delegate then be `[NSOperationQueue new]` in your opinion?

Again, apologies for the issues.

**Comment by guidedways** [comment]
@scobbe no harm done, we learn every day, right :D

I think it was the Dropbox API for Android where during the port it surprised me to see the app crash as it was trying to run network code on the main thread (from `OkHttp`). I made me realize then that there's no valid reason to have the network code run on the main thread, ever - and that was a pretty clever `assert` added just to make sure we're forced to use a background thread. 

For reasons of consistency (since Dropbox API on Android uses OkHttp in the background), I'd say yeah it should really just be `[NSOperationQueue new]` with perhaps `maxConcurrentOperationCount` set to 1. This would avoid situations where the app is executing code in the background and wouldn't expect network callbacks to hit the main thread.

Thanks!

**Comment by scobbe** [comment]
@guidedways: Thanks for the feedback, and sorry again for the problems!

This is fixed now in the [latest version of the SDK](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.14).

**Comment by guidedways** [comment]
Thanks again @scobbe 

Out of curiosity, there are still numerous places where I see:

`NSOperationQueue *queueToUse = queue ?: [NSOperationQueue mainQueue];`

Is that intended?

**Comment by scobbe** [comment]
@guidedways: So I'm a little bit torn here – clearly, for dispatching responses, there's no need for anything to be done on the main queue, and that was updated in my latest change.

However, I feel like the most common use-case for any response block includes updating some UI component, which is why I left the response block execution on the main thread by default.

But I'm not totally sold by my thinking – do you think it should be incumbent on the caller to dispatch to the main queue if they want to update to the UI, even if this is the most likely case of what they'll be doing?

In my opinion, if the caller has heavy lifting to do in the response block, they should dispatch to another thread, rather than the other way around.

But let me know what you think. Thanks for checking back in here!

**Comment by scobbe** [comment]
For reference, respected networking libraries like [AlamoFire](https://github.com/Alamofire/Alamofire#response-handler-queue) exhibit this default behavior (executing response blocks on main thread).

**Comment by guidedways** [comment]
@scobbe I totally get you, and would agree that the usual response is to update the UI after some network operation completes. But then, this applies to all asynchronous GCD stuff we otherwise do - it's the responsibility of the user to ensure they always update any UI code explicitly, and intentionally, using some means of posting it on the main thread. The moment you enter the realm of multi-threading and pass a block to execute in the background, I'm usually always weary of updating the UI explicitly on the main thread. Examples we find of code doing:

```ObjC
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
   //    ... network call comes here ...
   
   // ... time consuming, post-processing of result (expecting to remain in background for heavy lifting)

    // Finally, explicitly update the UI
    dispatch_async(dispatch_get_main_queue(), ^{
         // update UI here
    });
});
```
The way I see it, the current Dropbox API allows one to chain API calls - calling one method from the response of another, without block the main thread. I should also add that if there was a single API method that did everything - yeah, we could argue it makes sense to always update the UI as soon as it's done. But the Dropbox API has tons of end-points, where you're normally calling a handful of methods one after another. I'd be surprised if there's any app out there that needs to update the UI after every . single . result . received :) 

In my particular use-case, I've got a dedicated background thread where sync is performed. All Dropbox APIs are executed there (and during a sync session, we normally end up calling numerous deltas / uploads / downloads). Results are expected to be processed in the background before finally updating the UI (or updating it in between based on internally tracked progress).

**Comment by scobbe** [comment]
@guidedways: This makes sense. Thanks for the detailed writeup and for your feedback! I will update the default execution behavior for all blocks to be off the main thread, and then update the documentation accordingly.

I'll ping this thread when I've released the new update. Thanks again for all the help and for the feedback!

**Comment by guidedways** [comment]
Pleasure! Thanks for looking into this so deeply 👍

**Comment by scobbe** [comment]
@guidedways: Wanted to update this thread here. After some consideration, additional research, and consultation with other members of my team, I think we are opting to keep the default behavior of executing response code on the main thread. As I have mentioned earlier, other networking libraries do this, and the most common use case for response code is updating the UI.

That said, all dispatching and non-response code execution logic, by default, will now happen off the main thread, so this will be an improvement over the earlier behavior.

I apologize for the inconvenience, and for the delayed response here. You raised many valid points, and I very much see where you're coming from. I trust that you will be able to continue using the SDK, but will simply want to dispatch all heavy lifting, non-UI related actions to another queue, in your response logic.

Please reach out if this is a serious issue, and we can try to work something else out.

For now, I will be closing this thread.

**Comment by guidedways** [comment]
@scobbe thanks for the update on this. Completely understand 👍 I'm just glad there's an option to override this behaviour by supplying a custom queue, as in our particular case I saw a marked improvement in UI animations, list scrolling etc while the app continued syncing in the background.

Many thanks.
