### ISSUE TITLE
Question: A way to set custom timeout?

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#136]
Although timeouts have always plagued the Dropbox v1 API, I seem to be hitting these often during testing. It seems the moment you try and make requests a little too frequently, the API call would hang for a good 60 seconds or so. Since we're trying to do this in a background fetch (when app is suspended), we miss the 30 second window and the app gets killed. I'd rather we set a custom timeout for certain calls so if these fail, we skip syncing entirely for that one session.

Is it possible to specify a timeout? I can't figure it out. The rather more serious issue we're facing is that we're unable to 'clean-up' properly from inside the background sync thread, since it's 'hung' in the background (supposedly for the current timeout of 6-8 minutes). We need to let go of opened database handles and perform other cleanup tasks.

**Comment by greg-db** [comment]
You can set custom timeouts by constructing the transport client and setting the values in the configuration as desired, like this:

```
DBTransportDefaultConfig *transportConfig = [DBTransportDefaultConfig new];
NSString *accessToken = [[DBOAuthManager sharedOAuthManager] retrieveFirstAccessToken].accessToken; // or access token for specific user
DBTransportDefaultClient *transportClient = [[DBTransportDefaultClient alloc] initWithAccessToken:accessToken transportConfig:transportConfig];
[transportClient.session.configuration setTimeoutIntervalForRequest:60]; // or whatever your desired value is
[transportClient.session.configuration setTimeoutIntervalForResource:60]; // or whatever your desired value is

self.client = [[DBUserClient alloc] initWithTransportClient:transportClient];
```

Hope this helps!
