### ISSUE TITLE
Callback not triggered wi-fi is disconnected after download request

### ISSUE THREAD

**Issue by mitsuteru** [dropbox/dropbox-sdk-obj-c#137]
I am having trouble preparing code for the following error scenario (steps as written below):
1) request downloadUrl
2) disconnect wi-fi on iPad
3) The downloadUrl block is never called

```
[[client.filesRoutes downloadUrl:dropboxPath overwrite:YES destination:localUrl] setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *networkError) {
    // Callback not triggered wi-fi is disconnected after download request
    if (result) {
        // succeed case.
    }
    else {
        // failure case.
    }
}];
```

**Comment by scobbe** [comment]
@mitsuteru: Thanks for reaching out. Try checking out the [NSURLSession section](https://github.com/dropbox/dropbox-sdk-obj-c#note-about-background-sessions) of the README. Let me know if you have any questions after reading this.

**Comment by mitsuteru** [comment]
Thanks, I got it.
