### ISSUE TITLE
Properly adopt semantic versioning and mark breaking changes accordingly

### ISSUE THREAD

**Issue by stefanceriu** [dropbox/dropbox-sdk-obj-c#138]
Hello there,

There were 2 recent breaking changes added to the project and not marked:

- this one here https://github.com/dropbox/dropbox-sdk-obj-c/commit/8936d7fc0be220e4cb1664b17ea6829044230a52#diff-c81aa4f783505ecb7aaecb5ba74e700cL33 which wasn't that bad as the compiler warned us about the change

- and this other one https://github.com/dropbox/dropbox-sdk-obj-c/commit/51cc2a172455c6425b0f594edbbe4ecc8c74801b that is crashing our app as callbacks started hitting UI components from secondary threads and of which we found out through sheer luck

Now, I understand breaking changes are sometimes necessary but you need to make sure they are very clearly marked and do not create unforeseen problems for your SDK clients. 

I should be able to integrate with it using `~>3.0.12` and receive all small tweaks and patches without worrying about the breaking changes in `3.0.14` for example.

You are offering both CocoaPods and Carthage support and they both follow [Semantic Versioning](http://semver.org/) so I suggest you do the same or be more strict about it.

Cheers,
Stefan

**Comment by scobbe** [comment]
@stefanceriu: Thanks for your feedback, and apologies for the inconvenience on your end. You're totally right, we really need to be more strict with adhering to semantic versioning. Going forward, I will endeavor to be strict about it.

As far as [51cc2a1](https://github.com/dropbox/dropbox-sdk-obj-c/commit/51cc2a172455c6425b0f594edbbe4ecc8c74801b), I'm a little confused as to how this would cause crashes in your app. Unless I'm mistaken, moving `_delegateQueue` from the main queue, by default, to a secondary queue, by default, should only affect how the response blocks are dispatched, not the final thread they are executed on. Maybe would you mind clarifying this for me?

Thank you!

**Comment by stefanceriu** [comment]
Hey Stephen,

Thank you for your quick reply and for understanding.

Regarding [51cc2a1](https://github.com/dropbox/dropbox-sdk-obj-c/commit/51cc2a172455c6425b0f594edbbe4ecc8c74801b), please apply this [patch.diff](https://github.com/dropbox/dropbox-sdk-obj-c/files/945245/patch.diff.zip) on top of your CocoaPods powered DBRoulette demo and watch it fail when picking a photo.

**Comment by greg-db** [comment]
Apologies for the delay here. We're looking into it and will follow up here once we have an update for you.

**Comment by stefanceriu** [comment]
No worries, you don't really need to do anything about it now.
Feel free to close this issue when you see fit.

Thanks,
Stefan

**Comment by xjki** [comment]
Changelog document with versions/API changes (with related commits) would be essential to follow up what has ben changed between versions. Now it's really hard.

**Comment by greg-db** [comment]
Thanks for the feedback! We currently document changes in [the release notes](https://github.com/dropbox/dropbox-sdk-obj-c/releases), but I'll send this along as a request to offer more specific information.

**Comment by xjki** [comment]
If release notes would dcument changes in header files and links to individual commits that would be perfect. Like https://github.com/skywinder/github-changelog-generator does.

**Comment by billymeltdown** [comment]
It's good that this SDK is so well maintained, but I think I should mention that since we updated to it, we were trying to keep up with the releases. They come out quite often. We had adapted to how the newer SDK handled response callbacks (on main thread, so we adapted). Then, in a span of I think less than 24 hours, this behavior changed and a new release was out with response callbacks not on the main thread.

As a result, I'm still using on version 3.0.3 and waiting for a stable release. I'm not sure what's fair to call "stable," as all code has bugs. But I can't imagine that such an important change should become a release that quickly. Shouldn't some time be taken to test major, breaking changes in some actual apps on devices for a little while, rather than declaring a change as stable just because the unit tests pass? 

I really appreciate the SDK and all the great work going into it and the responsiveness to fixing bugs, but I'm holding off on updating to new releases for a little bit. I'm not trying to be mean, but I'd like to hear the maintainers thoughts on what we should expect going forward.

**Comment by greg-db** [comment]
Thanks for the feedback @billymeltdown . I'll make sure the team reviews this.

**Comment by scobbe** [comment]
@stefanceriu @xjki @billymeltdown: Thank you all for your feedback. It is much appreciated on our end.

I really do owe all of you an apology. I have failed to adhere to the well-defined conventions around semantic versioning, especially in the case of the 3.0.14 update, which inadvertently made a subtle, but quite destructive change to the SDK interface: executing response handler code off the main thread by default.

My apologies for this. I know up until this point, I have not been good about semantic versioning, but it was certainly not my intention to introduce such a substantial change, without a major version update.

The latest version of the SDK (v3.0.16) fixes this regression, and restores the default behavior to executing response blocks on the main thread.

Going forward, I will be committed strictly adhering to semantic versioning. I can imagine how inconvenient the last couple of weeks have been for you all. Again, please accept my heartfelt apology.

I would encourage all of you to update to the latest version of the SDK. In the meantime, please reach out to me if anything else comes up.

**Comment by stefanceriu** [comment]
Hey Stephen, I appreciate your apology and I do understand that things like these sometimes happen, no worries.

Also, I think we've dwelled on the subject for long enough now, I'm closing the issue.

Cheers,
Stefan

**Comment by billymeltdown** [comment]
@scobbe no need for an apology here, and looking back I think I came on a little too strong! Thanks for all your hard work Stephen.
