### ISSUE TITLE
Failed to download files

### ISSUE THREAD

**Issue by olliwang** [dropbox/dropbox-sdk-obj-c#14]
Hi, I was trying to download a file but always failed to access the downloaded file contents. I tried `downloadURL:overwrite:destination:`, it did return a response with correct metadata and no errors. But still, the file at the url it returned never exists. I also tried the `downloadData:` method. There is no error as well but the returned data is always `nil`.

It seems the error happens in `DBXDelegate`'s `URLSession:downloadTask:didFinishDownloadingToURL:` method.

    - (void)URLSession:(NSURLSession *)session downloadTask:(NSURLSessionDownloadTask *)downloadTask didFinishDownloadingToURL:(NSURL *)location {
        NSLog(@"1: exists(%d)", location, [[NSFileManager defaultManager] fileExistsAtPath:location.path]);
        NSString *sessionId = [self getSessionId:session];
        NSNumber *taskId = [NSNumber numberWithUnsignedInteger:downloadTask.taskIdentifier];
        [_delegateQueue addOperationWithBlock:^{
            NSLog(@"2: exists(%d)", location, [[NSFileManager defaultManager] fileExistsAtPath:location.path]);
            void (^completionHandler)(NSURL *, NSURLResponse *, NSError *) = _downloadTasks[sessionId][taskId][kCompletionHandlerKey];
            completionHandler(location, downloadTask.response, nil);
            [_downloadTasks[sessionId] removeObjectForKey:taskId];
        }];
    }

I added two `NSLog()` to the method and it prints...

    1: exists(1)
    2: exists(0)

The downloaded file is gone in ``_delegateQueue`'s operation block. Once I executed the completion handler without running in the `_delegateQueue`. The issue no longer exists, I can receive the downloaded file in my response callback as expected. It seems iOS just deleted the temporary file as soon as exiting the delegate method as discussed here: http://stackoverflow.com/questions/22278407/nsurlsessiondownloadtask-downloads-but-ends-with-error

**Comment by scobbe** [comment]
Hey @olliwang: Thanks so much for reaching out and identifying this issue – and pointing us to the source of the problem as well! Looks like we were unnecessarily double-queuing events with the `[_delegateQueue addOperationWithBlock` calls in all of the `NSURLSessionTaskDelegate` response handler functions. Given that our delegate was already using `_delegateQueue`, it was unnecessary (and in this case, detrimental) to be requeuing sensitive blocks. I've gone ahead and updated the repo. Let me know if the problem persists or if you spot anything else. Thanks again!

**Comment by olliwang** [comment]
The issue is gone in the latest commit. Thanks @scobbe. 👍
