### ISSUE TITLE
Downloading in order

### ISSUE THREAD

**Issue by monish152** [dropbox/dropbox-sdk-obj-c#140]
Thanks for wonderful library. 
I have just updated it and facing below issue:

1. In previous library I used semaphore for download files in order. and it was working fine.
2. But after updating library now files are not downloading with that semaphore code. 

I have tried below conditions:
1. After removing semaphore, files are downloading but not in order as I have requested.
2. With semaphore, files are not downloading and even not going in error block.

Before downloading starts : dispatch_semaphore_t sem = dispatch_semaphore_create(0);
After download completion : dispatch_semaphore_signal(sem);
After completion of function : dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);

Can you please help.

**Comment by greg-db** [comment]
@monish152 Can you share the rest of the relevant code, so we can better understand the issue here? Thanks in advance!

**Comment by monish152** [comment]
DropDown — UITableVieeController
Search bar -  Done
crash
account summary didselect overdue, paid
Present view controller
iPad test
iPhone5
Landscape test
Remove tooltip
remove coreplot
Library html
Launch screen
iPad Screenshots
inventory
Fabric
flurry
navigation title click
contacts
iPad pro
pie graph value
Next Phase
graph jbgraph
whatsapp pdf
swift-objective
ipad arabic
iPad screensots
NSdateformatter
poview from sync
html
observer hit
georgeon check
critism
videos
help
reload
Payment
push notification
make in india
passcode
firebase alert on foreground
ios8, 9 ,10 notification test
setting passcode commented line number 95 
Foreground alert Change Firebase
core plot
crash mbprogresshud
invoice changes in first row.
release certificate in firebase
accounts check on back
Firebase License
unit of measure —> create new item desgin
null check for old users
Accounts, Inventory UI test back
notification web page open
Barcode, sku again test
badge count 0
Life time subscription test
Life time
login mbprogresshud
peek and pop
test for push notifcation
flurry peek pop, condition
web push time 
naveen wala mail karna hai
Buyer detail
buyer detail invoice
Force close remove
force touch double remove 
local reminder for trial period — Add time in unixstamp
Exit company alert
flurry force touch
icons force touch
hide edit invoice button in send invoice
first screen design landscape icon 200*200 577*351
ipad splash screen
ipad home screen text size
restore dialoog ipad
comment code for dropbox sync in action sheet
dropbox sync test, app delegate
iCloud multiple file
easybooks, invoicemaker
set username defaults after login
text field cross
intial and username
admin disable on login
usermanagement hadana
company logo
upar account summary hide
display sales invoice company logo, 
height check in setting class
Buyer detail multiline in invoice
refresh not happening in account summary
set all defaults yes
Every Dropbox case check sucess and failure case, remove 
changes in getMaxSerialVchNoGivenVchType, getMaxSerialVchNoGivenOrderType, checkDuplicateVoucherNumber, vchNoExists, orderNoExists
1. Postnotification banana
2. SetGlobalDb !isAdmin and !databasePath databasepath bangea

exit, didfinishlaunching, logi
isadmin = true
database path = null
user create - keyboard shall be small letters by default
check for latest only admin case
Without admin case remove info button
Tax account commit code verified
[[DataHelper sharedDataHelperObject] getGlobalCompanyDb] - check everywhere in code
Allow backdated remove
Offline Upload : Twice calling, Delete line, MBProgessHUD remove, Testing, 15,20 files 20 upload try, 
first time taking time user login
Edit tax group
import failed summary to be corrected
issues in switchview create tax group switch issue
iPad and rotation before upload
user login -time should not come in account summary
content in checkuserpermission
Failed tp insert category n while creating estimation
account summary iphone 5s



MTBBarcodeScanner ipad
Tax name should not be same as account name
Flurry Check


refdoc sync across devices
db transaction commit


update library deopbox

Check +/- in invoice..single tax and total tax case both
search generic array
App Review inside app ios10.3


add same code in all types of transactions save, sql rollback


SRPR Multiple discount
Templates settings
pdf high defination


3 times login
already purchased
first time issue

no itunes restriction found
1. yearly to monthly plan done, new date is saved year after date
2. New user
3. Old user done, 
4. phone change wih same itunes id
5. phone change with same user id

6. New user with dummy id
7. phone change android-iphone
8. auto renew test 
9. 30, 31 days Now only api will execute after exppiration,
10. family sharing
11. iTunes live check


Release
keychain off while release
FirebaseAppDelegateProxyEnabled No




Next release:
Peek pop button
Multiple companies crash syncallowed
remove async task from create vourcher- save sjould be in single thred in 
Debug/release mode
image upload item in dropbox
analyse








after 5 times api hit
cancellation funda
compare expiry date with current one
api

-Resizing the app for iPhone and pro models 
	iPhone - 25 days
	iPad pro - 20 days
-re-doing prop shop and categories 
	Categories and new design - 18-20 days
-adding account management/ collaborative stage feature  
	We will use firebase - 15 days
- favorites function 
	12 days
- fix printing
	4 days
- Push notification
	7 days, we will use firebase
- predictive text and spell check
	3 days
- Walk through
	5 days - we will need arts for that
- Videos tutorials
	6 days
- duplicate issue debug if any user will provide icloud file 
	1 day
- SymphonicPercussion pack change
	3 days
- User signup, login with facebook
	12 days
I think this will be 3-4 month effort. we can prfioritize according to time and budget.

Black and white printing



371843284










"expires_date" = "2017-04-19 07:22:42 Etc/GMT";
    "expires_date_ms" = 1492586562000;
    "expires_date_pst" = "2017-04-19 00:22:42 America/Los_Angeles";
    "is_trial_period" = false;
    "original_purchase_date" = "2017-03-07 10:06:30 Etc/GMT";
    "original_purchase_date_ms" = 1488881190000;
    "original_purchase_date_pst" = "2017-03-07 02:06:30 America/Los_Angeles";
    "original_transaction_id" = 1000000279702591;
    "product_id" = "com.Justapps.BookKeeper.1monthAuto";
    "purchase_date" = "2017-04-19 07:17:42 Etc/GMT";
    "purchase_date_ms" = 1492586262000;
    "purchase_date_pst" = "2017-04-19 00:17:42 America/Los_Angeles";
    quantity = 1;
    "transaction_id" = 1000000291681976;
    "web_order_line_item_id" = 1000000034865203;



Forgot password html page


Skip/sign in flow
new itunes account
push notifcation
swipe down/up
Share page




Hi, Thanks for reply. Below is code details:

///After getting files list calling this method for downloading file from dropbox
-(BOOL)downloadAndDelete :(NSString*)fileName :(NSString *)companyName :(NSString *)uName :(int)fileType{
    __block BOOL didWriteSuccessfull = NO;

//dispatch_semaphore_t for downloading in order
     dispatch_semaphore_t sem = dispatch_semaphore_create(0);
        NSString *srcPath = [NSString stringWithFormat:@"/%@/%@/%@",companyName,uName,fileName];
        NSString *dstPath = [[DataHelper sharedDataHelperObject] getFolderPath:@"/JSON_Admin/"];

//Dropbox code
        DropboxClient *client = [DropboxClientsManager authorizedClient];
    downlodedFileNumber++;
        [[client.filesRoutes downloadData:srcPath]
         response:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBError *error, NSData *fileData) {
             if (result) {
                 NSString *filepath = [dstPath stringByAppendingPathComponent:[NSString stringWithFormat:@"%@",fileName]];
                 didWriteSuccessfull= [fileData writeToFile:filepath atomically:YES];
                 if (didWriteSuccessfull) {
                      dispatch_semaphore_signal(sem);
                     if ([self importExport:fileName :fileType :srcPath]) {
                         
		//Delete file after download
                         [client.filesRoutes delete_:srcPath];
                        
                          dispatch_semaphore_signal(sem);
                        
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                           }
                     }
                     else{
                        
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                           }
                         dispatch_semaphore_signal(sem);
                     }
                 }
             } else {
                  [self hideProgressBar];
      
             }
         }];

     dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
    return didWriteSuccessfull;
}


1. If above code if I remove dispatch_semaphore_wait  then files are not downloading in order
2. If I run above code then files are not downloading even its not calling error.

**Comment by monish152** [comment]
Hi, Thanks for reply. Below is code details:

```
///After getting files list calling this method for downloading file from dropbox
-(BOOL)downloadAndDelete :(NSString*)fileName :(NSString *)companyName :(NSString *)uName :(int)fileType{
    __block BOOL didWriteSuccessfull = NO;

//dispatch_semaphore_t for downloading in order
     dispatch_semaphore_t sem = dispatch_semaphore_create(0);
        NSString *srcPath = [NSString stringWithFormat:@"/%@/%@/%@",companyName,uName,fileName];
        NSString *dstPath = [[DataHelper sharedDataHelperObject] getFolderPath:@"/JSON_Admin/"];

//Dropbox code
        DropboxClient *client = [DropboxClientsManager authorizedClient];
    downlodedFileNumber++;
        [[client.filesRoutes downloadData:srcPath]
         response:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBError *error, NSData *fileData) {
             if (result) {
                 NSString *filepath = [dstPath stringByAppendingPathComponent:[NSString stringWithFormat:@"%@",fileName]];
                 didWriteSuccessfull= [fileData writeToFile:filepath atomically:YES];
                 if (didWriteSuccessfull) {
                      dispatch_semaphore_signal(sem);
                     if ([self importExport:fileName :fileType :srcPath]) {
                         
		//Delete file after download
                         [client.filesRoutes delete_:srcPath];
                        
                          dispatch_semaphore_signal(sem);
                        
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                           }
                     }
                     else{
                        
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                           }
                         dispatch_semaphore_signal(sem);
                     }
                 }
             } else {
                  [self hideProgressBar];
      
             }
         }];

     dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
    return didWriteSuccessfull;
}
```


1. If above code if I remove dispatch_semaphore_wait  then files are not downloading in order
2. If I run above code then files are not downloading even its not calling error.

**Comment by greg-db** [comment]
Thanks! Can you let me know what version of the SDK you have installed though? I notice that you're still using `response` instead of `setResponseBlock`. (It was renamed in v3.0.0.) Also, please let me know what version you updated from that was working for you.

Also, it looks like you aren't checking for an error (`routeError` and `error`). Make sure you check that. Additionally, it looks like you may be missing a `dispatch_semaphore_signal` in that code path?

In addition, you should make sure `authorizedClient` is not `nil` (if you're not already doing that elsewhere).

**Comment by monish152** [comment]
Hi There,

In previous we had 1.1.0 version and now we have updated to 3.0.14 version. Below is latest code after updation. and its not working.

I have checked authorizedClient is not nil. In below code I only changed setResponseBlock method from previous version. Now its not working. 

`-(BOOL)downloadAndDelete :(NSString*)fileName :(NSString *)companyName :(NSString *)uName :(int)fileType{
    __block BOOL didWriteSuccessfull = NO;
     dispatch_semaphore_t sem = dispatch_semaphore_create(0);
        NSString *srcPath = [NSString stringWithFormat:@"/%@/%@/%@",companyName,uName,fileName];
        NSString *dstPath = [[DataHelper sharedDataHelperObject] getFolderPath:@"/JSON_Admin/"];
        DBUserClient *client = [DBClientsManager authorizedClient];
    downlodedFileNumber++;
        [[client.filesRoutes downloadData:srcPath]
         setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *error, NSData *fileData) {
             if (result) {
                 NSString *filepath = [dstPath stringByAppendingPathComponent:[NSString stringWithFormat:@"%@",fileName]];
                 didWriteSuccessfull= [fileData writeToFile:filepath atomically:YES];
                 if (didWriteSuccessfull) {
                      dispatch_semaphore_signal(sem);
                     if ([self importExport:fileName :fileType :srcPath]) {
                         NSLog(@"import and delete successfully : %@ - %@",uName,fileName);
                         [client.filesRoutes delete_:srcPath];
                         [[DataHelper sharedDataHelperObject]deleteJsonFileFromAdmin:fileName];
                          dispatch_semaphore_signal(sem);
                         [self.table reloadData];
                         NSLog(@"/n %ld - %d",(long)filesListCount,downlodedFileNumber);
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                              [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:@"Import complete. Please tap on info button for summary" :self.view];
                             
                             NSDictionary *articleParams = [NSDictionary dictionaryWithObjectsAndKeys:@"Imported", @"Sync_Button", nil];
                             [Flurry logEvent:@"User_Management" withParameters:articleParams];
                         }
                     }
                     else{
                         NSLog(@"Import and delete failed : %@ - %@",uName,fileName);
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                              [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:@"Import complete. Please tap on info button for summary" :self.view];
                             
                             NSDictionary *articleParams = [NSDictionary dictionaryWithObjectsAndKeys:@"Imported", @"Sync_Button", nil];
                             [Flurry logEvent:@"User_Management" withParameters:articleParams];
                         }
                         dispatch_semaphore_signal(sem);
                     }
                 }
             } else {
                  [self hideProgressBar];
                 [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:error.errorContent :self.view];
                 NSLog(@"error : %@",error);
             }
         }];

     dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
    return didWriteSuccessfull;
}`

**Comment by greg-db** [comment]
What output are you getting? 

Also, I see that you're now printing `error`, but not `routeError`. You should check both. It looks like you're still missing `dispatch_semaphore_signal` in that path though. I.e., if an error occurs, your semaphore will never be released.

Likewise, it looks like you're missing a `dispatch_semaphore_signal` in the case where `didWriteSuccessfull` is not true.

**Comment by scobbe** [comment]
@monish152: Thanks for reaching out. In addition to @greg-db's recommendation that you add `dispatch_semaphore_signal` to all possible paths, I would recommend that you

1. update to v3.0.16 (as it fixes a threading regression from v3.0.14)
2. supply a specific (non-main) response queue to your `[client.filesRoutes downloadData:srcPath]` call (for example, `[NSOperationQueue new]`) with the `setResponseBlock` method. That way, you won't be blocking execution of your response handler with your `dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);` call.

**Comment by monish152** [comment]
ok @scobbe I will check on monday and will let you know.

**Comment by monish152** [comment]
`-(BOOL)downloadAndDelete :(NSString*)fileName :(NSString *)companyName :(NSString *)uName :(int)fileType{
    __block BOOL didWriteSuccessfull = NO;
     dispatch_semaphore_t sem = dispatch_semaphore_create(0);
        NSString *srcPath = [NSString stringWithFormat:@"/%@/%@/%@",companyName,uName,fileName];
        NSString *dstPath = [[DataHelper sharedDataHelperObject] getFolderPath:@"/JSON_Admin/"];
        DBUserClient *client = [DBClientsManager authorizedClient];
    downlodedFileNumber++;
        [[client.filesRoutes downloadData:srcPath]
         setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *error, NSData *fileData) {
             if (result) {
                 NSString *filepath = [dstPath stringByAppendingPathComponent:[NSString stringWithFormat:@"%@",fileName]];
                 didWriteSuccessfull= [fileData writeToFile:filepath atomically:YES];
                 if (didWriteSuccessfull) {
                      dispatch_semaphore_signal(sem);
                     if ([self importExport:fileName :fileType :srcPath]) {
                         NSLog(@"import and delete successfully : %@ - %@",uName,fileName);
                         [client.filesRoutes delete_:srcPath];
                         [[DataHelper sharedDataHelperObject]deleteJsonFileFromAdmin:fileName];
                          dispatch_semaphore_signal(sem);
                         [self.table reloadData];
                         NSLog(@"/n %ld - %d",(long)filesListCount,downlodedFileNumber);
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                              [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:@"Import complete. Please tap on info button for summary" :self.view];
                             
                             NSDictionary *articleParams = [NSDictionary dictionaryWithObjectsAndKeys:@"Imported", @"Sync_Button", nil];
                             [Flurry logEvent:@"User_Management" withParameters:articleParams];
                         }
                     }
                     else{
                         NSLog(@"Import and delete failed : %@ - %@",uName,fileName);
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             [self hideProgressBar];
                              [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:@"Import complete. Please tap on info button for summary" :self.view];
                             
                             NSDictionary *articleParams = [NSDictionary dictionaryWithObjectsAndKeys:@"Imported", @"Sync_Button", nil];
                             [Flurry logEvent:@"User_Management" withParameters:articleParams];
                         }
                         dispatch_semaphore_signal(sem);
                     }
                 }
             } else {
                  [self hideProgressBar];
                 [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:error.errorContent :self.view];
                 NSLog(@"error : %@",error);
             }
         }queue:[NSOperationQueue new]];

     dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
    return didWriteSuccessfull;
}`

1. I have updated library to v3.0.17
2. Now files are not downloading in order. And getting below logs. This is due to operation queue.

 This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.

**Comment by guidedways** [comment]
To avoid callback hell and not rely on a pyramid model that is error prone (not to mention, you cannot later introduce another 'download' in the middle of three successive downloads easily), I would recommend you initiate the first download in a background thread / queue, then simply use a boolean flag with the following after the first download call:

```ObjC
- (BOOL) downloadFileFromPAth.... {
BOOL _done = NO;

// download file here

// Call this after the loop
while (!_done) {
    [[NSRunLoop currentRunLoop] runMode: NSDefaultRunLoopMode beforeDate: [NSDate distantFuture]];
  }

  return YES;
}
```

And then just use this method easily to download multiple files:

```ObjC
[self downloadFileFromPAth:...];

[self downloadFileFromPAth:...];

[self downloadFileFromPAth:...];

```

and so on

**Comment by monish152** [comment]
There is dynamic data. i am reading multiple folders and calling download files with for loop. and I need to download all files in order as I hit that. It was working on 3.0.1

**Comment by guidedways** [comment]
Sure, the above solution I've provided you is perfect for looping in sequence. Not sure if it was working or not - I don't believe the SDK guarantees this (it never did in v2). We rely on this very approach since not only do we have to download files in sequence, we have dependencies between downloads, so file 2 depends on file 1 to have completed fully in order to join the two, for instance.

**Comment by guidedways** [comment]
@monish152 This is guaranteed to work irrespective of the SDK you use (network calls are not meant to block, and there's never a guarantee of 'sequential' download using a network library since one call may finish earlier than the other - or the OS may prioritise to its will).

**Comment by scobbe** [comment]
Thanks @guidedways for your helpful suggestion.

@monish152: If you wish to use the approach that you're currently, and not the implementation that @guidedways suggested, then please ensure the following:

1. You need to make sure the response code is being executed **on a different queue** from the queue that is executing `dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);`. You can either do as I suggested above and supply `[NSOperationQueue new]` with the `setResponseBlock` method **or** if your above code (`dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);`) is being executed off the main thread, then you can simply not supply a response queue at all (it will default to the main thread). But if you do supply a new queue, you need to dispatch all UI updates to the main thread, otherwise you will crash your app. So if you want to have the above code work, please dispatch all UI updates to the main thread.

2. As @greg-db has mentioned already, please add `dispatch_semaphore_signal(sem);` to your first `else` statement.

Once you have taken these steps, please repost your code, and we can continue to debug.

Thank you for your patience!

**Comment by monish152** [comment]
Hi @scobbe Thanks for help. 

I have changed my code to below code. In result set it seems working. I have tested roughly. Can you please have a look in code and see if I am missing something.
`-(BOOL)downloadAndDelete :(NSString*)fileName :(NSString *)companyName :(NSString *)uName :(int)fileType{
    __block BOOL didWriteSuccessfull = NO;
     dispatch_semaphore_t sem = dispatch_semaphore_create(0);
        NSString *srcPath = [NSString stringWithFormat:@"/%@/%@/%@",companyName,uName,fileName];
        NSString *dstPath = [[DataHelper sharedDataHelperObject] getFolderPath:@"/JSON_Admin/"];
        DBUserClient *client = [DBClientsManager authorizedClient];
    downlodedFileNumber++;
        [[client.filesRoutes downloadData:srcPath]
         setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *error, NSData *fileData) {
             if (result) {
                 NSString *filepath = [dstPath stringByAppendingPathComponent:[NSString stringWithFormat:@"%@",fileName]];
                 didWriteSuccessfull= [fileData writeToFile:filepath atomically:YES];
                 if (didWriteSuccessfull) {
                      dispatch_semaphore_signal(sem);
                     if ([self importExport:fileName :fileType :srcPath]) {
                         NSLog(@"import and delete successfully : %@ - %@",uName,fileName);
                         [client.filesRoutes delete_:srcPath];
                         [[DataHelper sharedDataHelperObject]deleteJsonFileFromAdmin:fileName];
                          dispatch_semaphore_signal(sem);
                         [self.table reloadData];
                         NSLog(@"/n %ld - %d",(long)filesListCount,downlodedFileNumber);
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             dispatch_async(dispatch_get_main_queue(), ^ {
                                 [self hideProgressBar];
                                  [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:@"Import complete. Please tap on info button for summary" :self.view];
                             });
                             NSDictionary *articleParams = [NSDictionary dictionaryWithObjectsAndKeys:@"Imported", @"Sync_Button", nil];
                             [Flurry logEvent:@"User_Management" withParameters:articleParams];
                         }
                     }
                     else{
                         NSLog(@"Import and delete failed : %@ - %@",uName,fileName);
                         if (filesListCount == downlodedFileNumber) {
                             [[DataHelper sharedDataHelperObject]updateDropboxDb];
                             dispatch_async(dispatch_get_main_queue(), ^ {
                                 [self hideProgressBar];
                                 [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:@"Import complete. Please tap on info button for summary" :self.view];
                             });
                           
                             NSDictionary *articleParams = [NSDictionary dictionaryWithObjectsAndKeys:@"Imported", @"Sync_Button", nil];
                             [Flurry logEvent:@"User_Management" withParameters:articleParams];
                         }
                         dispatch_semaphore_signal(sem);
                     }
                 }
             } else {
                  dispatch_semaphore_signal(sem);
                 dispatch_async(dispatch_get_main_queue(), ^ {
                     [self hideProgressBar];
                     [[CommonUIObjects sharedCommonUIObjectsInstance] showAlerView:error.errorContent :self.view];
                 });
                 NSLog(@"error : %@",error);
             }
         }queue:[NSOperationQueue new]];

     dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
    return didWriteSuccessfull;
}
`

**Comment by scobbe** [comment]
@monish152: Thanks for your reply! If I understand you correctly, your code is working correctly? Is that right?

As far as further advice, only a couple of things come to mind:
- remove the redundant `dispatch_semaphore_signal(sem);` after `if ([self importExport:fileName :fileType :srcPath]) {`
- handle your `delete_` call here `[client.filesRoutes delete_:srcPath];` (actually set a response block, and surface an error, if one occurs)

Other than that, things look good. Let us know if you have other questions / feedback on the SDK.

**Comment by monish152** [comment]
Thanks @scobbe its working perfect.

**Comment by scobbe** [comment]
@monish152: Great to hear! Let us know if anything else comes up, or if you have any feedback for the SDK. Good luck!

**Comment by alokfuterox** [comment]
How to get multiple file download Progress ?

Regards
Alok

**Comment by greg-db** [comment]
@alokfuterox You can set progress listeners for any/all of the download requests you initiate as documented here, using `setProgressBlock`:

https://github.com/dropbox/dropbox-sdk-obj-c#download-style-request

This is unrelated to this old thread though, so if something's not working for you, please open a new issue with the details so we can help without spamming the other people here:

https://github.com/dropbox/dropbox-sdk-obj-c/issues/new
