### ISSUE TITLE
3.0.15/16 sometimes fileContents is nil

### ISSUE THREAD

**Issue by chrisvanbuskirk** [dropbox/dropbox-sdk-obj-c#142]
I'm trying to figure out what's going on with this, but as of 3.0.15 my app is no longer functioning properly downloading files.  Looks like **sometimes** fileContents is nil after the progress block is finished.  Tried both 15/16.  I'm using threads to run each download.

**Comment by scobbe** [comment]
@chrisvanbuskirk: Sorry for this issue. The [latest version of the SDK](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.17) should fix your issue. Apologies for the inconvenience!

**Comment by chrisvanbuskirk** [comment]
@scobbe Thanks for the quick turnaround.  Everything looks good.

**Comment by tererecool** [comment]
Should this fix be in cocoapods ObjectiveDropboxOfficial 3.1.2? Because I'am having this same issue. Problem seems to be in following line of code:
`downloadContent = [NSData dataWithContentsOfFile:[location path]];`
The returned value is nil and errors are also nil.
