### ISSUE TITLE
AppStore Reject: using safari for auth flow

### ISSUE THREAD

**Issue by truebucha** [dropbox/dropbox-sdk-obj-c#145]
I have an app reject from app store. The main theme is I use safary instead of brand new SFSafaryViewController. 
![screen shot 2017-05-04 at 2 20 55 pm](https://cloud.githubusercontent.com/assets/16370048/25743372/b4bcb0c2-319c-11e7-9042-8500532f3861.jpg)
But for me it doesn't look like the thing I could use to authorize the user anyway. Any suggestions?
the deployment target of the app is 8.0. This limits me to version 3.0.10
I will try to use default not in browser option for now.

**Comment by scobbe** [comment]
@truebucha: Thanks for letting us know. If you update to the latest version of the SDK, it will automatically use `SFSafariViewController`? Let us know if you have any issues doing this.

**Comment by scobbe** [comment]
@truebucha: Any update here? Were you able to get this working?

**Comment by truebucha** [comment]
hi, I updated the pod to last available 8.0 version and pushed it to review. the app is in the store now. it is because you repo code implement in app web view auth without options now.
