### ISSUE TITLE
authorizeFromControllerDesktop doesn't work at times

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#148]
I distinctly remember that in one of the SDK updates, the Mac app was displaying a Dialog window where the user would authenticate and link. Now, it opens the browser like before. Sadly, at times clicking the 'Allow' button does nothing. Some users complain that clicking the button repeatedly also does not work. I've tried unlinking and linking our app just today and I've experienced the same issue. It seems to be happening randomly, at times it works and at times it doesn't. The 'dialog' I saw in one of the previous SDK versions worked like a charm though - not sure if that was something deliberately disabled.

**Comment by greg-db** [comment]
Thanks for the report! Are you seeing this in any particular browsers/versions? We'll try to reproduce it here.

**Comment by scobbe** [comment]
@guidedways: Thanks for reaching out. Yes, the dialog unfortunately was deliberately disabled. Companies like Google, which Dropbox uses as an identity provider, are starting to force everyone away from using lightweight web-views, in favor of full-fledged browsers (for security reasons). Hence our shift to `SFSafariViewController` on iOS and default browser for macOS.

In the past, I have noticed an issue like this sometimes if I have also run the iOS version of the app. I assumed this was only a development time issue, and not an actual production issue. My thought was that when both iOS and macOS apps have the same redirect uri, the OS can get confused about which app to redirect to.

Would you try reproing this again one more time? When you do, would you mind running the following command:

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`

Then (without relaunching the iOS version of your app) try repeatedly going through the macOS flow and see if you notice this issue.

Let me know – thanks!

**Comment by scobbe** [comment]
@guidedways: Ok, I looked into this some more. What I've observed is sometimes that app doesn't go to the foreground up redirect (but the actual redirect still works). If this is the issue that you're encountering, I recommend adding the following code to your app delegate:

`[[NSRunningApplication currentApplication] activateWithOptions(NSApplicationActivateAllWindows | NSApplicationActivateIgnoringOtherApps)];`

This will force your application to the foreground upon redirect.

Checkout out the updated README [here](https://github.com/dropbox/dropbox-sdk-obj-c#macos-5) for a full example.

Please let me know if this is the issue you're experiencing, and the above suggestion resolves it. Thank you!

**Comment by scobbe** [comment]
@guidedways: Any updates? Was this connected to the issue at all?

**Comment by guidedways** [comment]
Hi @scobbe sorry, I did try this and it seems that was it! I had something similar before but used your code verbatim and that seems to have fixed it for me at least. I'll continue to monitor this as I know some people have had issues with using Safari directly at times - not sure why.

**Comment by scobbe** [comment]
@guidedways: Great to hear! Do let us know if the issue resurfaces, or if other problems arise. Closing for now.
