### ISSUE TITLE
`clientModified` never updates after uploading

### ISSUE THREAD

**Issue by olliwang** [dropbox/dropbox-sdk-obj-c#15]
Hi, @scobbe. I was trying to use the `uploadURL:mode:autorename:clientModified:mute:inputURL` method with `overwrite` mode to upload a file and update the `clientModified` attribute at the same time. However, it seems the `clientModified` value never updated. The corresponded `DBXFILESFileMetadata` object always reports the old value no matter how many times I tried to alter it. Does the SDK cache the value somewhere or does the Dropbox will update the value after a long time? Thanks.

Updated:
After some experiments, I found that this issue happens when trying to upload a exact same file to Dropbox. It seems Dropbox server just ignores the uploaded `clientModified` parameter if there is already a same copy on the server, and keeps the old `clientModified` value. Can anyone confirm this?

**Comment by greg-db** [comment]
Yes, that's correct, if you upload the exact same data to a given path, Dropbox won't update the metadata since nothing really changed.
