### ISSUE TITLE
DBDownloadUrlTask failure

### ISSUE THREAD

**Issue by euroboy** [dropbox/dropbox-sdk-obj-c#153]
DBDownloadUrlTask works well, showing progress until 100%, but in response block it gives me the following error (and file is not downloaded in the end):

`DropboxClientError[{
    NSError = "Error Domain=NSCocoaErrorDomain Code=4 \"\U201cCFNetworkDownload_dxtMTH.tmp\U201d couldn\U2019t be moved to \U201cDocuments\U201d because either the former doesn't exist, or the folder containing the latter doesn't exist.\" UserInfo={NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/.../Library/Caches/com.apple.nsurlsessiond/Downloads/test/CFNetworkDownload_dxtMTH.tmp, NSUserStringVariant=(\n    Move\n), NSFilePath=/private/var/mobile/Containers/Data/Application/.../Library/Caches/com.apple.nsurlsessiond/Downloads/test/CFNetworkDownload_dxtMTH.tmp, NSDestinationFilePath=/var/mobile/Containers/Data/Application/.../Documents/sound2.mp3, NSUnderlyingError=0x14641e40 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}";
}];`

**Comment by scobbe** [comment]
@euroboy: Thanks for reaching out. Could you confirm which version of the SDK you're using? Also some sample code to reproduce would be helpful. Thanks!

**Comment by euroboy** [comment]
I'm using ObjectiveDropboxOfficial (3.0.15)

Sample code:
`- (void) downloadDropBoxFile:(DBFILESFileMetadata *) dbFile toPath:(NSString *) destinationPath
{
    NSString *path = [NSString stringWithString:dbFile.pathLower];
    __block DBDownloadUrlTask *task = [self.client.filesRoutes downloadUrl:path overwrite:YES destination:[NSURL fileURLWithPath:destinationPath]];
    
    [task setResponseBlock:^(id  _Nullable response, id  _Nullable routeError, DBRequestError * _Nullable error, NSURL * _Nonnull destination) {
        
        if (response)
        {
            NSLog(@"File loaded into path: %@", destinationPath);
        }
        else
        {
            NSLog(@"%@\n%@\n", routeError, error);
        }
    }];
    
    [task setProgressBlock:^(int64_t bytesWritten, int64_t totalBytesWritten, int64_t totalBytesExpectedToWrite) {
        
        float progressPercentage = (float) totalBytesWritten / totalBytesExpectedToWrite;
        progressPercentage *= 100.0f;
        NSLog(@"progress = %f", progressPercentage);
    }];
}`

**Comment by scobbe** [comment]
@euroboy: Would you mind updating to the latest version of the SDK (v3.1.0)? A number of download bugs have been fixed in recent versions.

Once you have updated to the latest version, please let me know if the problem you're experiencing still persists. Thank you.

**Comment by euroboy** [comment]
Yes, version 3.1.0 works well. Closing the issue and thanks for help )

**Comment by scobbe** [comment]
Great to hear! Let us know if anything else comes up, or if you have any feedback for the SDK.

**Comment by kennybuc** [comment]
@scobbe Can you please tell me how I can update the dropbox official sdk which I've installed with Cocoapods?

**Comment by scobbe** [comment]
@kennybuc: Sure thing. Go to the folder that contains your `Podfile` and run `pod update`.

**Comment by JustStoryteller** [comment]
@scobbe update doesn't work, the latest version is ObjectiveDropboxOfficial (3.0.15) after 'pod update'

**Comment by scobbe** [comment]
@JustStoryteller: `rm Podfile.lock; rm -rf Pods/; pod install` should update. Let me know if that doesn't work.

**Comment by JustStoryteller** [comment]
@scobbe unfortunately, it doesn't work too

**Comment by kennybuc** [comment]
@JustStoryteller Please try the followings.
pod 'ObjectiveDropboxOfficial', '~>3.1.0'

Pod update doesn't work sometimes and when I specify the version, I can get the latest version of sdk.
pod 'ObjectiveDropboxOfficial', '~>3.x.x'
You can specify the latest version you find on this repository as well.

https://github.com/dropbox/dropbox-sdk-obj-c/blob/master/ObjectiveDropboxOfficial.podspec
The podspec indicates which the latest version is so you can easily know.

Let me know if you have got any new issue.

**Comment by JustStoryteller** [comment]
@kennybuc, @scobbe thank you for your help! It's OK

**Comment by semionenko** [comment]
Hi, I see the same problem in SDK 3.3.3.

DropboxClientError[{
    NSError = "Error Domain=NSCocoaErrorDomain Code=4 \"\U201cCFNetworkDownload_f3HZ60.tmp\U201d couldn\U2019t be moved to \U201cDocuments\U201d because either the former doesn't exist, or the folder containing the latter doesn't exist.\" UserInfo={NSSourceFilePathErrorKey=/Users/meteorx/Library/Developer/CoreSimulator/Devices/30D277D8-4B9D-4FFE-BD20-322502775B51/data/Containers/Data/Application/9504E6C3-2501-42FA-931E-97D555BEC060/Library/Caches/com.apple.nsurlsessiond/Downloads/com.test.app/CFNetworkDownload_f3HZ60.tmp, NSUserStringVariant=(\n    Move\n), NSDestinationFilePath=/Users/meteorx/Library/Developer/CoreSimulator/Devices/30D277D8-4B9D-4FFE-BD20-322502775B51/data/Containers/Data/Application/9504E6C3-2501-42FA-931E-97D555BEC060/Documents/test.backup, NSFilePath=/Users/meteorx/Library/Developer/CoreSimulator/Devices/30D277D8-4B9D-4FFE-BD20-322502775B51/data/Containers/Data/Application/9504E6C3-2501-42FA-931E-97D555BEC060/Library/Caches/com.apple.nsurlsessiond/Downloads/com.test.app/CFNetworkDownload_f3HZ60.tmp, NSUnderlyingError=0x60800045ecf0 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}";

**Comment by greg-db** [comment]
@semionenko Can you share the code that reproduces this for you in 3.3.3? Thanks in advance!

**Comment by semionenko** [comment]
Pod update operation show me: Using ObjectiveDropboxOfficial (3.3.3)

backupMetadata - the result from listFolder task:

```
DBUserClient *userClient = [DBClientsManager authorizedClient];
[[userClient.filesRoutes listFolder:@""] setResponseBlock:^(DBFILESListFolderResult *response, DBFILESListFolderError *routeError, DBRequestError *networkError) { ... }];
```

Then I've tried download the file:
```
DBUserClient *userClient = [DBClientsManager authorizedClient];
NSString *outputFileName = [NSString stringWithFormat:@"test.backup"];
NSURL *outputDirectory = [[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask][0];
NSURL *outputURL = [outputDirectory URLByAppendingPathComponent:outputFileName];
[[[userClient.filesRoutes downloadUrl:backupMetadata.pathLower overwrite:YES destination:outputURL] setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *networkError, NSURL *destination) { ... }]];
```

**Comment by greg-db** [comment]
@semionenko Thanks! I just tried that code with 3.3.3 and unfortunately it doesn't reproduce the issue for me. I hate to be a bother, but can you share a small sample project that hits this error? We'll need to be able to reproduce it here to investigate it properly. Thanks in advance!

**Comment by LDima13** [comment]
The problem remained and it is not solved! still the same mistake!

**Comment by greg-db** [comment]
@LDima13 To help us look into the issue you're seeing, can you share the code for building the `fileInInboxURL` variable in your sample? Thanks in advance!

**Comment by LDima13** [comment]
fileInInboxURL - typy NSURL,
this is the correct URL, and once there the file is downloaded, then I delete it, and the second time it does not work

file:///Users/Dima/Library/Developer/CoreSimulator/Devices/766995EC-27DE-4BE5-9EBD-12342E2762A4/data/Containers/Data/Application/9CE49A84-7393-41EB-AC88-87E6E976BE6A/Library/Caches/TEST.TXT.BalansInfo

**Comment by greg-db** [comment]
@LDima13 Can you share the code to make that URL? Also, what are you deleting exactly (i.e., the file, or a parent folder), and how?

**Comment by LDima13** [comment]
the file is deleted. But this is not important, since any other file that has never been in this folder is not loaded.
After the program is restarted, ANY file is loaded once again, and the second time again this error.
I can only send a piece of code, since it is part of a large project

**Comment by greg-db** [comment]
@LDima13 We'll need to be able to reproduce the issue in order to help with it. Also, there are a number of other people on this thread, so in order to properly look into this, and avoid spamming them, please [open a new issue](https://github.com/dropbox/dropbox-sdk-obj-c/issues/new) and include the following information:

- the version of the SDK you're using (you mentioned 3.7.0)
- the error/output (the `DropboxClientError` you shared above)
- the exact steps to reproduce the issue
- the full code needed to reproduce the issue (a sample project would be great, but otherwise the minimal code should be sufficient, e.g., including how you build each parameter)

Thanks!

**Comment by LDima13** [comment]
OK
