### ISSUE TITLE
DropboxClientError while downloading large number of files 

### ISSUE THREAD

**Issue by bazimogmbh** [dropbox/dropbox-sdk-obj-c#157]
I'm using ObjectiveDropboxOfficial (3.1.1) and receive these errors randomly when i try to download large number of files -

>  DropboxClientError[{
>      NSError = "Error Domain=NSURLErrorDomain Code=-997 \"Lost connection to background transfer service\" UserInfo={NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/download, NSLocalizedDescription=Lost connection to background transfer service, NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/download}";
> 
> DropboxClientError[{
>     NSError = "Error Domain=NSURLErrorDomain Code=-1 \"unknown error\" UserInfo={NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/download, NSLocalizedDescription=unknown error, NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/download}";
> }];
> 

I use a NSOperationQueue to send 10 parallel download requests at a time, many files do get downloaded but few get the error. All the dropboxFilePaths do exist.
Here is my code :

```
 NSOperationQueue *limitRequestsQueue = [NSOperationQueue new];
 limitRequestsQueue.maxConcurrentOperationCount = 10 ;
 for (DBFILESFileMetadata *file in files) {

 [limitRequestsQueue addOperationWithBlock:^{
      dispatch_semaphore_t blockingSemaphore = dispatch_semaphore_create(0);
      NSString* dropboxFilePath = file.pathLower;
       [[client.filesRoutes downloadData:dropboxFilePath] 
      setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, 
      DBRequestError *networkError , NSData* fileData) {
        if (result) {
            // Do something
          } else {
          }
      dispatch_semaphore_signal(blockingSemaphore);
    } ];
 } ];

```

**Comment by scobbe** [comment]
@bazimogmbh: I suspect that these requests are timing out because so many are queued up at one time. I wouldn't start more than 3-5 simultaneous requests at any one time. Would you try setting `maxConcurrentOperationCount = 3` and see if these errors still happen?

**Comment by bazimogmbh** [comment]
Works well with maxConcurrentOperationCount 3 & 5, Thanks.
