### ISSUE TITLE
restClient.filesRoutes listFolder no longer returns full folder content listing.

### ISSUE THREAD

**Issue by paulbeadle** [dropbox/dropbox-sdk-obj-c#158]
Over the last couple of days we've had a lot of complaints from users that they aren't seeing newly uploaded files in listings. Files that are uploaded are successfully listed using the Dropbox web site but aren't when using our app. We found that changing the restClient.filesRoutes listFolder API so that 'includeMediaInfo:[NSNumber numberWithBool:YES]' is changed to 'includeMediaInfo:[NSNumber numberWithBool:NO]' will allow the newly uploaded files to be listed correctly in our app. Is the server side software change going to be fixed so we can again use the includeMediaInfo option? If so, can we please have a timescale for the change?

**Comment by greg-db** [comment]
Yes, this is an issue on our side specific to using `includeMediaInfo` like this. We're working on it, and expect have all entries being properly returned tomorrow.

**Comment by paulbeadle** [comment]
Thank you for the update, we'll reassure our customers.

**Comment by greg-db** [comment]
This is fixed now. Calls to listFolder will now return the latest entries. Please let us know if you're still seeing any issues.

**Comment by paulbeadle** [comment]
Hi Greg. The listings are fine for us now and many of our customers, but a small number are still saying they aren't seeing all their files. It doesn't seem to be geographical because someone in the UK reports it doesn't work yet, but it's OK for us in the UK. Is the change taking time to roll out to all servers?

**Comment by greg-db** [comment]
@paulbeadle We're investigating a related issue affecting a smaller portions of cases around this. I'll follow up here once we have an update on that.

**Comment by greg-db** [comment]
This secondary issue should also be fixed now.
