### ISSUE TITLE
Podspec has wrong pod name

### ISSUE THREAD

**Issue by xaphod** [dropbox/dropbox-sdk-obj-c#16]
Hi! Thanks for making an obj-c SDK that we can use for API v2!
Looks like you're "released". I followed instructions for Pods, ie. `pod 'ObjectiveDropboxOfficial'`, but there's no pod known with that name. Looks like in your podspec you're still just called `ObjectiveDropbox`. Perhaps you didn't rename & push to cocoapods repo yet?

**Comment by scobbe** [comment]
Thanks @xaphod. We'll be pushing out a build to CocoaPods later today! I've updated the .podspec to correctly use `ObjectiveDropboxOfficial`
