### ISSUE TITLE
Dropbox SDK Dismisses my ViewController

### ISSUE THREAD

**Issue by danielgruber** [dropbox/dropbox-sdk-obj-c#160]
Hi There,

The dropbox SDK has one Bug I think: If it is opening the Dropbox App via URL, it although dismisses the current pushed ViewController from the Stack, even if it's not the WebViewViewController. This dismisses my Settings View, which is leading to the Problem that I am not able to handle the result correctly. 

What can I do?

Thanks!

Best

Daniel

**Comment by danielgruber** [comment]
Opening with nil as controller worked:

 [DBClientsManager authorizeFromController:[UIApplication sharedApplication]
                                       controller:**nil**
                                          openURL:^(NSURL *url) {
                                              [[UIApplication sharedApplication] openURL:url];
                                          }];

**Comment by ilyon** [comment]
A
-canOpenURL: failed for URL: "dbapi-8-emm://1/connect" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

> Opening with nil as controller worked:
> 
> [DBClientsManager authorizeFromController:[UIApplication sharedApplication]
> controller:**nil**
> openURL:^(NSURL *url) {
> [[UIApplication sharedApplication] openURL:url];
> }];

It's still worked? I got this error when set controller's to nil.

-canOpenURL: failed for URL: "dbapi-8-emm://1/connect" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
