### ISSUE TITLE
ViewController can't be release after authorizeFromController

### ISSUE THREAD

**Issue by josechen01** [dropbox/dropbox-sdk-obj-c#165]
ViewController can't be release after called authorizeFromController

**Comment by greg-db** [comment]
@josechen01 Can you elaborate on the issue you're experiencing? Please include the code to reproduce the issue, and the unexpected error/output you're getting. Thanks in advance!

**Comment by josechen01** [comment]
@greg-db 
I can reproduce by follow steps:
1.Present a ViewController
2.Invoke + (void)authorizeFromController:controller:openURL
3.Touch cancel button on Dropbox app, then it will back to my app
4.Dismiss the ViewController(vc can't be release)

I noticed that "DBMobileSharedApplication" will retain the viewcontroller, after cancel authorization, "_controller" should be set to nil.

**Comment by greg-db** [comment]
Thanks! We'll look into it.

**Comment by greg-db** [comment]
This should be fixed in v6.0.1.
