### ISSUE TITLE
Oauth not redirect back in iOS11 beta 4

### ISSUE THREAD

**Issue by sarunw** [dropbox/dropbox-sdk-obj-c#166]
Just FYI, since it still in beta. Here is what I get

![1simulator_screen_shot_-_iphone_6s_-_2017-07-28_at_11_29_52](https://user-images.githubusercontent.com/795368/28702811-c8ca84f2-7389-11e7-897a-e8f34faeb32b.png)
![2simulator_screen_shot_-_iphone_6s_-_2017-07-28_at_11_30_01](https://user-images.githubusercontent.com/795368/28702812-c9284254-7389-11e7-85e7-97d77009c51d.png)

**Comment by greg-db** [comment]
Thanks for the report!

**Comment by greg-db** [comment]
@sarunw It looks like you might be using an older version of the Dropbox SDK. Based on the screenshots you provided, you appear to be using the old `browserAuth` parameter. That had to be removed in [v3.0.11](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.0.11). That was one way to hit this issue on iOS 11. Please update to the latest version of the iOS SDK, currently v3.2.0. Doing so and updating your code to remove the `browserAuth` parameter will help your app avoid this issue.

There is also another way to trigger this issue, when processing the app authorization flow via the official Dropbox for iOS app, if installed. We're fixing this issue there in a future update to the official app itself.
