### ISSUE TITLE
v3.2.0 does not compile. Dozens of 'file not found' errors.

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#168]
Just did a clean checkout of `carthage update` (v3.2.0) and I get the following build error:

`DBTEAMPOLICIESOfficeAddInPolicy.h file not found`

This is in `DBTeamPoliciesObjects.m`. I can see the file exists but does not get added to the project for some reason.

**Comment by guidedways** [comment]
Just added this manually and it seems there are dozens more missing from the project file. I then tried downloading the project directly from GitHub and it seems the project file really does have dozens of files missing. Not sure what's going on,

**Comment by guidedways** [comment]
It seems the instructions on the main page are incorrect. It mentions v3.2.0 as the latest release, whereas the latest release should have been v3.1.2. Switching to 3.1.2 fixes it.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by Solublepeter** [comment]
As we can't use 3.2.0, due to the number of compile errors, is the official advice to use 3.1.2, or to wait for 3.2.0 to be fixed?

**Comment by greg-db** [comment]
I don't have an ETA for a fix right now, so feel free to use 3.1.2 for now.

**Comment by greg-db** [comment]
This should be fixed in the latest version, currently v3.3.2.
