### ISSUE TITLE
The project have to many issues, don't compile

### ISSUE THREAD

**Issue by businessOS** [dropbox/dropbox-sdk-obj-c#169]
carthage update --platform iOS
Error:
*** Building scheme "ObjectiveDropboxOfficial iOS" in ObjectiveDropboxOfficial.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/Laeramario/Documents/Proyectos/Xcode/iTopsolutions/Dental/DentalCheck/Carthage/Checkouts/dropbox-sdk-obj-c/Source/ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.xcodeproj -scheme ObjectiveDropboxOfficial\ iOS -configuration Release -derivedDataPath /Users/Laeramario/Library/Caches/org.carthage.CarthageKit/DerivedData/dropbox-sdk-obj-c/3.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

**Comment by businessOS** [comment]
Please just put a framework SDK file!

**Comment by greg-db** [comment]
Thanks for the report! This seems to be the same as #168, so I'm closing this in favor of that one.

I'm also sending this along as a feature request to also distribute the SDK as a framework file.

**Comment by neojino** [comment]
I have exactly same problem.
please Just put a framework SDK file, I can't any update with API V2 now.
