### ISSUE TITLE
Umbrella header file?

### ISSUE THREAD

**Issue by xaphod** [dropbox/dropbox-sdk-obj-c#17]
Small improvement suggestion: create a `"Dropbox.h"` which imports all the necessary header files, using `#ifdef` to determine platform if necessary.

Example why: I import the header file mentioned in the tutorial, I attempt the tutorial code `[[[client.filesRoutes createFolder...` to create a folder, and I get a compile error of `Property filesRoutes cannot be found in forward class object 'DropboxClient'`.

**Comment by scobbe** [comment]
Thanks @xaphod. Good idea. I went ahead and did that!
