### ISSUE TITLE
Is there a possibility to build for iOS 5.1 (iPad 1)?

### ISSUE THREAD

**Issue by PaulSlocum** [dropbox/dropbox-sdk-obj-c#172]
I have clients who have many iPad 1's that they use for their business with a Dropbox app of mine, which now stopped working because the API v1.0 was turned off.  My app has been updated for the new Dropbox API, but I can't find a way to build with a deployment target as low as 5.1 for the iPad 1.  I tried building with XCode 7, but it says that embedded frameworks are only supported on iOS 8.0 and later.  I did see that the stated requirement for this library is iOS 9+, but I figured I'd ask in case there's some workaround.

**Comment by greg-db** [comment]
@PaulSlocum Thanks for the post. This SDK doesn't support iOS 5.1. I'll pass this along as a feature request, but it's relatively unlikely that we'll be implementing support for that. Apologies I don't have better news!

For reference, there are some third party SDKs listed here, but I don't know what versions they support:

https://www.dropbox.com/developers/documentation/communitysdks

Alternatively, you can call the HTTPS endpoints directly:

https://www.dropbox.com/developers/documentation/http/documentation
