### ISSUE TITLE
Item already in "tmp" folder

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#178]
I got into a situation where a file got corrupt somehow in Dropbox. It wouldn't download correctly so I "restored" an older version using the web version of dropbox. The app now seems to pull changes just fine, however it now is now receiving these error from the library:

`Error Domain=NSCocoaErrorDomain Code=0 "(null)" UserInfo={errorContent=“EBF5E1F3-BF9B-46C6-8BE8-F0A9529E8025” couldn’t be moved to “tmp” because an item with the same name already exists.}
`
I presume this is because the file did indeed get downloaded earlier but was 0 bytes (corrupt). It now won't let me download it again since the SDK thinks it's already there. Restarting the app didn't clear "tmp". Any ideas?

**Comment by greg-db** [comment]
@guidedways For reference, can you share the code that triggers this?

If you're using one of [the `download` methods](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESUserAuthRoutes.html#/c:objc(cs)DBFILESUserAuthRoutes(im)downloadUrl:overwrite:destination:) though, you may want to set `overwrite` to true so you can overwrite that existing local file.

**Comment by guidedways** [comment]
This may be the reason why but I can no longer remember sorry. I do recall there were other issues fixed back then with how background download sessions work as there were some other similar issues. I think it's safe to close this issue.
