### ISSUE TITLE
Methods DeleteV2 and MoveV2 not working in SDK 3.3.3

### ISSUE THREAD

**Issue by semionenko** [dropbox/dropbox-sdk-obj-c#179]
Methods delete_ and move are deprecated. I try to use method deleteV2 (printed delete_v2 - wrong too) and moveV2.

`DBUserClient *userClient = [DBClientsManager authorizedClient];
[[userClient.filesRoutes deleteV2:backupMetadata.pathLower] setResponseBlock:^(DBFILESDeleteResult * _Nullable deleteResult, DBFILESDeleteError * _Nullable routeError, DBRequestError * _Nullable networkError) {...}`

deleteV2 not work: [DBFILESUserAuthRoutes deleteV2:]: unrecognized selector sent to instance
moveV2 not work: [DBFILESUserAuthRoutes moveV2:]: unrecognized selector sent to instance

**Comment by greg-db** [comment]
@semionenko The deprecation waring does have the wrong formatting for the non-deprecated method. I'll ask the team to get that fixed up.

I can't reproduce this unrecognized selector error for `deleteV2` and `moveV2` though. This runs for me:

```
DBUserClient *userClient = [DBClientsManager authorizedClient];
[[userClient.filesRoutes deleteV2:@"/somepath"] setResponseBlock:^(DBFILESDeleteResult * _Nullable deleteResult, DBFILESDeleteError * _Nullable routeError, DBRequestError * _Nullable networkError) {

    NSLog(@"%@", deleteResult);
    NSLog(@"%@", routeError);
    NSLog(@"%@", networkError);

}];

[[userClient.filesRoutes moveV2:@"/somepath1" toPath:@"/somepath2"] setResponseBlock:^(DBFILESRelocationResult * _Nullable moveResult, DBFILESRelocationError * _Nullable routeError, DBRequestError * _Nullable networkError) {

    NSLog(@"%@", moveResult);
    NSLog(@"%@", routeError);
    NSLog(@"%@", networkError);

}];
```

Can you double check you have 3.3.3 successfully installed, and perhaps trying cleaning and rebuilding?

**Comment by semionenko** [comment]
Pod update operation show me: Using ObjectiveDropboxOfficial (3.3.3)

**Comment by greg-db** [comment]
Thanks for following up. Unfortunately I'm still not able to reproduce this. Can you try my code sample above and let me know if that does or doesn't work for you? It may be useful to try it in [the sample app](https://github.com/dropbox/dropbox-sdk-obj-c/tree/master/Examples/DBRoulette) for comparison.

To help us look into this, please share the code that reproduces this, or ideally, a small sample project that does. Thanks in advance!

**Comment by semionenko** [comment]
Thanks for the help. You can close the issue. I've fixed the problem after remove pods and install it again.
