### ISSUE TITLE
How to remove session for a user when deleting app

### ISSUE THREAD

**Issue by Mudasir441** [dropbox/dropbox-sdk-obj-c#188]
I logged in to dropbox through my app. Then i delete the app without logout. When I again install the app, the user is logged in. How to logout user when deleting app?

**Comment by greg-db** [comment]
[Cross-linking for reference: https://stackoverflow.com/questions/46904825/user-not-logged-out-from-dropbox-and-google-drive-when-deleting-app ]

You should use [`DBClientsManager.unlinkAndResetClients`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBClientsManager.html#/c:objc(cs)DBClientsManager(cm)unlinkAndResetClients) to remove the stored access token.

Note that this is stored in the Keychain though, so it can persist across uninstallation/re-installation. There isn't a way to automatically run [`DBClientsManager.unlinkAndResetClients`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBClientsManager.html#/c:objc(cs)DBClientsManager(cm)unlinkAndResetClients) when the app is uninstalled, but you can detect a re-installation and run it then as noted in the answer to [the StackOverflow post](https://stackoverflow.com/questions/46904825/user-not-logged-out-from-dropbox-and-google-drive-when-deleting-app).
