### ISSUE TITLE
unlinkAndResetClient appears to not delete auth tokens as docs say it should

### ISSUE THREAD

**Issue by jerry-jpreng** [dropbox/dropbox-sdk-obj-c#194]
Starting with an authorized user, after I call unlinkAndResetClients, [DBClientsManager authorizedUser] is nil as expected. But, if I then trigger reauthorization with..
```
    [DBClientsManager authorizeFromController:[UIApplication sharedApplication]
                                   controller:self
                                      openURL:^(NSURL *url) {
                                          [[UIApplication sharedApplication] openURL:url];
                                      }];
```
...I am **not** presented with the 'Enter Username and Password' dropbox authentication screen, but with the  'Allow access to folder' screen, which shows the user as **already logged in** to the user whose auth tokens should have been deleted by the unlinkAndResetClients call. I want to be presented with the 'Enter Username and Password' dropbox authentication screen. (Yes, there is a sign-out button on the 'Allow access to folder' screen, but it's confusing to the user to have clicked a 'Forget my dropbox account info' button and then get logged in automatically because the info clearly hasn't been forgotten.')

**Comment by greg-db** [comment]
Thanks for the post. The `unlinkAndResetClients` method clears out `authorizedClient` and deletes the stored API access tokens from the keychain, but note that this is separate from the user's web session in the browser, which is based on the browser's cookies.

When the official Dropbox for iOS app isn't installed, this Objective-C Dropbox SDK uses `SFSafariViewController` to send the user through the web OAuth 2 app authorization flow. This involves them signing in to the Dropbox web site, if they aren't already signed in, to choose to authorize the API app.

Once that is done, the API app receives an access token for use with the Dropbox API, unrelated to the web session itself.

If the user wants to, they can sign out there, as you mentioned. When signing in to authorize an app, the browser also only gets "Session" cookies anyway, which are relatively short-lived. (The browser decides what a "session" is, but for example, it seems to be cleared when the app is restarted.) Users can also remotely log out of web sessions from their [security page](https://www.dropbox.com/account/security), similar to how they can unlink apps from their [connect apps page](https://www.dropbox.com/account/connected_apps).)

We'll consider this a feature request for a way to force the user to be logged out of the browser though.
