### ISSUE TITLE
DBFILESUserAuthRoutes , downloadURL:overwrite:destination API not working

### ISSUE THREAD

**Issue by ntnbkta** [dropbox/dropbox-sdk-obj-c#196]
Hi, I am trying to migrate API v1 to APIv2 and have completed successful integration of Dropbox new  iOS SDK using carthage.

I get a valid result for `getMetadata` API, but doesn't work for `downloadURL:overwrite:destination`.

I tried to debug and found out that  when I step into the instruction in `DBFILESUserAuthRoutes`, the `downloadURL:overwrite:destination` has path = nil, overwrite = overwrite but destination actully has the value I pass. 

I am blocked with this issue in my implementation. Please let me know if I am missing anything asap.

Thanks in advance.

**Comment by scobbe** [comment]
Hi there, please share some sample code with us. Thanks!

**Comment by ntnbkta** [comment]
We can close this issue. I sorted out that we were doing some timing out checks in out legacy code and this issue was happening because of that. Sorry for the inconvenience. Also thanks a lot for the timely response.
