### ISSUE TITLE
DBClientsManager authorizeFromController not working on device

### ISSUE THREAD

**Issue by amacymind** [dropbox/dropbox-sdk-obj-c#197]
Hello,
I am integrate Dropbox ios sdk in my app. For authenticate i am using method
`[DBClientsManager authorizeFromController:[UIApplication sharedApplication]
                                   controller:self
                                      openURL:^(NSURL *url) {
                                          NSLog(@"urlll:%@",url);
                                          [[UIApplication sharedApplication] openURL:url];
                                      }];`

but its works  only in simulator. It is not working on my iPhone/iPad with ios 10.2.1.

**Comment by greg-db** [comment]
Can you elaborate on what you're seeing? For example, what does or doesn't happen, and what error/output are you getting? Thanks in advance!

**Comment by amacymind** [comment]
Nothing happen on ios device. I tap on 'Link to Dropbox Account' then nothing happen on iPhone device. It works for simulator & redirect to dropbox login page view.

**Comment by amacymind** [comment]
Resolved. After add library in Embedded Binaries.
