### ISSUE TITLE
path_display sometimes with lowercase characters

### ISSUE THREAD

**Issue by everythingIsBuggy** [dropbox/dropbox-sdk-obj-c#198]
For some reason, sometimes a directory has only lowercase characters in the property path_display, although the real directory has uppercase characters.

Example folder-structure:

/directoryName
--/Sub#Dir1/
----/SubDir2/

Returning DBFILESMetadata Object:

{
    id = "id:a-bcdefgh-fsjfrejgierojgoe";
    name = SubDir2;
    "path_display" = "/directoryName/Sub#Dir1/subdir2";      // wrong
    "path_lower" = "/directoryname/sub#dir1/subdir2";
}

**Comment by greg-db** [comment]
Thanks for writing this up! Unfortunately, this behavior is sometimes expected. Even in `path_display`, the original casing isn't always available. There's a note about this in [the API v2 documentation](https://www.dropbox.com/developers/documentation/http/documentation), under "Case insensitivity": 
> Also, while Dropbox is case-insensitive, it makes efforts to be case-preserving. Metadata.name will contain the correct case. Metadata.path_display usually will contain the correct case, but sometimes only in the last path component. If your app needs the correct case for all components, it can get it from the Metadata.name or last path component of each relevant Metadata.path_display entry.

We understand this is non-ideal of course, and I'll forward this on to the team as feedback, but I can't make any promises as to if or when this might be improved in the future.
