### ISSUE TITLE
The old version of the dropbox platform is being retired on september 28 2017 warning

### ISSUE THREAD

**Issue by IgorRatynski** [dropbox/dropbox-sdk-obj-c#199]
I have "the old version of the dropbox platform is being retired on september 28 2017" warning, but I use a 3.3.5 version of framework, installed via Carthage, in .plist "dbapi-2". How it to solve?

![screen shot 2017-11-09 at 16 51 06](https://user-images.githubusercontent.com/11771792/32608856-ba8602cc-c56e-11e7-8d8b-9d50a2e82e56.png)

**Comment by greg-db** [comment]
To dismiss this message, sign in to the Dropbox account that owns that API app and go to the App Console:

https://www.dropbox.com/developers/apps

There will be a banner at the top of the page there where you can "acknowledge" the deprecation to dismiss this message.
