### ISSUE TITLE
Creating a folder that already exists yields unexpected error

### ISSUE THREAD

**Issue by xaphod** [dropbox/dropbox-sdk-obj-c#20]
Hi again! Hope this isn't too many issues filed in one day :)
When attempting to create a folder that already exists, I was expecting something in the routeError that would allow me to detect this, rather than having to look at error and sniff a 409 statusCode.
Is my expectation reasonable?

    [[[client.filesRoutes createFolder:subfolderName] response:^(DBFILESFolderMetadata *result, DBFILESCreateFolderError *routeError, DBError *error) {
    ... <debug breakpoint>
        (lldb) po result
         nil
        (lldb) po routeError
        {
            ".tag" = path;
        }

        (lldb) po error
        DropboxHttpError[{
            ErrorContent = "path/conflict/folder/..";
            RequestId = 53f8e192682948d93f4f925854e530e8;
            StatusCode = 409;
        }];

**Comment by scobbe** [comment]
@xaphod: Not at all! Really appreciate the help :) 

In this case, you actually are getting a structured response that informs you of the conflict. It's a little bit buried, though. I added a bit to the README on [error handling](https://github.com/dropbox/dropbox-sdk-obj-c#user-content-route-specific-errors) which might be helpful.

But as far as the example you brought up specifically, this might help:

```
[[client.filesRoutes createFolder:@"/test/path"] response:^(DBFILESFolderMetadata *result, DBFILESCreateFolderError *routeError, DBError *error) {
        if (result) {
            NSLog(@"%@\n", result);
        } else {
            if (routeError) {
                if ([routeError isPath]) {
                    DBFILESWriteError *writeError = routeError.path;
                    if ([writeError isConflict]) {
                        // handle
                    }
                }
            } else {
            }
            NSLog(@"%@\n%@\n", routeError, error);
        }
    }];
```

Two layers of indirection :)

Let me know if this helps

**Comment by xaphod** [comment]
Yup I like that a lot better than looking at the statusCode, thanks. Closing.

**Comment by scobbe** [comment]
@xaphod: I think what was confusing was the description method for the error type gave you a confusing result:

```
(lldb) po routeError
 {
    ".tag" = path;
 }
```

I've updated the repo, so now it should give you the following result:

```
(lldb) po routeError
{
    ".tag" = path;
    path =     {
        ".tag" = conflict;
        conflict =         {
            ".tag" = folder;
        };
    };
}
```
