### ISSUE TITLE
Sharable Link

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [dropbox/dropbox-sdk-obj-c#202]
Is there a way to add a sharable link along with the random photo in DBRoulette

**Comment by greg-db** [comment]
The `DBRoulette` example as written doesn't do it, but you can use [`createSharedLinkWithSettings`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGUserAuthRoutes.html#/c:objc(cs)DBSHARINGUserAuthRoutes(im)createSharedLinkWithSettings:) to create a new shared link for any file or folder, or [`listSharedLinks`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGUserAuthRoutes.html#/c:objc(cs)DBSHARINGUserAuthRoutes(im)listSharedLinks) to retrieve existing links.

**Comment by MarcAnthonyPhotography** [comment]
I've tried to do that but I am stuck. Do you do custom work? That's all I am looking for. When you press random photo you just list an NSLog with the sharable link to that photo.

**Comment by greg-db** [comment]
We don't offer custom code-writing services, but I'll be happy to help with whatever issues you're having with the API. Please share whatever isn't working for you and I'll take a look.

**Comment by MarcAnthonyPhotography** [comment]
That would really be amazing if you could. It's probably as simply as one line. I attached my version of DBRoulette. In photoviewcontroller.m I added a UILabel to display the sharable link and linked it in the main storyboard. You will see reference to this in line 107-108. All it does is display the filename when you hit random photo. I need it to display the full path to the image (i.e. https://www.dropbox.com/s/4mv65wiqmuwgea6/test.jpg?dl=0)
[DBRoulette.zip](https://github.com/dropbox/dropbox-sdk-obj-c/files/1514849/DBRoulette.zip)

**Comment by greg-db** [comment]
Where are you attempting to call `createSharedLinkWithSettings` or `listSharedLinks`? I don't see either in that file. You'll need to use one or both of those, depending on the situation. Those are both RPC style calls, so you'd call them like shown in the documentation here:

https://github.com/dropbox/dropbox-sdk-obj-c#rpc-style-request

Give that a try and let me know if it's not working for you, and if not, share your code and the error/output.

**Comment by MarcAnthonyPhotography** [comment]
That’s the problem I’m having Greg. I don’t know how to add that.

Cordially,
Marc A. Matteo

**Comment by greg-db** [comment]
Here's a basic example of calling these two methods:

```obj-c
NSString *filePath = @"/test.txt";
[[client.sharingRoutes createSharedLinkWithSettings:filePath] setResponseBlock:^(DBSHARINGSharedLinkMetadata *result, DBSHARINGCreateSharedLinkWithSettingsError *routeError, DBRequestError *networkError) {
    if (result) {
        NSLog(@"created shared link: %@\n", result.url);
    } else {
        NSLog(@"%@\n%@\n", routeError, networkError);

        if ([routeError isSharedLinkAlreadyExists]) {

            [[client.sharingRoutes listSharedLinks:filePath cursor:nil directOnly:@YES] setResponseBlock:^(DBSHARINGListSharedLinksResult *result, DBSHARINGListSharedLinksError *routeError, DBRequestError *networkError) {
                if (result) {
                    NSLog(@"existing shared link: %@\n", result.links[0].url);
                } else {
                    NSLog(@"%@\n%@\n", routeError, networkError);
                }
            }];

        }
    }
}];
```

**Comment by MarcAnthonyPhotography** [comment]
Thank you so much for that. It is exactly what I needed. I greatly appreciate you helping me.
