### ISSUE TITLE
Is there an api for iOS that can connect to Dropbox without setting Dropbox URL scheme in info.plist?

### ISSUE THREAD

**Issue by FreemanYan** [dropbox/dropbox-sdk-obj-c#203]
Is there an api for iOS that can connect to Dropbox without setting Dropbox URL scheme in info.plist?
Because URL scheme in info.plist is read-only, I want to set something dynamically for each user to connect to his own Dropbox.

**Comment by greg-db** [comment]
I'm not sure I understand your request. The URL schemes you [should set in the plist](https://github.com/dropbox/dropbox-sdk-obj-c#application-plist-file) for the Dropbox SDK are not user-specific. They allow any user of your app to be sent through the app authorization flow, and do not need to be set dynamically. Can you elaborate on what you're trying to do and what isn't working? Thanks in advance!

**Comment by FreemanYan** [comment]
But there is a limitation of max  500 user connections per URL scheme, right? is this number of concurrent connection? or cumulative connection? Thanks.

**Comment by greg-db** [comment]
I'm not sure I know what you're referring to. Can you link to the relevant documentation? (You may be thinking of [the limit on `canOpenURL`](https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl)?)

**Comment by FreemanYan** [comment]
In App Console, pls see the attached screen shot. is this a limitation per URL scheme?
![dropbox](https://user-images.githubusercontent.com/17807880/33863676-e9c92f2c-df23-11e7-8621-c24a1f7ba314.JPG)

**Comment by greg-db** [comment]
I see, thanks for clarifying. That 500 user limit is the maximum number of users that can connect to your Dropbox API app while it is in development mode. (More info [here](https://www.dropbox.com/developers/reference/developer-guide#production-approval).) This isn't really related to the URL scheme setup for the SDK. You should set up the URL schemes as documented, and it will allow arbitrary users to connect to your app. That 500 user limit is enforced by the Dropbox servers, not the SDK.
