### ISSUE TITLE
listFolderContinue - not returning enough information

### ISSUE THREAD

**Issue by kalsky** [dropbox/dropbox-sdk-obj-c#204]
I tried the api call using this web page:
https://dropbox.github.io/dropbox-api-v2-explorer/#files_list_folder/continue
and I can see that it returns some good information about the entries that were changed:
```
{
  "entries": [
    {
      ".tag": "file",
      "name": "file.zip",
      "path_lower": "/backup/file.zip",
      "path_display": "/Backup/file.zip",
      "id": "id:DKz7xfb7BoAAAAAAAAAABA",
      "client_modified": "2017-12-09T16:19:36Z",
      "server_modified": "2017-12-09T16:19:36Z",
      "rev": "5452695749",
      "size": 2570,
      "content_hash": "0c395b522b3d47790437a7f7e99b3d89447d7f4c7ab949dcd5df8397721ec21c"
    }
  ],
  "cursor": "ABEeRtyVJN1kImQC7P8heeJWuwMQ9FEjiXIQmBR62Bl-bje8Xnrcz19gdSAuujOjw5ZR16ZlpLnt0-GUoHC0K1yH4MQ7_IQFjKcVGaDuIQ13g6iBbbrw_-4iR4_LMj6wj3cwydxaALaOb_Rz4fKXb29k84P_eVhwnN9f3PGPhwAKs-Ix21GToKMimakaSLn_2MA",
  "has_more": false
}
```

But when using the listFolderContinue api method from the code, the entries are from type DBFILESMetadata, which only has the following properties: name,pathLower,pathDisplay,parentSharedFolderId

Seems like the server returns a combination of DBFILESMetadata and DBFILESFileMetadata for each entry, can you update the return value to support it as well?

Use case:
I'm trying to find a way to monitor for file changes and download a specific file only if it got changed. But sometimes my application is making the changes and uploads the file, so a listFolderLongPoll that is waiting for changes (made by other devices) will also get to the response block.
In it, I'm trying to figure out if the change was done by this device or another device, so I thought of comparing the revision number or client modified date that I got when I'm uploading the file.
Problem is, there is no easy way to get the revision number of the file that changed using the above functions, so I'll have to listRevisions of a file whenever I'll get a notification that it got changed... 

If there is a better way to solve this use case, please let me know.

**Comment by greg-db** [comment]
Every object in the [`DBFILESListFolderResult.entries`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESListFolderResult.html#/c:objc(cs)DBFILESListFolderResult(py)entries) returned by [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESUserAuthRoutes.html#/c:objc(cs)DBFILESUserAuthRoutes(im)listFolder:) and [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESUserAuthRoutes.html#/c:objc(cs)DBFILESUserAuthRoutes(im)listFolderContinue:) will be of type [`DBFILESMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESMetadata.html). 

Each one will be one of [`DBFILESFileMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESFileMetadata.html), [`DBFILESFolderMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESFolderMetadata.html), or [`DBFILESDeletedMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESDeletedMetadata.html), all of which are sub-classes of [`DBFILESMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESMetadata.html).

You can see which specific type a particular entry is by using `isKindOfClass`, and then cast it accordingly to access the properties specific to that type as [shown here](https://github.com/dropbox/dropbox-sdk-obj-c#response-handling-edge-cases).

Hope this helps!
