### ISSUE TITLE
Email invitation not working because of captcha.

### ISSUE THREAD

**Issue by carlos-mateo** [dropbox/dropbox-sdk-obj-c#205]
After sending email invitation to people, when they follow the link and try to sign up, after they have introduced their data, password, and accepted Dropbox Terms in the form, a red text appears saying:
"Please enter a CAPTCHA response."
The issue is that there is no CAPTCHA and no extensions installed to block anything.
We have tried in different browsers (Firefox, Chrome, Safari), computers (Mac, Linux) and incognito windows with no luck.
It wasn't happening for the last person, it started today.

Thanks.

**Comment by greg-db** [comment]
It sounds like this is more of an issue with the Dropbox web site itself, and not the Objective-C SDK, so I'm afraid this is the wrong place for this issue.

Please open a support ticket for the web site here instead:

https://www.dropbox.com/support/email/other/submit

Thanks!
