### ISSUE TITLE
An error prompt up when download any file

### ISSUE THREAD

**Issue by FreemanYan** [dropbox/dropbox-sdk-obj-c#206]
An error prompt up when download any file, each time. but finally the data will be downloaded completely. another question: is it possible to stop the download process?

```
[[[client.filesRoutes downloadData:@"/my_file.txt"]
    setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *networkError,
                       NSData *fileContents) {
      if (result) {
        NSLog(@"%@\n", result);
        NSString *dataStr = [[NSString alloc] initWithData:fileContents encoding:NSUTF8StringEncoding];
        NSLog(@"%@\n", dataStr);
      } else {
        NSLog(@"%@\n%@\n", routeError, networkError);
      }
    }] setProgressBlock:^(int64_t bytesDownloaded, int64_t totalBytesDownloaded, int64_t totalBytesExpectedToDownload) {
  NSLog(@"%lld\n%lld\n%lld\n", bytesDownloaded, totalBytesDownloaded, totalBytesExpectedToDownload);
}];
```

![downloaderror](https://user-images.githubusercontent.com/17807880/33992281-f039b8aa-e10c-11e7-87e6-08b663ee031b.JPG)

**Comment by greg-db** [comment]
This error is actually coming from a `listFolder` call (not the `downloadData` call in the code you shared), where you have the error being shown in an alert box. Please check where in your code that you call `listFolder`. The error itself is indicating that the path you're calling for is not a folder, and so can not be listed by `listFolder`.

You can cancel an individual download call by calling cancel on the task object itself, like this:

```
DBDownloadDataTask *req = [client.filesRoutes downloadData...
[req cancel];
```
