### ISSUE TITLE
CAPTCHA Error

### ISSUE THREAD

**Issue by cedarpoolst** [dropbox/dropbox-sdk-obj-c#207]
Hi, I keep getting this CAPTCHA error asking me to do a captcha, but the prompt is never available.  Any suggestions?

![screen shot 2017-12-28 at 1 50 57 am](https://user-images.githubusercontent.com/24502187/34407364-ed0b1f3c-eb72-11e7-9bef-2f977d47ca90.png)

**Comment by greg-db** [comment]
@cedarpoolst Can you let me know what OS and browser version(s) you're seeing this with? Thanks in advance!

**Comment by symbiologist** [comment]
I am having this same problem as well. 

Tested on both Mac (latest High Sierra) and Windows 10 (on a new computer).
On Mac I could not see any captcha field using the following browsers: Chrome, Opera, Firefox, or Safari. I have disabled adblock on all of these
On Windows I tested it on a new PC with Microsoft Edge and also a fresh install of Google Chrome.
Any help would be appreciated! Trying to help set up Dropbox for my father.

Best,

David

**Comment by greg-db** [comment]
Thanks! Unfortunately, I'm unable to reproduce this issue. This appears to be an issue with the Dropbox web site itself though, and not the Objective-C SDK itself anyway. That being the case, if you're still seeing this, please instead open this as a Dropbox support directly either [here](https://www.dropbox.com/support/email/other/submit), if this is occurring whether or not you're using the API/SDK, or [here](https://www.dropbox.com/developers/contact) if it is only affecting the API/SDK flow.
