### ISSUE TITLE
Sharable link to uploaded files in dropbox V2 version

### ISSUE THREAD

**Issue by ViswanathB84** [dropbox/dropbox-sdk-obj-c#208]
Thank you very much for developing and supporting great library. I used below lines code for sharing url  in dropbox v1 version.

```
  [[self restClient] loadSharableLinkForFile:filePath];

- (void)restClient:(DBRestClient*)restClient loadedSharableLink:(NSString*)link 
           forFile:(NSString*)path{
    NSLog(@"link %@",link); //this is the sharable link 
    NSLog(@"File Path %@ ",path); // this is the path of the file 

}

- (void)restClient:(DBRestClient*)restClient loadSharableLinkFailedWithError:(NSError*)error{
    NSLog(@"Error %@",error);
}
```
I did not see any related code for sharing in Dropbox v2 version. Please let me know how can I do this.

**Comment by greg-db** [comment]
In the Dropbox API v2 Objective-C SDK, the replacement for `loadedSharableLink` is [`createSharedLinkWithSettings`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGUserAuthRoutes.html#/c:objc(cs)DBSHARINGUserAuthRoutes(im)createSharedLinkWithSettings:settings:) to create a new shared link, or [`listSharedLinks`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGUserAuthRoutes.html#/c:objc(cs)DBSHARINGUserAuthRoutes(im)listSharedLinks:cursor:directOnly:) to retrieve existing shared links. (The sharing methods are in `sharingRoutes`.)
