### ISSUE TITLE
Completion handler not called if operation fails

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#210]
I'm referring to the file `DBDelegate.m`, method `addRpcResponseHandler`

If `completionData` is nil, the passed `handler` is never invoked, and so if the calling method is depending on this (i.e. waiting on a semaphore) it blocks forever. 

This is a serious bug. In the same file you can see the handler is never invoked on other situations either. When completionData is nil, an error should be thrown instead.

I was able to reproduce this with an active Wifi Connection but no internet - the Dropbox SDK seems to hang the calling thread forever.

More specifically I think it needs to handle it like so in the else part:

```objc
     if (completionData.responseError) {
        [queueToUse addOperationWithBlock:^{
          handler(nil, nil, completionData.responseError);
        }];
      }
```

**Comment by guidedways** [comment]
As an example, since the completion handler was never called, this hung forever:

```objc
  dispatch_semaphore_t sema = dispatch_semaphore_create(0);
  
  [[[DBClientsManager authorizedClient].filesRoutes search: [self getResolvedDropboxFolderPath: DROPBOX_WEBDAV_ROOT_DIR] query:
    searchFor] setResponseBlock: ^(DBFILESSearchResult *searchResult, DBFILESSearchError *searchError, DBRequestError
                                   *requestError) {
    if (searchResult != nil) {
      allResults = searchResult;
    }
    
    [self setAsyncError: requestError];
    
    dispatch_semaphore_signal(sema);
  }];
  dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);
```

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by scobbe** [comment]
@guidedways: Sorry for the delay here. The [latest version of the SDK](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.6.0) should fix this.

Basically, we were accidentally using a 480 sec timeout (which we use for longpoll) instead of the default 60 sec. The response block should now be executed after 60 sec in the event of a connection outage.

**Comment by guidedways** [comment]
Thanks scobbe, however in the event where there's an active Wifi connection and no internet, the network call usually fails immediately without a 60 second timeout. My change to the file seems to have worked and I get an immediate failure. Are we saying it'll always wait for 60 seconds before giving up? That may not be ideal when we've already received `responseError`

**Comment by scobbe** [comment]
@guidedways: In general, when the NSURLSession library can unambiguously determine that there is no internet available (e.g. airplane mode), I think its behavior is to fail immediately. However, in the case where the network connection is so poor that no data is being sent or received, I think its behavior is to timeout (in this case, after 60 seconds). Does that clarify?
