### ISSUE TITLE
version 3.8.0 doesn't build properly for macOS via Carthage update

### ISSUE THREAD

**Issue by JBishopJr** [dropbox/dropbox-sdk-obj-c#213]
Carthage update for macOS appears to run to completion (macOS 10.13.4, Xcode 9.3), but the resulting framework is missing most of its header files (just 28 files in Headers directory for macOS, 1016 files for iOS).  Updating for iOS seems to be fine.

The fatal error that prevents use of the framework is the header DBSDKImportsGenerated.h (referenced in DBSDKImportsShared.h) is missing.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
This should be fixed in v3.8.1. Apologies for the bother!
