### ISSUE TITLE
Download Sharable link file in dropbox v2 version in iOS sdk

### ISSUE THREAD

**Issue by ViswanathB84** [dropbox/dropbox-sdk-obj-c#214]
Thank you very much for developing and supporting great library. 
I am trying download a file by using sharable link url [](https://www.dropbox.com/s/yoor9vle4cnccu8/KNSXE5TFOIQDEMBRGY5SAMRQGE3A%3D%3D%3D%3D?dl=0). Would you please help on this.
Thank you very much.

**Comment by greg-db** [comment]
To download file data from a shared link using this SDK, you should use one of the `getSharedLinkFile` methods, documented here:

https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGUserAuthRoutes.html#/c:objc(cs)DBSHARINGUserAuthRoutes(im)getSharedLinkFileUrl:overwrite:destination:
