### ISSUE TITLE
queryJobStatus does not seem to be calling the response block on the passed operation queue

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#221]
`- (void)queryJobStatus:(DBBatchUploadData *)uploadData asyncJobId:(NSString *)asyncJobId retryCount:(int)retryCount` in `DBCustomRoutes.m` does not seem to be using `uploadData.queue` for the response block for `uploadSessionFinishBatchCheck` and I feel the UI stutters at times when I'm batch uploading (possibly because it's calling the block on the main queue).

Am I wrong in assuming that this should use `uploadData.queue` instead?

**Comment by guidedways** [comment]
Similarly the `setResponseBlock` under `batchFinishUponCompletion` in the same file does not seem to be using the passed in `NSOperationQueue`. I supply the main `batchUpload` method with a  background queue and would like all responses to avoid using the main thread.

**Comment by guidedways** [comment]
I can verify that fixing the blocks with a ` queue:uploadData.queue` seems to have resolved the stuttering for me. Can someone verify this was unintentional?

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
This should be resolved by #241, now released in [v3.11.2](https://github.com/dropbox/dropbox-sdk-obj-c/releases/tag/3.11.2).
