### ISSUE TITLE
iOS App Extension UIApplication Not Available

### ISSUE THREAD

**Issue by mmcguill** [dropbox/dropbox-sdk-obj-c#234]
Hi,

I'm using 3.9.2 via Cocoapods. I'm trying to build an App Extension which means that UIApplication.sharedApplication is not available. This means then that DBClientsManager authorizeFromController is problematic as the first parameter takes a UIApplication.

A quick search reveals issue #113 which is closed and says that this has been fixed, but is unclear about how to use this library in an App Extension.

Am I missing something obvious here? 

Even the code in the README etc uses UIApplication.sharedApplication.

Should I be using a different method to launch authorization in an App Extension?

Thanks,
-Mark

**Comment by greg-db** [comment]
Hi Mark, if I recall correctly, for that reason, you can't start/process the app authorization flow (i.e., `authorizeFromController`) from within an app extension. (The app authorization flow needs to be able to redirect back to your app after the authorization; it wouldn't be able to bring you back to the extension itself. My understanding is that the other issue was about just using an already authorized client from within the app extension.) Sorry I don't have better news for you!

**Comment by mmcguill** [comment]
Ok, thanks for the quick response Greg.
