### ISSUE TITLE
Can't update iOS "The file “ObjectiveDropboxOfficial.framework” couldn’t be opened because there is no such file." 

### ISSUE THREAD

**Issue by bsabiston** [dropbox/dropbox-sdk-obj-c#235]
I am trying to update my app for the first time in a year.  I was using 3.0.11 because it was the last version to support iOS8, but now my app is crashing, and it seems to have something to do with Dropbox.  

But when I run carthage update --platform iOS, I get this:
Fetching dropbox-sdk-obj-c
*** Checking out dropbox-sdk-obj-c at "3.9.2"
*** xcodebuild output can be found in /var/folders/rd/w5sm142d1sn3m4zq2djv3wnc0000gp/T/carthage-xcodebuild.oyTrL3.log
*** Building scheme "ObjectiveDropboxOfficial iOS" in ObjectiveDropboxOfficial.xcodeproj
2018-11-17 13:03:58.862 xcodebuild[8522:656734] [MT] iPhoneSupport: 📱<DVTiOSDevice (0x7f823d89cfd0), XXXXX, iPhone, 12.0.1 (16A404), f6bd8b1aa1c6e180effbaff25d2d9c999cbb2807> missing architecture for device
Failed to write to /XXXXX/Carthage/Build/iOS/ObjectiveDropboxOfficial.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “ObjectiveDropboxOfficial.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/XXXX/Library/Developer/Xcode/DerivedData/ObjectiveDropboxOfficial-gglpwkwsxlwnfpftsoxrweyopqta/Build/Products/Release-iphoneos/ObjectiveDropboxOfficial.framework, NSUnderlyingError=0x7fd2cb128370 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} 

Anyone know what causes this?  I've tried to also request a specific older version, like 3.4.0, and got the same error.

**Comment by greg-db** [comment]
It looks like this is an issue with Carthage itself. There's a thread here with more information, including a potential workaround, as well as a link to the Carthage issue itself: https://www.dropboxforum.com/t5/API-Support-Feedback/Objective-C-build-of-3-4-0-failing-when-using-carthage/td-p/264461
