### ISSUE TITLE
directory not found for option '-F/...'

### ISSUE THREAD

**Issue by 4EEGroupRon** [dropbox/dropbox-sdk-obj-c#237]
Yes, I know, this has been discussed many time.  I've read and tried all solutions.  But to no avail.

I can create a new Xcode project, use CocoaPods to load the DB SDK with zero problems.  But, my existing project will simply not build.  I think I have checked every Build Setting mention in these forums.  Any help?

![screen shot 2018-12-22 at 8 17 39 am](https://user-images.githubusercontent.com/521715/50375922-8aae8c00-05c2-11e9-88a2-bd6dcc518635.png)

**Comment by greg-db** [comment]
I see that you also have a Dropbox support ticket with more information on this issue, so I'll close this in favor of that ticket to keep this in one place. We'll follow up with you there.
