### ISSUE TITLE
listout all specific files from all directoryes

### ISSUE THREAD

**Issue by BhaumikSurani** [dropbox/dropbox-sdk-obj-c#239]
I want get all video files from multiple directories in dropbox
but it only list specific directory files. 

```
[[self.client.filesRoutes listFolder:@""] setResponseBlock:^(DBFILESListFolderResult * _Nullable result, DBFILESListFolderError * _Nullable routeError, DBRequestError * _Nullable networkError) {
    if (result) {
        NSArray<DBFILESMetadata *> *entries = result.entries;
        NSString *cursor = result.cursor;
        BOOL hasMore = [result.hasMore boolValue];
        if (hasMore) {
            NSLog(@"Folder is large enough where we need to call `listFolderContinue:`");
        } else {
            NSLog(@"List folder complete.");
        }
    } else {
        NSLog(@"%@\n%@\n", routeError, networkError);
    }
}];
```

above code is properly work for specific directory 

    How to get all video files from multiple directories?
    can i search in dropbox by following code? if yes so how can i search for only video?
    because follow code not getting any result

```
DBFILEPROPERTIESPropertiesSearchMode *searchMode = [[DBFILEPROPERTIESPropertiesSearchMode alloc] initWithFieldName:@""];
DBFILEPROPERTIESPropertiesSearchQuery *searchQuery = [[DBFILEPROPERTIESPropertiesSearchQuery alloc] initWithQuery:@"" mode:searchMode];
[[self.client.filePropertiesRoutes propertiesSearch:@[searchQuery]] setResponseBlock:^(DBFILEPROPERTIESPropertiesSearchResult * _Nullable result, DBFILEPROPERTIESPropertiesSearchError * _Nullable routeError, DBRequestError * _Nullable networkError) {
    if(result) {
        NSLog(@"%@", result);
    } else {
        NSLog(@"");
    }
}];
```

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://stackoverflow.com/questions/54321649/dropbox-listout-all-specific-files-from-all-directoryes](https://stackoverflow.com/questions/54321649/dropbox-listout-all-specific-files-from-all-directoryes) ]

First, note that, as mentioned in the first `NSLog`, you'll need to implement calling [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESUserAuthRoutes.html#/c:objc(cs)DBFILESUserAuthRoutes(im)listFolderContinue:) in case there are more results to return. 

Second, if you want to list all files under a certain path at any depth (as opposed to just directly in the folder), you should set `recursive` to true when calling [`listFolder`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESUserAuthRoutes.html#/c:objc(cs)DBFILESUserAuthRoutes(im)listFolder:recursive:includeMediaInfo:includeDeleted:includeHasExplicitSharedMembers:includeMountedFolders:limit:sharedLink:includePropertyGroups:).

The Dropbox API doesn't offer a way to filter the results to a specific file type, e.g., video files, on the server, but I'll pass this along as a feature request. You can list everything and then filter the results based on file extension client-side though.

Finally, I see you're calling `propertiesSearch`, but that's only for searching "file properties", if any (which the app would have to have previously set itself). If you want to search files, e.g., by filename, you should instead use [the `search` method](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESUserAuthRoutes.html#/c:objc(cs)DBFILESUserAuthRoutes(im)search:query:).
