### ISSUE TITLE
addFileMember:uploadPath with quiet YES send email.

### ISSUE THREAD

**Issue by semionenko** [dropbox/dropbox-sdk-obj-c#240]
```
DBSHARINGMemberSelector *memberSelector = [[DBSHARINGMemberSelector alloc] initWithEmail:<email>];
                    
DBSHARINGAccessLevel *level = [[DBSHARINGAccessLevel alloc] initWithViewer];

DBUserClient *userClient = [DBClientsManager authorizedClient];

[userClient.sharingRoutes addFileMember:uploadPath members:@[memberSelector] customMessage:nil quiet:@(YES) accessLevel:level addMessageAsComment:@(NO)];
```

Still sends messages to the mail.

**Comment by greg-db** [comment]
[The `addFileMember` method's `quiet` parameter](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGUserAuthRoutes.html#/c:objc(cs)DBSHARINGUserAuthRoutes(im)addFileMember:members:customMessage:quiet:accessLevel:addMessageAsComment:) only offers control over "device notifications", not email:
> Whether added members should be notified via device notifications of their invitation.

I'll pass this along as a feature request for control over the email notification as well, but I can't make any promises as to if/when that would be added.

**Comment by greg-db** [comment]
For reference, the Dropbox API has been updated to suppress email notifications as well when using `quiet`.
