### ISSUE TITLE
Authentication doesn't work on several iOS simulators

### ISSUE THREAD

**Issue by adoucet52** [dropbox/dropbox-sdk-obj-c#250]
I was doing some testing on the Xcode simulators and found that the sdk behaves oddly with several of them. I do not have the official Dropbox app installed on the simulator. Upon clicking the authentication button, I am routed out of the app as expected. However, the UI of the drop box authenticator doesn't load, leaving me stuck with a white screen that only has an empty navigation bar.

I am using Xcode 11.1. I have found this problem with the following simulators:
iPad 6th Gen
iPad Air 2 (12.0)
iPad Air 2 (11.4)
iPad Pro (12.0)

The sdk is working with the following simulators:
iPad Air 3rd Gen
iPad Pro 3rd Gen

**Comment by greg-db** [comment]
I just gave this a try with Xcode 11.1 and an 'iPad Air 2 - 12.0' simulator and it worked as expected for me. I wasn't able to reproduce the issue you described. It presented the `SFSafariViewController` in the app as expected:

![Screenshot 2019-11-11 14 47 08](https://user-images.githubusercontent.com/8700917/68616179-84532800-0492-11ea-9a01-637ae236674a.png)

Technically, you're not routed out of the app. The `SFSafariViewController` is just presented. Aside from the Dropbox web page not rendering, is this different from what you're seeing?

Can you double check that you've [configured your plist and code for the authorization flow exactly as documented](https://github.com/dropbox/dropbox-sdk-obj-c#configure-your-project)?

If so, perhaps there's an issue with the state of those simulators on your machine? You may want to try the "Hardware > Erase All Content and Settings" option to reset them.

**Comment by adoucet52** [comment]
Found the actual issue causing this. There's a problem with SFSafariViewController where it fails to load if there's a popup showing.

Details can be found here: https://stackoverflow.com/questions/39662498/sfsafariviewcontroller-loading-blank-white-page
