### ISSUE TITLE
keyWindow Depreciated

### ISSUE THREAD

**Issue by datan3rd** [dropbox/dropbox-sdk-obj-c#252]
I am having trouble utilizing the SDK for an app in iOS13. 

I am getting a warning "'keyWindow' is deprecated: first deprecated in iOS 13.0 - Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes" but I am not sure that is causing the issue. 

When attempting to connect I am getting the message:
[15208:18854646] DBSDKReachability Flag Status: -R ------- networkStatusForFlags

and

[15208:18854646] Can't end BackgroundTask: no background task exists with identifier 1 (0x1), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

I am brought to the Dropbox app for authentication. Clicking allow brings me back to the app but no connection is made.

**Comment by greg-db** [comment]
Thanks for the report! It looks like there are a few pieces here, so I'll address each of them individually:

> a warning "'keyWindow' is deprecated

It sounds like this is referring to the `[UIApplication sharedApplication].keyWindow` usage in `topMostController` for calling `authorizeFromController`, as covered in [the "Begin the authorization flow" section of the documentation](https://github.com/dropbox/dropbox-sdk-obj-c#begin-the-authorization-flow). That's currently just a warning and so shouldn't be causing any functional issue. I'll ask the team to update the instructions with a non-deprecated alternative.

> I am getting the message ... DBSDKReachability Flag

This is just some network testing output, and also shouldn't be causing any issues. You can ignore it.

> Can't end BackgroundTask

I'm not seeing this error in my own testing, and we haven't received any other reports like this. Is this coming from Dropbox code? Please share the relevant code and steps to reproduce this for us to look into it.

> Clicking allow brings me back to the app but no connection is made.

Can you elaborate on what you mean when you say "no connection is made"? What code exactly isn't doing what you expect? This last step of the app authorization flow is handled by the `openURL` method. Make sure you've implemented the code as documented in [the "Handle redirect back into SDK" section of the documentation](https://github.com/dropbox/dropbox-sdk-obj-c#handle-redirect-back-into-sdk) to handle the redirect back to your app with the authorization result.

**Comment by datan3rd** [comment]
This is the code that is firing before the background task error:

```
- (void)connectToDropboxButton {
    NSLog(@"*Connecting to Dropbox");
        //Begin Authorization Flow
        [DBClientsManager authorizeFromController:[UIApplication sharedApplication]
                                       controller:[[self class] topMostController]
                                          openURL:^(NSURL *url) {
                                              [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:nil];
                                          }];
        [self DropboxStatus]; //This is to update the status of a button and display message same error if this is commented out
}

+ (UIViewController*)topMostController
{
    SettingsViewController * vc = [[SettingsViewController alloc]init];
    UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;

    while (topController.presentedViewController) {
        topController = topController.presentedViewController;
    }

    return topController;
}
```

However after trying to replicated I am now getting these errors:

[18507:19224116] DBSDKReachability Flag Status: -R ------- networkStatusForFlags

[18507:19224116] Can't end BackgroundTask: no background task exists with identifier 1 (0x1), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

[18507:19224444] Connection 1: received failure notification

[18507:19224444] [] nw_flow_add_write_request [C1.1 23.2.40.27:80 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests

[18507:19224444] [] nw_write_request_report [C1] Send failed with error "Socket is not connected"

The code is all nearly exactly as it is in GIT. I do have the redirect code in place. When I say no connection is made I am running this code to validate if there is a connection to dropbox before doing anything more and it is coming back as no connection:

  ```
  if ([DBClientsManager authorizedClient] != nil) {
        NSLog(@"*Dropbox is connected");
    } else {
        NSLog(@"*Dropbox is disconnected");
    }
```

**Comment by greg-db** [comment]
Thanks. I still can't reproduce the other output so it may be specific to some other code you have running somewhere in your app.

In any case, since the initial redirect to the official Dropbox app is working, it may not be related to this issue. I recommend adding some logging in the `openURL` method in the app delegate, as well as for the `handleRedirectURL` method result itself, to see what is happening there, as that's where the authorization result is used to  enable later use of `authorizedClient`.

For instance, the code in [the "Handle redirect back into SDK" section of the documentation](https://github.com/dropbox/dropbox-sdk-obj-c#handle-redirect-back-into-sdk) has three `NSLog` statements to show what the result was. Please try adding that if you don't already have it, as well as an earlier one at the beginning of `openURL` itself to see if it's getting called at all. Let me know what output you then get, if any, when redirected back to your app.

**Comment by datan3rd** [comment]
I do have the code almost exactly, just rewording the NSLog statements but they are not being called so I will add code to validate that any of it is getting called.

**Comment by datan3rd** [comment]
> Thanks. I still can't reproduce the other output so it may be specific to some other code you have running somewhere in your app.
> 
> In any case, since the initial redirect to the official Dropbox app is working, it may not be related to this issue. I recommend adding some logging in the `openURL` method in the app delegate, as well as for the `handleRedirectURL` method result itself, to see what is happening there, as that's where the authorization result is used to enable later use of `authorizedClient`.
> 
> For instance, the code in [the "Handle redirect back into SDK" section of the documentation](https://github.com/dropbox/dropbox-sdk-obj-c#handle-redirect-back-into-sdk) has three `NSLog` statements to show what the result was. Please try adding that if you don't already have it, as well as an earlier one at the beginning of `openURL` itself to see if it's getting called at all. Let me know what output you then get, if any, when redirected back to your app.


I added an NSLog to see if this gets called:
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {

And it does not.

**Comment by datan3rd** [comment]
For what its worth, I have made some progress. Adding the following code into the sceneDelegate allowed for things to actually run in the appDelegate. I am still getting a bunch of messages as I had before but at least it seems to functionally work for now.

```
- (void)scene:(UIScene *)scene openURLContexts:(NSSet<UIOpenURLContext *> *)URLContexts {
    NSLog(@"--Open URL");
    NSURL *url = [[URLContexts allObjects] firstObject].URL;
    //Handle redirect back in to SDK from Dropbox login
    DBOAuthResult *authResult = [DBClientsManager handleRedirectURL:url];
      if (authResult != nil) {
        if ([authResult isSuccess]) {
          NSLog(@"*Logged into Dropbox");
        } else if ([authResult isCancel]) {
          NSLog(@"*Authorization flow was manually canceled by user");
        } else if ([authResult isError]) {
          NSLog(@"Error: %@", authResult);
        }
      }
}
```

**Comment by greg-db** [comment]
Great, thanks for following up with the additional information. I'm glad to hear you got this working.

Starting with iOS 13, if your app uses scenes, UIKit will only send the events to the scene delegate, and not the app delegate like how the Dropbox SDK was originally written for. There's some documentation on this [here, under "Specifying the Scenes Your App Supports" > "Adopt Scene-Based Life-Cycle Semantics"](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/specifying_the_scenes_your_app_supports#3262270).

I'll ask the team to update our documentation with information on how to set up the authorization flow in this scenario.

**Comment by greg-db** [comment]
The documentation has been updated for this. Thanks!
