### ISSUE TITLE
File search gives unexpected results.

### ISSUE THREAD

**Issue by DimonDeveloper** [dropbox/dropbox-sdk-obj-c#253]
A search by name returns files whose names do not contain a search query.
Dropbox web version search results different from iOS SDK API Search.

Search query = @"adds"
Result some of the files:
1_ISO_eCommittee_Guide_for_Secretaries_and_Convenors_-_CS10.pdf
2_Circular_letter_-_ISO_eCommittee_system_-_ISOTC_Server_migrated.pdf

Why is that happens?

**Comment by greg-db** [comment]
@DimonDeveloper Thanks for the report! This is likely going to depend on the state of your account, and not the SDK itself. That being the case, please open this as an API ticket here so we can check on this for you: https://www.dropbox.com/developers/contact

Please include:
- the code you're running, including the parameter values (but don't include your access token)
- the output you're getting
- the affected account ID

Thanks in advance!
