### ISSUE TITLE
Upload/Download issue

### ISSUE THREAD

**Issue by pauldhanson** [dropbox/dropbox-sdk-obj-c#256]
Recently my program has stopped working with Dropbox.  I am using the V2 SDK and just the basic upload and download (to NSData) tasks.

In the case of the upload, it actually works and uploads the file to my Dropbox App folder, but returns a nil result (appearing as though it failed).  The file shows up.

In the case of download, the progress block shows that it downloads all the data (all bytes accounted for), but it too returns nil for the result, so I am unable to get at the data.

There is no routeError.  There is a network error as follows :
_tag	DBRequestErrorTag	DBRequestErrorClient
_nsError	NSError *	domain: @"dropbox.com" - code: 0	0x00000002836d14a0

Thanks!

**Comment by greg-db** [comment]
Thanks for the report. Can you also let us know:

- when this started happening
- the version number of the SDK you have installed
- the steps and code to reproduce this issue
- the full error/output you're getting, if there's any more than what you already shared

Thanks in advance!

**Comment by pauldhanson** [comment]
Not sure when this began, to be truthful.  Maybe with iOS 13, but I think after that.
3.11.1
My code is literally a duplicate of the tutorial/example code (with my app key used, of course).
No more error output other than what shared.  And like I said, it is DOING it, but then return nil Result.  If I don't use the Response/Progress block with the upload, it uploads fine.  If I use the response block, it still uploads, but I get a nil Result, so it appears as though it did not.  For the download, I get a nil Result, so even the the progress block showed the correct number of bytes being downloaded, I don't get the final NSData.

**Comment by greg-db** [comment]
Thanks! That's helpful. Please downgrade to v3.10.0 for now and let me know if that helps.

**Comment by pauldhanson** [comment]
That fixed it.  Thanks!

**Comment by greg-db** [comment]
Thanks for confirming. In that case, I believe we know what the issue is. We'll fix that in an upcoming release.

**Comment by hector-dropbox** [comment]
@pauldhanson Could you attempt this one more time with 3.11.2? Still trying to determine the root cause of some of these issues and would appreciate your help!

**Comment by pauldhanson** [comment]
Yep, that worked as well.  Thanks again.

Paul
