### ISSUE TITLE
Error in call "files/upload" [convertFormat in DBStoneSerializers returns wrong value]

### ISSUE THREAD

**Issue by rhcpfan** [dropbox/dropbox-sdk-obj-c#257]
A new issue was introduced in `3.11.0` (it's present in `3.11.1` also). I'm trying to upload a file through a `DBUploadTask` and I get a network error saying 

`Error in call to API function \"files/upload\": HTTP header \"Dropbox-API-Arg\": client_modified: time data \"Y-'m-'dT'H:'M:'SZ\" does not match format '%Y-%m-%dT%H:%M:%SZ'`

Here's how I create the `DBUploadTask`:
``` 
DBUploadTask *uploadTask = [client.filesRoutes uploadData:dropboxPath
                                                     mode:writeMode
                                               autorename:[NSNumber numberWithBool:!allowOverwrite]
                                           clientModified:[NSDate date]
                                                     mute:[NSNumber numberWithBool:YES]
                                           propertyGroups:nil
                                           strictConflict:[NSNumber numberWithBool:NO]
                                                inputData:data];
```
I pass the current date to the `clientModified` parameter. Later, in `DBFilesObject.m` this date is serialized to JSON by calling:

```
if (valueObj.clientModified) {
  jsonDict[@"client_modified"] = [DBNSDateSerializer serialize:valueObj.clientModified dateFormat:@"%Y-%m-%dT%H:%M:%SZ"];
}
```

Notice the date format. This one is later converted to a format that obj-c supports in `DBStoneSerializers`, in `+ (NSString *)convertFormat:(NSString *)format;`

Instead of returning `yyyy-MM-dd'T'HH:mm:ssZ` like in `3.10.0`, now it fails to convert to the correct format.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by hector-dropbox** [comment]
@rhcpfan I just wrote this code to remove the warnings that were being emitted by the compiler in that code. I'll be looking into fixing this issue today. Thank you for reporting it!

**Comment by hector-dropbox** [comment]
@rhcpfan Could you check the latest 3.11.2 release and test this issue for me one more time, please?

**Comment by rhcpfan** [comment]
@hector-dropbox I've just tested using `3.11.2` and it works just fine. Thank you for fixing this so quickly!
