### ISSUE TITLE
How to unlink the dropbox account?

### ISSUE THREAD

**Issue by amoshsueh** [dropbox/dropbox-sdk-obj-c#26]

**Comment by greg-db** [comment]
@amoshsueh Depending on exactly what functionality you're looking for, you can use one or more of:
- [`DropboxClientsManager.unlinkClients`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DropboxClientsManager.html#/c:objc(cs)DropboxClientsManager(cm)unlinkClients)
- [`DBOAuthManager.clearStoredAccessToken`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBOAuthManager.html#/c:objc(cs)DBOAuthManager(im)clearStoredAccessToken:)
- [`DBOAuthManager.clearStoredAccessTokens`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBOAuthManager.html#/c:objc(cs)DBOAuthManager(im)clearStoredAccessTokens)
- [`DBAUTHRoutes.tokenRevoke`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBAUTHRoutes.html#/c:objc(cs)DBAUTHRoutes(im)tokenRevoke)

**Comment by amoshsueh** [comment]
@greg-db Appreciate your help!
