### ISSUE TITLE
Redeclaration of 'kDBSDKVersion' with a different type: 'NSString *const __strong' vs 'NSString *__strong'

### ISSUE THREAD

**Issue by wasimsafdar** [dropbox/dropbox-sdk-obj-c#269]
I started updating my app and getting this issue in 'DBSDKConstants.h' file. I understood this issue and trying to resolve it but I also think, it is the latest bug in Dropbox SDK that they need to resolve. For help check this.

https://stackoverflow.com/questions/3196491/objective-c-const-nsstring-vs-nsstring-const

I just removed const modifier. i.e. NSString *kDBSDKVersion; NSString *kDBSDKVersion = @"4.0.0";

If anybody has a better solution, please post. Thanks.

**Comment by greg-db** [comment]
Thanks for the report! I'm not getting this same message though. Can you let me know:

- the steps to produce this error
- which version of Xcode you're using
- what, if any, extra build settings, e.g., to enable extra warnings, you have enabled

**Comment by wasimsafdar** [comment]
I am using XCode 11.4.1. There are no extra build settings.

**Comment by greg-db** [comment]
Thanks for following up. I still can't seem to reproduce this output though, even with Xcode 11.4.1 and Dropbox SDK v4.0.0 in particular.

Can you let me know how you're installing the SDK?

Also, can you check you're not accidentally declaring `kDBSDKVersion` in your own code somewhere?

**Comment by wasimsafdar** [comment]
I am using Cocoapods to install the SDK. i.e. pod 'ObjectiveDropboxOfficial'. I am not redeclaring kDBSDKVersion in my own code. It was redeclared in SDK in 'DBSDKConstants.h' and 'DBSDKConstants.m' files with 'NSString *const __strong' and with 'NSString *__strong'. I also thought that why it is redeclared and producing the error. That's why I removed the const modifier to make it work.

**Comment by greg-db** [comment]
Thanks. I'm also using CocoaPods, so I'm still not sure why I can't reproduce the same thing you're seeing. 

In any case, the latest release is v5.0.3 so I do recommend updating to that anyway. 

If you still see the issue with that (unmodified v5.0.3), can you share a screenshot for reference?

**Comment by wasimsafdar** [comment]
In my case, it was v4.0.0. If I update my app with the new version and still see the issue, I will update you. Thank you very much for looking into it.

**Comment by YogendraPatel** [comment]
I also face same issue. have you find any solution?

**Comment by YogendraPatel** [comment]
![Screenshot 2020-09-30 at 11 56 59 AM](https://user-images.githubusercontent.com/20812615/94650335-1d419a80-0314-11eb-8e06-4e3be6f95b55.png)
 
Still get this error in v5.0.3

**Comment by greg-db** [comment]
@YogendraPatel  From your screenshot, I see that you're looking at the file "DBSession.h", which is actually part of an old Dropbox SDK for the now retired Dropbox API v1. You should instead only install the current [Dropbox Objective-C SDK](https://github.com/dropbox/dropbox-sdk-obj-c), which is for API v2, and remove the old SDK. They both define `kDBSDKVersion` so having both installed could cause this issue.
