### ISSUE TITLE
getMetadata does not work with trailing slash

### ISSUE THREAD

**Issue by phil1995** [dropbox/dropbox-sdk-obj-c#277]
When I call the function `getMetadata("/Folder/")` I get a `routeError` with `malformed_path`. If I call `getMetadata("/Folder")` I get the metadata of the folder as expected.
 In the Dropbox API v2 HTTP Documentation the following pattern is allowed for the path: 
`(/(.|[\r\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)`. 
Therefore I would expect that both calls behave equivalent. The item located at the path described above is of course a folder.

**Comment by greg-db** [comment]
Thanks for the report, but this is the expected behavior. This is noted in [the Dropbox API documentation](https://www.dropbox.com/developers/documentation/http/documentation#path-formats):
> Paths may not end with a slash or whitespace.
