### ISSUE TITLE
Problem to compile the sdk

### ISSUE THREAD

**Issue by RWarnecke** [dropbox/dropbox-sdk-obj-c#278]
Hello,

I had installed the actually version 5.0.3 from this sdk over cocoapods into my app. Under Xcode 12 and iOS 14 i get these error messages:

Command CompileC failed with a nonzero exit code --> In the Framework
unexpected service error: The Xcode build system has crashed. Please close and reopen your workspace. --> In the workspace.

Can anybody help me ?

**Comment by greg-db** [comment]
This issue doesn't reproduce for me with v5.0.3 of the Dropbox Objective-C SDK with Xcode 12 and iOS 14. 

Can you share the full error/output? This portion doesn't seem to indicate what specifically failed.

Also, it asks you to close and reopen the workspace. Please try doing so if you haven't already and let me know if that does or doesn't help.

**Comment by RWarnecke** [comment]
To reopen the workspace doesn't help. In the attached file are my output from my last build where I get these errors.

[Build target ObjectiveDropboxOfficial_2020-09-22T16-30-57.txt](https://github.com/dropbox/dropbox-sdk-obj-c/files/5263032/Build.target.ObjectiveDropboxOfficial_2020-09-22T16-30-57.txt)

**Comment by RWarnecke** [comment]
I found a solution. There is a problem with Cocoapod Version 1.9.x and Xcode 12. If you install the rc1 from Cocoapod 1.10 the sdk compiles very fine. More infos under this link : https://stackoverflow.com/a/63648164

**Comment by greg-db** [comment]
Great, I'm glad to hear you already sorted this out. Thanks for sharing the solution!
