### ISSUE TITLE
'DBFILESUploadSessionStartError.h' file not found

### ISSUE THREAD

**Issue by baksogen** [dropbox/dropbox-sdk-obj-c#281]
Xcode 12.2 
Can't build Obj-c SDK

/DropboxOfficial/Shared/Generated/Routes/DBFILESUserAuthRoutes.m:170:9: fatal error: 'DBFILESUploadSessionStartError.h' file not found
#import "DBFILESUploadSessionStartError.h"

**Comment by greg-db** [comment]
Thanks for the report. We'll look into it.

Also, are you using Carthage to build the SDK? If so, can you confirm which version of it you have installed?

**Comment by greg-db** [comment]
This should be fixed in the latest version. Please refer to [the updated documentation](https://github.com/dropbox/dropbox-sdk-obj-c#carthage) for more information.
