### ISSUE TITLE
Carthage fails to build 5.0.4

### ISSUE THREAD

**Issue by chrisvanbuskirk** [dropbox/dropbox-sdk-obj-c#282]
I'm trying to upgrade, and it fails.  I have Catalina's .7 and Xcode 12.2

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/administrator/github/corkulous/Carthage/Checkouts/dropbox-sdk-obj-c/Source/ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.xcodeproj -scheme ObjectiveDropboxOfficial\ iOS -configuration Release -derivedDataPath /Users/administrator/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/dropbox-sdk-obj-c/5.0.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/95/mrhgrkv92y1g9pl4hxjvhcp00000gn/T/dropbox-sdk-obj-c SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/administrator/github/corkulous/Carthage/Checkouts/dropbox-sdk-obj-c)

[carthage-xcodebuild.LpuHC5.log](https://github.com/dropbox/dropbox-sdk-obj-c/files/5579681/carthage-xcodebuild.LpuHC5.log)

**Comment by chrisvanbuskirk** [comment]
error: Build input file cannot be found: '/Users/administrator/github/corkulous/Carthage/Checkouts/dropbox-sdk-obj-c/Source/ObjectiveDropboxOfficial/Shared/Generated/Routes/RouteObjects/DBCLOUDDOCSRouteObjects.m' (in target 'ObjectiveDropboxOfficial iOS' from project 'ObjectiveDropboxOfficial') 

What I spotted in the log file.

**Comment by greg-db** [comment]
Thanks for the report. We'll look into it.

Also, for reference, can you confirm which version of Carthage you have installed?

**Comment by chrisvanbuskirk** [comment]
@greg-db  0.36.0

**Comment by greg-db** [comment]
Thanks!

**Comment by greg-db** [comment]
This should be fixed in the latest version. Please refer to [the updated documentation](https://github.com/dropbox/dropbox-sdk-obj-c#carthage) for more information.
