### ISSUE TITLE
Layout issue in a authorization dialog for app permissions with iPad

### ISSUE THREAD

**Issue by androidports** [dropbox/dropbox-sdk-obj-c#284]
In iPad, when my app launch the Dropbox app for authenticating app permissions via this SDK, the dialog layout is broken as below screenshot.

![Screen Shot 2020-12-01 at 10 09 26](https://user-images.githubusercontent.com/6258322/100684340-7b930400-33bd-11eb-8b52-cffb4bf16ec4.png)

Device: iPad (6-gen)
iOS: 14.2
Dropbox app: 216.2
ObjectiveDropboxOfficial: 5.0.4

**Comment by greg-db** [comment]
Thanks for the report! This is a bug on our side. We're looking into it. I'll follow up here once I have an update on that. No action is required on your part.

**Comment by greg-db** [comment]
This is fixed in the latest version of the official Dropbox iOS app, v232.2. Thanks again.
