### ISSUE TITLE
Carthage fails to build 5.0.5

### ISSUE THREAD

**Issue by JBishopJr** [dropbox/dropbox-sdk-obj-c#288]
Xcode 12.3, macOS 11.1
Following documented instructions for Carthage iOS update from 5.0.3, version 5.0.5 downloads and builds with an error:

.../Carthage/Checkouts/dropbox-sdk-obj-c/Source/ObjectiveDropboxOfficial/Shared/Generated/ApiObjects/DBTeamPoliciesObjects.m:184:9:  fatal error:  'DBTEAMPOLICIESComputerBackupPolicyState.h'  file not found
#import "DBTEAMPOLICIESComputerBackupPolicyState.h"
•
•
•
The following build commands failed:
	CompileC /Users/jb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.3_12C33/dropbox-sdk-obj-c/5.0.5/Build/Intermediates.noindex/ArchiveIntermediates/ObjectiveDropboxOfficial\ iOS/IntermediateBuildFilesPath/ObjectiveDropboxOfficial.build/Release-iphoneos/ObjectiveDropboxOfficial\ iOS.build/Objects-normal/armv7/DBTeamPoliciesObjects.o /Users/jb/Development/Scoring\ Machine/Carthage/Checkouts/dropbox-sdk-obj-c/Source/ObjectiveDropboxOfficial/Shared/Generated/ApiObjects/TeamPolicies/DBTeamPoliciesObjects.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

How do I proceed?

**Comment by greg-db** [comment]
Thanks, we'll look into it. Can you also let me know what version Carthage you have installed?

**Comment by JBishopJr** [comment]
0.36.0

> On Dec 29, 2020, at 8:03 AM, Greg <notifications@github.com> wrote:
> 
> 
> Thanks, we'll look into it. Can you also let me know what version Carthage you have installed?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------------------------------------------------------------------
John Bishop
Mulligan Software
<mailto:jb@mulligansoftware.com>
<https://www.mulligansoftware.com>
Twitter:  MulliganGolf

**Comment by greg-db** [comment]
Thanks!

**Comment by kkiplinger** [comment]
I can confirm that dropbox-sdk-obj-c v5.0.5 and v5.0.4 fail to build with the new Carthage 0.37.0 release. However, v5.0.3 does still build properly with Carthage 0.37.0.

**Comment by greg-db** [comment]
@kkiplinger Thanks for the information!

**Comment by greg-db** [comment]
This should be fixed in the latest version. Please refer to [the updated documentation](https://github.com/dropbox/dropbox-sdk-obj-c#carthage) for more information.
