### ISSUE TITLE
`client_modified` does not match format error.

### ISSUE THREAD

**Issue by olliwang** [dropbox/dropbox-sdk-obj-c#29]
Hi, I got an error message when trying to upload a file. It seems something is wrong when converting the `NSDate` object.

    Error in call to API function "files/upload": HTTP header "Dropbox-API-Arg": client_modified: time data '2016-09-08T8:38:19 PMZ' does not match format '%Y-%m-%dT%HM:%SZ'.

**Comment by greg-db** [comment]
@olliwang Can you share the code you're using to reproduce this? Thanks in advance!

**Comment by olliwang** [comment]
Thanks for reply. Here it is.

    NSDate* fileModificationTime = [NSDate date];
    NSDictionary* fileAttributes = [fileManager
      attributesOfItemAtPath:localFileURL.path error:nil];
    if (fileAttributes != nil) {
    fileModificationTime = [fileAttributes fileModificationDate];
    }

    DBUploadTask* task = [client.filesRoutes
      uploadUrl:targetURL
      mode:[[DBFILESWriteMode alloc] initWithOverwrite]
      autorename:[NSNumber numberWithBool:YES]
      clientModified:fileModificationTime
      mute:[NSNumber numberWithBool:YES]
      inputUrl:localFileURL];
    [task response:^(DBFILESFileMetadata *metadata,
                   DBFILESUploadError *routeError,
                   DBError *error) {
    }];

I was wondering if it has something to do with the locale settings.
![14274449_1180967725259264_2048627336_o](https://cloud.githubusercontent.com/assets/76374/18396680/85bb2e3a-76f7-11e6-9932-4ad9cd4003b3.jpg)

**Comment by greg-db** [comment]
Thanks! We'll look into it.

**Comment by scobbe** [comment]
@olliwang: Thanks for the heads up. You were correct, the issue came from the localization (using a 12 hour clock in a 24 hour default region). 41e099e should fix the issue.

Let me know if the issue persists or if anything else comes up.
