### ISSUE TITLE
Delete multiple files/folders at once

### ISSUE THREAD

**Issue by rodionovd** [dropbox/dropbox-sdk-obj-c#31]
There's a method in Dropbox API called [`/delete_batch`](https://www.dropbox.com/developers/documentation/http/documentation#files-delete_batch) which is pretty useful for deleting multiple items with just one network request. It would be nice to see this API wrapped into the SDK.

I'm aware that this method alone is not enough and you also need to call [`/delete_batch/check`](https://www.dropbox.com/developers/documentation/http/documentation#files-delete_batch-check) in order to figure out the current status of a deletion job.

Thank you!

**Comment by greg-db** [comment]
Thanks for the request! That endpoint is new and will be included in this SDK the next time it is regenerated.

**Comment by rodionovd** [comment]
Awesome, thanks!

**Comment by scobbe** [comment]
@rodionovd: Ok, eee9f4f updated the SDK (v1.1.0) to include the `/delete_batch` endpoint, among other things. Let us know if you run into any issues using it!
