### ISSUE TITLE
Short-lived tokens not refreshing when app is in background?

### ISSUE THREAD

**Issue by junjie** [dropbox/dropbox-sdk-obj-c#316]
> > Should the legacy authorization flow (which is appearing in the code above) keep working even after long-lived tokens are deprecated?
> 
> Yes, the legacy flow should continue working once long-lived access tokens are no longer being returned, but that means that it will only receive short-lived access tokens. When that occurs, users still on the legacy flow will only be able to use the connection for up to four hours before the access token expires and they need to re-connect it.
> 
> > Or, should a new SDK method be introduced soon? (Which presumably use refresh tokens to keep the current behavior)
> 
> The `authorizeFromControllerV2` method is the new method that you should use now. It will automatically take care of short-lived access tokens and refresh tokens for you, including automatically performing the refresh for you so that the app will maintain long-term access (i.e., longer than four hours).

_Originally posted by @greg-db in https://github.com/dropbox/dropbox-sdk-obj-c/issues/287#issuecomment-749612726_

I started using the 6.x SDK, along with the `authorizeFromControllerV2` method that according to the response from @greg-db quoted above, should take care of doing the refreshing so that my app maintains long-term access.

However I'm finding that after a period of time, when my app receives a background push to fetch data from Dropbox in the background, I'm getting the following error when calling `-[DBUserClient.filesRoutes getMetadata:]`:

`The operation couldn’t be completed. (com.dropbox.dropbox_sdk_obj_c.oauth.error error 11.)`

I looked through the SDK code and error 11 seems to be `DBAuthUnknown`, which was documented as `Some other error (outside of the OAuth2 specification)`.

Is there something else I need to be doing to ensure that my app can make Dropbox API calls even when it is in a background state?

**Comment by greg-db** [comment]
First, just to clarify, your title says "Long-live tokens not refreshing", however long-lived access tokens don't need to be refreshed; only short-lived access tokens. Did you mean to say "short-lived"?

Anyway, I'm not sure off hand what might cause this, so we'll need to look into it. Can you share the specific steps and code snippets to reproduce this? (Or if possible, a small sample project would be very helpful.) Thanks in advance!

**Comment by junjie** [comment]
Hi @greg-db, you're right! I meant to say short-lived tokens are not refreshing (but that's only my suspicion, more info below).

Indeed having a sample project would come in handy for you to diagnose the issue. My project is rather huge and complex by now, so extracting the relevant code, including setting up the background push, and ensuring that the problem reproduces on the sample code would be time-consuming and challenging. Of course, if it comes to that, I’d have no choice but to attempt that.

For now I’m hoping you can shed some light that can point me in the right direction to troubleshoot the problem. If there’s any logging I can turn on in the Dropbox SDK that can help potentially diagnose the issue, I’d be able to do that too. 

My project has previously been using the 3.9.2 SDK for years, and minimal changes were made to adopt the 6.0.0 SDK. The most significant being the adoption of scopes and the `authorizeFromControllerV2` method to handle the short-lived tokens and refreshing.

So from this:

```
	[DBClientsManager authorizeFromController:[UIApplication sharedApplication] controller:controller openURL:^(NSURL * _Nonnull url) {
		[[UIApplication sharedApplication] openURL:url];
	}];
```

to this

```
    DBScopeRequest *scopeRequest = [[DBScopeRequest alloc] initWithScopeType:DBScopeTypeUser scopes:@[@"files.metadata.read", @"files.content.write", @"files.content.read"] includeGrantedScopes:NO];
    [DBClientsManager authorizeFromControllerV2:[UIApplication sharedApplication] controller:controller loadingStatusDelegate:nil openURL:^(NSURL * _Nonnull url) {
        [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:nil];
    } scopeRequest:scopeRequest];
```

So the error message from Dropbox SDK happens when my app is in a background state, but woken up in the background in response to a [background push notification](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app). The first call I make in that scenario is a `getMetadata` call.

There have been no issues with how my app worked with the 3.9.2 SDK when woken up in the background with a background push to communicate with Dropbox.

With the 6.0.0 SDK, it’d fail to do so after some time has past. However once I bring my app to the foreground, the API calls to Dropbox would work normally again. I have not narrowed down the time frame it takes for the problem to happen, but I suspect it’s in the range of hours based on my available logs. 

I believe there are two major changes between the 3.9.2 and 6.0.0 SDK: one of them was the adoption of short-lived tokens, and the other being making use of NSURLSession to make calls in the background.

I created the issue with the suspicion that it could be the short-lived token not refreshing properly, based on how the error message was named (`com.dropbox.dropbox_sdk_obj_c.oauth.error`). But of course I could be completely off-tangent. The other issue I’m suspecting would be the use of a background NSURLSession, which I don't believe was used back in 3.9.2?

**Comment by greg-db** [comment]
Thanks for the additional information. We'll look into it.

**Comment by junjie** [comment]
Hi @greg-db, after running it for a few more days, I don't see the error any more. The app seems to be able to call the Dropbox API even in the background now. Perhaps there was some strange bug at that point in time when I encountered the problem. Let's close this for now? Sorry for taking up your time!

**Comment by greg-db** [comment]
No problem, thanks for the update! We were trying reproduce this but were also unable to do so. Let us know if it recurs though.
