### ISSUE TITLE
Path expression for the root folder

### ISSUE THREAD

**Issue by kfujino7** [dropbox/dropbox-sdk-obj-c#32]
When trying to list the contents of the root folder, it has to be specified @“” rather than @“/“. If specified @“”, following error occurs
_[client.filesRoutes listFolder:@"/"]_
Error loading metadata: DropboxBadInputError[{
    ErrorContent = "Error in call to API function \"files/list_folder\": request body: path: Specify the root folder as an empty string rather than as \"/\".";
    StatusCode = 400;
}];

Thought the SDK doesn’t like the leading slash,,, However, to display the contents of folder named ‘test’ under root, if I specify the folder name as ’test’, following error occurs, 
_[client.filesRoutes listFolder:@“test”]_

DropboxBadInputError[{
    ErrorContent = "Error in call to API function \"files/list_folder\": request body: path: ‘test’ did not match pattern '(/(.|[\\r\\n])*)?|(ns:[0-9]+(/.*)?)'";
    StatusCode = 400;
}];

So, this case I have to specify the folder as ‘/test’. this is confusing but is it working as expected?
**In V1, I needed to specify ‘/‘ for the root folder.**

Env : Version 1.0.8, iOS, cocoapods

**Comment by greg-db** [comment]
This is expected. With Dropbox API v2, the root is expressed as empty string `""`, and non-root paths are expressed with a leading slash, e.g. `"/test.txt"`.
