### ISSUE TITLE
Migration to Scoped Permissions - Production App using old 'authorizeFromController'

### ISSUE THREAD

**Issue by strongbox-mark** [dropbox/dropbox-sdk-obj-c#320]
Hello, I would like to migrate to App Permissions and App Tokens as discussed [here](https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens). However I am a little worried about hitting the 'Migrate' button on the 'Permissions' tab for my App in the developer console.

I have a large number of existing users using my App and I need to make sure they are unaffected while I test and make code changes for the migration. In the document linked above it says:

_"Click Migrate then Confirm. Note that this change does not impact existing tokens"_

However, what about users who have not used my App before? I get new users every day. They come along and want to connect their Dropbox's to my App, and they will not have an existing token. Also, consider my existing users who's tokens expire during the next few days and weeks. My question really boils down to:

If I hit the 'Migrate' button will my existing code succeed in creating a regular long lived access token and allow users to link successfully? 

NB: My existing code calls the old `authorizeFromController` method.

**Comment by greg-db** [comment]
Yes, this scopes migration is also backwards compatible for new authorizations using old code (e.g., `authorizeFromController`). Once an app is migrated to scopes, any authorizations that don't explicitly pass in scopes, such as `authorizeFromController`, will just automatically get whatever scopes you configure for the app on the App Console. So, you just need to make sure you enable all of the scopes needed for the functionality used by your app.

You'll want to keep the "Access token expiration" setting set to "No expiration" though, to keep the default token type to be long-lived for those users still on the old code.
