### ISSUE TITLE
ObjectiveDropboxOfficial_macOS.h doesn't exist

### ISSUE THREAD

**Issue by mathieugarcia** [dropbox/dropbox-sdk-obj-c#34]
Hello !

I'm using the SDK for both iOS & macOS. Everything is fine for my iOS target but, on macOS, the ```ObjectiveDropboxOfficial_macOS.h``` file is nowhere to be found. I checked every directories and it's not there. The ObjectiveDropboxOfficial pod is at version 1.0.8. Some verbose from ```pod update```:

```
  - Installing target `ObjectiveDropboxOfficial-OSX` OS X 10.10
  - Installing target `ObjectiveDropboxOfficial-iOS` iOS 8.0
```

I could include ```DropboxSDKImportsDesktop.h``` manually but that's not the point.
I'm using Xcode 8, cocoapods 1.0.1, OSX 10.11.6. Deployment target set to 10.11.

My Podfile is fine (got the macOS & iOS pods referenced), not sure what is going wrong.
Is this a known issue ?

Thank you !
Mathieu.

**Comment by scobbe** [comment]
Really sorry for all of the confusion around import statements. The SDK finally has a consistent import policy that should work regardless of platform. Please pull the latest version of the SDK (v1.0.9) and use the following import statements:

`#import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h>`

Please let me know if this resolves your issue. Thanks for your patience.

**Comment by mathieugarcia** [comment]
Just updated to v1.0.9 and it indeed fixed the issue.
Thanks for providing a quick solution to this problem.

Mathieu.

**Comment by mathieugarcia** [comment]
Hi again,

Now my iOS target tries to include the OSX header.
I'm importing the header as follow: ```#import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h```.

Mathieu.

**Comment by scobbe** [comment]
@mathieugarcia: Thanks for reaching out again. Sorry you're running into difficulties. How did you import the SDK? via CocoaPods, Carthage or as a subproject?

Can you confirm for me that the target membership for each of the `ObjectiveDropboxOfficial.h` files is correct for each target?

For example, the `ObjectiveDropboxOfficial.h` for macOS has membership only to the correct ObjectiveDropbox macOS target:

<img width="1403" alt="macos target" src="https://cloud.githubusercontent.com/assets/17483354/18757332/5739dd62-80a8-11e6-8ed0-0d55791ebe65.png">

**Comment by mathieugarcia** [comment]
Hey @scobbe thanks for the quick reply.

I'm using CocoaPods, I can see two ObjectiveDropboxOfficial.h files in the "Pod > ObjectiveDropboxOfficial" group:

![screen shot 2016-09-22 at 19 25 43](https://cloud.githubusercontent.com/assets/416792/18758944/71503a00-80fa-11e6-8b46-da45b6a30f76.png)

- The first one is located here: ```Source/ObjectiveDropboxOfficial/ObjectiveDropboxOfficial_iOS/ObjectiveDropboxOfficial.h``` and is a public member of the ```ObjectDropboxOfficial-iOS``` target

![screen shot 2016-09-22 at 19 26 40](https://cloud.githubusercontent.com/assets/416792/18758970/8901c664-80fa-11e6-82cc-ab286636dd66.png)

- The second one is located here:
```Source/ObjectiveDropboxOfficial/ObjectiveDropboxOfficial_macOS/ObjectiveDropboxOfficial.h``` and is a public member of the ```ObjectDropboxOfficial-OSX``` target.

![screen shot 2016-09-22 at 19 26 34](https://cloud.githubusercontent.com/assets/416792/18758975/92e209c8-80fa-11e6-868e-9d9d434af8c5.png)

Hope this helps,
Mathieu.

**Comment by mathieugarcia** [comment]
Some more information:

In the ```Pods/Headers/Public/ObjectiveDropboxOfficial``` directory I can see this symlink:
```ObjectiveDropboxOfficial.h -> ../../../ObjectiveDropboxOfficial/Source/ObjectiveDropboxOfficial/ObjectiveDropboxOfficial_macOS/ObjectiveDropboxOfficial.h``` 

I thought that could help you as well.

**Comment by scobbe** [comment]
@mathieugarcia: Thanks for bringing this issue up and thanks for your patience. It should be resolved now.

Try pulling from CocoaPods again (same version v1.0.9), but it should work now.

Make sure to clear your local CocoaPods cache before pulling:

`rm -rf "${HOME}/Library/Caches/CocoaPods"`

And make sure to clear other CocoaPods data:

`rm -rf MyProject.xcworkspace`
`rm -rf Pods`
`rm Podfile.lock`

Let me know if it works now!

**Comment by mathieugarcia** [comment]
Hello @scobbe !

Followed the steps and both iOS & macOS targets work perfectly.

Thanks a lot !
Cheers,
Mathieu.
