### ISSUE TITLE
DropboxAuthError with error content "expired access token"

### ISSUE THREAD

**Issue by rajubd49** [dropbox/dropbox-sdk-obj-c#351]
Our iOS app is basically implemented using Objective C and we use ObjectiveDropboxOfficial to login to dropbox. The app was working fine for a long time, but for the past few days, we are facing an access token expiration issue. If we log in today and try to fetch files the next day, we are getting this error and we need to relink or login again for the dropbox to work.

Error log:

DropboxAuthError[{
    ErrorContent = "expired_access_token/";
    RequestId = 24a031d6ab81429eb0f714646cbf9f38;
    StatusCode = 401;
    StructuredAuthError = "{\n    \".tag\" = other;\n}";
    UserMessage = nil;
}];

What is the solution or best way to resolve this issue?

**Comment by tidrop** [comment]
@rajubd49 It seems like you're experiencing short lived tokens expiring. The Obj-C SDK handles automatic refreshing of expired tokens. Please take a look at the example [here](https://github.com/dropbox/dropbox-sdk-obj-c#begin-the-authorization-flow) for how this is implemented.

**Comment by rajubd49** [comment]
@tidrop Thank you for your response, we've solved the issue.

**Comment by tienjp68** [comment]
@rajubd49 
I am also getting this error
Can you show the solved code?
Thank you very much!

**Comment by rajubd49** [comment]
@tienjp68 My problem was, in podfile we did specified version 3.x.x which was not working anymore for short lived tokens expiring issue. So we've updated ObjectiveDropboxOfficial to it's latest version which is I believe 6.2.3 and it resolves our problem.

**Comment by tienjp68** [comment]
@rajubd49 
Thank you very much!

**Comment by tienjp68** [comment]
@rajubd49 
I have reinstalled pod but func "AuthozeFromControllerV2" is not in DBClientsManager+MobileAuth-iOS file,
do you know why?

target 'Kodomomenkyo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Kodomomenkyo
  pod 'ObjectiveDropboxOfficial'
end

target 'Kodomomenkyo_dev' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Kodomomenkyo_dev
  pod 'ObjectiveDropboxOfficial'
end

**Comment by greg-db** [comment]
@tienjp68 Note that you have a typo in your comment; make sure you don't also have the same typo in your code. The method is named "authorizeFromControllerV2" not "AuthozeFromControllerV2". The `authorizeFromControllerV2` method is defined [here in DBClientsManager+MobileAuth-iOS.m](https://github.com/dropbox/dropbox-sdk-obj-c/blob/696c3d49e827c0f979c04d0b850cb3ac0c3756cc/Source/ObjectiveDropboxOfficial/Platform/ObjectiveDropboxOfficial_iOS/DBClientsManager%2BMobileAuth-iOS.m#L29).

Make sure you actually have a recent version of the SDK installed, ideally the latest version, which is currently v6.3.2. It looks like you're [using CocoaPods](https://github.com/dropbox/dropbox-sdk-obj-c#cocoapods), so you can use `pod update` to update. Check the output to make sure that runs successfully and to check that the latest version is installed.

Then, you can [set up the authorization flow as documented](https://github.com/dropbox/dropbox-sdk-obj-c#begin-the-authorization-flow).

If something still isn't working as expected, feel free to [open a new issue](https://github.com/dropbox/dropbox-sdk-obj-c/issues/new) with the details of the issue.

**Comment by tienjp68** [comment]
@greg-db 
Cause is missing: 
platform :ios, '9.0'
Thank you very much!
