### ISSUE TITLE
batchUploadFiles not returning since 6.3.0

### ISSUE THREAD

**Issue by michaelkircher** [dropbox/dropbox-sdk-obj-c#353]
Since version 6.3.0 all calls to batchUploadFiles are not calling the completion handler. Switching back to 6.2.3 makes it work again.

**Comment by greg-db** [comment]
Thanks for the report! I'll ask the team to look into it.

**Comment by greg-db** [comment]
This is fixed in v6.3.2. Thanks again!

**Comment by michaelkircher** [comment]
Works, thanks for the fast fix.
