### ISSUE TITLE
Warning while validating build with pod ObjectiveDropboxOfficial (version 7.0.0)

### ISSUE THREAD

**Issue by iOSCuriosity** [dropbox/dropbox-sdk-obj-c#358]
`App Store Connect Operation Error`
`The app references non-public selectors in Payload/PTM.app/Frameworks/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial: showLoading`

iOS Deployment Target : 13.0

**Comment by greg-db** [comment]
This appears to be a false positive in Apple's tooling. There's [a discussion about this here](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Error-when-uploading-binary-on-iOS-with-Xcode-14-and-using/td-p/622696). You may need to reach out to Apple regarding that.
