### ISSUE TITLE
Non public sectors - (void)showLoading

### ISSUE THREAD

**Issue by aronnelson** [dropbox/dropbox-sdk-obj-c#359]
How can I fix this error in Xcode 14:

The app references non-public selectors in Payload/xxxxxx.app/Frameworks/
ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial:showLoading

**Comment by greg-db** [comment]
This appears to be a false positive in Apple's tooling. There's [a discussion about this here](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Error-when-uploading-binary-on-iOS-with-Xcode-14-and-using/td-p/622696). You may need to reach out to Apple regarding that.
