### ISSUE TITLE
Why is there an assertion in +[DropboxClientsManager unlinkClients]?

### ISSUE THREAD

**Issue by rodionovd** [dropbox/dropbox-sdk-obj-c#36]
If there're no authorized clients `+resetClients` is a simple no-op (like it should be), but `+unlinkClients` crashes due to the failed assertion:

```objective-c
NSAssert(
      [DBOAuthManager sharedOAuthManager] != nil,
      @"Call `[DropboxClient setupWithAppKey]` or `[DropboxClient setupWithTeamAppKey]` before calling this method");
```

What are the caveats of clearing the empty keychain?

Thanks!

**Comment by scobbe** [comment]
Good point, there really aren't any caveats. The latest version of the SDK (v1.0.9) removes this assert statement. Thanks!
