### ISSUE TITLE
Don't embed Reachability

### ISSUE THREAD

**Issue by bvirlet** [dropbox/dropbox-sdk-obj-c#37]
This causes duplicate symbols when using Reachability in our main app. Please either make it an explicit dependency, or rename the class to avoid conflicts.

**Comment by scobbe** [comment]
Thanks for pointing this out. The latest version of the SDK (v1.0.9) renames the publicly visible names to have `DB` in front of them. Let me know if this resolves the namespace clash you were experiencing. Thanks!

**Comment by bvirlet** [comment]
Thanks, I have looked at the change and this will address the issue.

🙇
