### ISSUE TITLE
Dropbox SDK and xCode 15

### ISSUE THREAD

**Issue by veikoherne** [dropbox/dropbox-sdk-obj-c#380]
As Apple demanded, I had to update my apps to xCode 15. However, my old dropbox framework compiled with older xCode wasn't anymore suitable to include with my app, therefore I tried to compile to a new framework. Even there was a warning, that iOS 11.0 isn't anymore supported the framework was compiled succesfully and I included to my project. 
However, trying to test my newly built app with my iOS device still running iOS 16, it crashes immediatly after starting. Removing your library works fine. So, do you have any intentions to provide me a framework library to support Apple new requirements or do I have to remove any integration with Dropbox from my app?

Thanks,
Veiko Herne

**Comment by greg-db** [comment]
We'll be happy to help with any issues you're having with this Dropbox SDK, but we'll need some more information. Please reply with:

- the steps to reproduce the issue, including relevant configuration settings and code snippet(s), but don't include any access or refresh token(s)
- the full text of any error or unexpected output

**Comment by veikoherne** [comment]
I think I sorted it out. When including your framework, I should have been mark it as "embed & sign". Thanks for your help.
