### ISSUE TITLE
DBMobileSafariViewController does not render content on iOS 18.0 Simulators

### ISSUE THREAD

**Issue by 4marcus** [dropbox/dropbox-sdk-obj-c#387]
When running in iOS 18.0 Simulators, calls to 
```
        // request scoped app access
        [DBClientsManager authorizeFromControllerV2:[UIApplication sharedApplication]
              controller:[[self class] topMostController]
              loadingStatusDelegate:nil
              openURL:^(NSURL *url) { [[UIApplication sharedApplication] openURL:url  options:@{}  completionHandler:nil];}
              scopeRequest: scopeRequest];
```
result in transition to a DBMobileSafariViewController, but no content is rendered and application is hence stuck. Using iOS 17.4 simulator work fine.

This occurs on:

- tested simulators: iPad Pro 13-inch (M4) with iOS 18 and iOS 17.4
- Xcode Version 16.0 (16A242d) 
- macOS 15.0 (24A335)
- Carthage with ObjectiveDropboxOfficial  7.4.1

There is no console log beyond last log:
`DBSDKReachability Flag Status: -R ------- networkStatusForFlags`

**Comment by greg-db** [comment]
Thanks for the report! I just gave this code snippet a try myself, with the same iOS 18 simulator, Xcode, and ObjectiveDropboxOfficial versions, but the app authorization page rendered fine for me. 

I see you mentioned this happening "in iOS 18.0 Simulators", but only specifically mentioned testing in "iPad Pro 13-inch (M4) with iOS 18". So to clarify, can you reproduce this in multiple different iOS 18 simulators? If it seems to be isolated to one iOS 18 simulator, can you try resetting that simulator?

**Comment by 4marcus** [comment]
Thanks for quick support! I tested with other simulators, latest being iPhone SE (3rd gen). 
I restarted machine, Xcode, simulators (incl. resetting).

Currently the issue remains and seems related too/caused by adding  arm64 to Excluded Architectures in build settings. See post: "[SFSafariViewController not loading web pages on Xcode 16 Simulator with iOS 18](https://forums.developer.apple.com/forums/thread/764468)" 

When I try to build my app without this setting, linking fails with below error as ld uses the option `-target arm64-apple-ios13.0-simulator`:

```
ld: building for 'iOS-simulator', but linking in dylib (/Users/Marcus/.../Carthage/Build/iOS/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by greg-db** [comment]
Thanks for tracking that down and sharing that. I can confirm that this reproduces for me when I add `arm64` to "Excluded Architectures". Unfortunately that seems to be out of our control so I'll defer to that thread with Apple for that.

I don't get that `ld` error without the `arm64` exclusion though. That may be related to some other setting in your project that I don't have. We'll take a look.

**Comment by 4marcus** [comment]
The issue is resolved. In fact, my build settings pointed to an outdated framework setup which did not have the `arm64`support. After re-adding the `ObjectiveDropboxOfficial.xcframework`, `arm64` link issue did not occur and also iOS 18.0 simulator's safari view worked. Thanks for support!
