### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by vinacc** [dropbox/dropbox-sdk-obj-c#40]
Hello to all,
I'm implementing the project within my app. I have a problem during the upload of a file on Dropbox.

This is the code I use

```
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory , NSUserDomainMask, YES);
    NSString *documentsDir = [paths objectAtIndex:0];
    NSString *pathDB = [documentsDir stringByAppendingPathComponent:@"archive.sql"];

    [Archivio getInitialDataToDisplay:pathDB writeOnfile:YES];

    NSString *path = [documentsDir stringByAppendingPathComponent:@"backup_archive.txt"];

    if ([DropboxClientsManager authorizedClient] != nil || [DropboxClientsManager authorizedTeamClient] != nil) {
        NSData *fileData = [NSData dataWithContentsOfFile:path];
        [[[client.filesRoutes uploadData:@"/archive" inputData:fileData]
          response:^(DBFILESFileMetadata *result, DBFILESUploadError *routeError, DBError *error) {
              if (result) {
                  NSLog(@"%@\n", result);
              } else {
                  NSLog(@"%@\n%@\n", routeError, error);
              }
          }] progress:^(int64_t bytesUploaded, int64_t totalBytesUploaded, int64_t totalBytesExpectedToUploaded) {
              NSLog(@"%lld\n%lld\n%lld\n", bytesUploaded, totalBytesUploaded, totalBytesExpectedToUploaded);
          }];
```

and that the error I get

```
   ".tag" = path;
     path =     {
         reason =         {
             ".tag" = conflict;
             conflict =             {
                 ".tag" = folder;
             };
         };
         "upload_session_id" = AAAAAAAAGSOLDdsRysL2YQ;
     };
 }
 DropboxHttpError[{
     ErrorContent = "path/conflict/folder/...";
     RequestId = 32deffe21bf9b202f172de351510e1f3;
     StatusCode = 409;
 }];
```

How can I fix?

**Comment by rodionovd** [comment]
Hello!

The problem seems to be that you're trying to upload a file to the path that already exists in Dropbox — so there's a conflict (as the error implies). Try to use `-uploadData:mode:autorename:clientModified:mute:inputData:` method for uploading files instead with an appropriate WriteMode (see [`DBFILESWriteMode.h`](https://github.com/dropbox/dropbox-sdk-obj-c/blob/9ba22e25fbaffbf48b1b3ff09dce64806de96719/Source/ObjectiveDropboxOfficial/PlatformNeutral/ApiObjects/Files/DBFILESWriteMode.h)) and autorename=YES if needed.

**Comment by smarx** [comment]
@vinacc Make sure you're passing a _full path_ to where the file should be saved in Dropbox. In your example, you're using `@"/archive"`, and the error indicates that this path contains a folder right now. You probably want to pass something like `@"/archive/backup_archive.txt"`.

And then, as @rodionovd points out, if you want to overwrite the file that's there, be sure to use a write mode to indicate that. See the documentation for [`-uploadData:mode:autorename:clientModified:mute:inputData:`](http://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)uploadData:mode:autorename:clientModified:mute:inputData:)

(If you're coming from the v1 SDK, you might be used to the SDK appending a filename for you, but in the v2 SDK, where you're not passing a filename at all, you need to include it yourself.)

**Comment by vinacc** [comment]
Thank you both for the help but it still does not work.

[[[client.filesRoutes uploadData:@"/archive" inputData:fileData] is not taking any / (slash) then it seems unable to enter the correct path to the file.

**Comment by smarx** [comment]
@vinacc I'm not sure what you're saying. Can you share the updated version of your code (where you pass a full path)?

**Comment by vinacc** [comment]
looks up the code.

**Comment by smarx** [comment]
I didn't understand "looks up the code."

The code in your message still has just `@"/archive"` in it, instead of `@"/archive/backup_archivetxt"` or something similar.

Have you tried adding a full path?

**Comment by vinacc** [comment]
The code is this:

```
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory , NSUserDomainMask, YES);
	NSString *documentsDir = [paths objectAtIndex:0];
	NSString *pathDB = [documentsDir stringByAppendingPathComponent:@"archive.sql"];
    
    [Archivio getInitialDataToDisplay:pathDB writeOnfile:YES];
    
	NSString *path = [documentsDir stringByAppendingPathComponent:@"backup_archive.txt"];
    
    if ([DropboxClientsManager authorizedClient] != nil || [DropboxClientsManager authorizedTeamClient] != nil) {
        NSData *fileData = [NSData dataWithContentsOfFile:path];
        [[[client.filesRoutes uploadData:@"/archive/backup_archive.txt" inputData:fileData]
```
```
".tag" = path;
    path =     {
        reason =         {
            ".tag" = conflict;
            conflict =             {
                ".tag" = file;
            };
        };
        "upload_session_id" = AAAAAAAAGS9C10DP6Cv7vA;
    };
}
DropboxHttpError[{
    ErrorContent = "path/conflict/file/..";
    RequestId = 2669f054ba87bb6d23887198b4fbd726;
    StatusCode = 409;
}];

```
I can not get to overwrite the file if it exists. If there is properly created. But I can not overwrite.
Using uploadData:mode:autorename:clientModified:mute:inputData: I still mistakes. What is the correct mode to overwrite?

**Comment by smarx** [comment]
As I said above: "See the documentation for [`-uploadData:mode:autorename:clientModified:mute:inputData:`](http://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html)."

Your code doesn't use that method. Can you share the code where you try to use it and what happened?

**Comment by vinacc** [comment]
The code that uses Dropbox is this:

```
-(IBAction)backup {

    DropboxClient *client = [DropboxClientsManager authorizedClient];
    
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory , NSUserDomainMask, YES);
	NSString *documentsDir = [paths objectAtIndex:0];
	NSString *pathDB = [documentsDir stringByAppendingPathComponent:@"archive.sql"];
    
    [Archivio getInitialDataToDisplay:pathDB writeOnfile:YES];
    
	NSString *path = [documentsDir stringByAppendingPathComponent:@"backup_archive.txt"];
    
    if ([DropboxClientsManager authorizedClient] != nil || [DropboxClientsManager authorizedTeamClient] != nil) {
        NSData *fileData = [NSData dataWithContentsOfFile:path];
        [[[client.filesRoutes uploadData:@"/archive/backup_archive.txt" inputData:fileData]
          response:^(DBFILESFileMetadata *result, DBFILESUploadError *routeError, DBError *error) {
              if (result) {
                  NSLog(@"%@\n", result);
              } else {
                  NSLog(@"%@\n%@\n", routeError, error);
              }
          }] progress:^(int64_t bytesUploaded, int64_t totalBytesUploaded, int64_t totalBytesExpectedToUploaded) {
              NSLog(@"%lld\n%lld\n%lld\n", bytesUploaded, totalBytesUploaded, totalBytesExpectedToUploaded);
          }];
    }
 }
```

**Comment by smarx** [comment]
You're calling [`-uploadData:inputData:`](http://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)uploadData:inputData:), but you need to call [`-uploadData:mode:autorename:clientModified:mute:inputData:`](http://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)uploadData:mode:autorename:clientModified:mute:inputData:).

Please at least try to use that method.

**Comment by scobbe** [comment]
I'm going to go ahead and close this issue as we haven't had any other reports of overwriting uploads.

**Comment by relfarias** [comment]
I am having problems with overwriting.
My files are not being cretaed inside the folder and overwriting the archives.

NSString * path = [documentdir stringByAppendingPathComponent:[keys lastObject]];
NSData *dataFile = [[NSFileManager defaultManager] contentsAtPath:path];

[self uploadFile:dataFile :@"/DB" pathLocal:path];

-(void)uploadFile:(NSData *)fileData:(NSString *)pathDropbox pathLocal:(NSString *)pathLocal{
    NSLog(@"PathDropbox:%@\n", pathDropbox);
    NSLog(@"PathLocal:%@\n", pathLocal);
    NSLog(@"FileDataLocal:%@",fileData);
    
    // For overriding on upload
    DBFILESWriteMode *mode = [[DBFILESWriteMode alloc] initWithOverwrite];
    
    [[[self.userClient.filesRoutes uploadData:pathDropbox
                                mode:mode
                          autorename:@(YES)
                      clientModified:nil
                                mute:@(NO)
                           inputData:fileData]
      setResponseBlock:^(DBFILESFileMetadata *result, DBFILESUploadError *routeError, DBRequestError *networkError) {
          if (result) {
              NSLog(@"%@\n", result);
              [self uploadedMetadata:result];
              
          } else {
              NSLog(@"%@\n%@\n", routeError, networkError);
          }
      }] setProgressBlock:^(int64_t bytesUploaded, int64_t totalBytesUploaded, int64_t totalBytesExpectedToUploaded) {
          NSLog(@"\n%lld\n%lld\n%lld\n", bytesUploaded, totalBytesUploaded, totalBytesExpectedToUploaded);
      }];
}

**Comment by greg-db** [comment]
@relfarias This is an old closed issue with several subscribers. Please [open a new issue](https://github.com/dropbox/dropbox-sdk-obj-c/issues/new) including both your code and the output you're getting so we can help you without spamming the others here. Thanks!
