### ISSUE TITLE
Failed to cancel a file download

### ISSUE THREAD

**Issue by AnnaKotova** [dropbox/dropbox-sdk-obj-c#41]
Hi all,

I have issue in case when file downloding should be cancelled by user: 
NSInvalidArgumentException (reason: '*** -[NSFileManager moveItemAtPath:toPath:error:]: source path is nil’) in
 `- (DBDownloadUrlTask *)response:response:`
 
 It happens in following part of code in your library:
```
// str 343 
NSError *fileMoveError;
[fileManager moveItemAtPath:[location path] toPath:path error:&fileMoveError];
if (fileMoveError) {
	responseBlock(nil, nil, [[DBError alloc] initAsClientError:fileMoveError], _destination);
	return;
}
```

 I use following method for download: `downloadUrl: overwrite: destination:`
```
// Download to NSURL
 DBDownloadUrlTask * downloadUrlTask = [[[client.filesRoutes downloadUrl:path overwrite:YES destination:outputUrl]   response:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBError *error, NSURL *destination) {
//processing  result	
}] 
progress:^(int64_t bytesDownloaded, int64_t totalBytesDownloaded, int64_t totalBytesExpectedToDownload) {
	NSLog(@"%lld\n%lld\n%lld\n", bytesDownloaded, totalBytesDownloaded, totalBytesExpectedToDownload);
}];
```
and this one for cancel
```
// Cancel
[downloadUrlTask  cancel];
downloadUrlTask = nil;
```

**Comment by scobbe** [comment]
@AnnaKotova: Thanks for reporting this issue. Sorry that you're having problems. Would you mind posting a copy of the stack trace that is printed out when the error happens?

**Comment by scobbe** [comment]
@AnnaKotova: Actually, I found the issue! Please disregard my last request.

3d9dca1 should resolve your problem. Please pull the latest version of the Obj-C SDK (v1.0.11).

Let me know if this solves your problem! Thanks for your patience.

**Comment by AnnaKotova** [comment]
@scobbe: Thank you so much! Issue is fixed and functionality works fine.
