### ISSUE TITLE
Umbrella header 'ObjectiveDropboxOfficial.h' not found

### ISSUE THREAD

**Issue by lvandal** [dropbox/dropbox-sdk-obj-c#42]
Using Carthage to get the latest version. File seems to be missing.

**Comment by scobbe** [comment]
@lvandal: Sorry about that. Issue with header file visibility being set to "project" rather than "public".

Issue should be fixed now. Please re-pull latest version (v1.0.10) from Carthage and let me know if it works now for you. Thanks for your patience.

**Comment by lvandal** [comment]
Solved. Thanks for the quick turnaround!
