### ISSUE TITLE
DBReachability status enumerators conflict with Reachability status enumerators

### ISSUE THREAD

**Issue by cgilboy** [dropbox/dropbox-sdk-obj-c#43]
The fix for https://github.com/dropbox/dropbox-sdk-obj-c/issues/37 does not appear to add prefixes to the actual status values `{ NotReachable = 0, ReachableViaWiFi, ReachableViaWWAN }`. These conflict with the status values in Reachability and cause the build error `Redefinition of enumerator`. 

Maybe change them to `{ DBNotReachable = 0, DBReachableViaWiFi, DBReachableViaWWAN }`?

Thanks!

**Comment by scobbe** [comment]
@cgilboy: Thanks for the feedback – sorry about that! Looked like I missed those when adding the `DB` prefixes to the other Reachability types.

d6e0012 should fix this. Go ahead and grab the latest version of the SDK (v1.0.12) and let me know if the issue persists.

**Comment by cgilboy** [comment]
Looks good! Thanks for the quick update.

**Comment by cgilboy** [comment]
One more change: `kReachabilityChangedNotification` will conflict with Reachability's notification name at link time. If renamed to `kDBReachabilityChangedNotification`, all is well :)

**Comment by scobbe** [comment]
@cgilboy: Ah, sorry! Try pulling v.1.0.12 again (if you're using CocoaPods, make sure to clear cache with `rm -rf "${HOME}/Library/Caches/CocoaPods"`) and let me know if that fixes it

**Comment by cgilboy** [comment]
Thanks! All good now.
