### ISSUE TITLE
Can not support iOS 6 and iOS 7.

### ISSUE THREAD

**Issue by OneSecure** [dropbox/dropbox-sdk-obj-c#49]
Do you have any plan to support iOS 6 and iOS 7? Thanks.

**Comment by greg-db** [comment]
I can't make any promises, but I'll pass this along as a feature request.

**Comment by scobbe** [comment]
I think at this point, we can safely say that we're not going to invest iOS 6 or 7 support at this point, especially with our `WebKit.framework` dependency, which requires iOS >= 8, so I'm going to go ahead and close this.
