### ISSUE TITLE
Crash on macOS 10.10

### ISSUE THREAD

**Issue by Dejal** [dropbox/dropbox-sdk-obj-c#51]
Apple just rejected an app with the Dropbox SDK, as it crashed when running on macOS 10.10.5.

Your documentation says it supports macOS 10.10+, though the Deployment Target in the project is set to 10.11.

Crash report excerpt:

    Exception Type:        EXC_BREAKPOINT (SIGTRAP)
    Exception Codes:       0x0000000000000002, 0x0000000000000000
    
    Application Specific Information:
    dyld: launch, loading dependent libraries
    
    Dyld Error Message:
      Symbol not found: ___NSArray0__
      Referenced from:     /Applications/zCloud.app/Contents/MacOS/../Frameworks/ObjectiveDropboxOfficial_macOS.framework/Versions/A/ObjectiveDropboxOfficial_macOS (which was built for Mac OS X 10.11)
      Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
     in /Applications/zCloud.app/Contents/MacOS/../Frameworks/ObjectiveDropboxOfficial_macOS.framework/Versions/A/ObjectiveDropboxOfficial_macOS

I'll try changing the Deployment Target to 10.10, though I'm not certain that's all that's required.

**Comment by scobbe** [comment]
@Dejal: Sorry for the inconvenience. I updated the macOS project to 10.10. All the unit tests passed, so it should work just fine with that deployment target version. Let me know if you run into any other issues.

**Comment by scobbe** [comment]
@Dejal: Were you able to successfully submit your app to the App Store?

**Comment by Dejal** [comment]
@scobbe: Yes, that seemed to fix it.  Thanks!

**Comment by scobbe** [comment]
@Dejal: Great to hear! 👍
