### ISSUE TITLE
Wrong message - 'Please enter a CAPTCHA response'

### ISSUE THREAD

**Issue by tonysong185** [dropbox/dropbox-sdk-obj-c#52]
Reproduce stage:
1. Enter wrong password or wrong name.
2. Enter right name and password.
3. Show the wrong message 'Please enter a CAPTCHA response', but the CAPTCHA not showing.

How can I resolve the issue? - 'Please enter a CAPTCHA response'

Thank you very much!
![dropbox](https://cloud.githubusercontent.com/assets/16331435/19261171/e46ecf76-8fc1-11e6-897a-a914abb48278.png)

**Comment by scobbe** [comment]
@tonysong185: Thanks for reaching out. Currently, we are unable to reproduce this issue on our end. The CAPTCHA shows up normally for us.

Could you confirm a couple of things for us:

1. Is the problem still present? Perhaps it was a transient issue and is no longer an issue.

2. Are you able to connect to www.google.com? Perhaps your firewall, proxy, ISP block, etc. is interfering with your ability to connect to Google. Our CAPTCHAs are hosted there, which would explain why they are not correctly rendering for you.

**Comment by tonysong185** [comment]
@scobbe : Thanks for your reply. I still have this problem and I can connect to www.google.com normally. 

Add: My test app is the sample app DBRoulette. When I tap link 'New to Dropbox? Get the App!'  whether we should jump to a new page? I can't jump now.

**Comment by greg-db** [comment]
Thanks @tonysong185 . Can you also let us know what version(s) of iOS you're seeing this on as well as what version(s) of the Dropbox Objective-C SDK itself you're seeing this with? Thanks in advance!

**Comment by tonysong185** [comment]
@greg-db : Thanks for you response. My iOS version is iOS 8.0+ and the Dropbox Objective-C SDK is master branch of the latest version. My  Xcode version is 7.3.

**Comment by scobbe** [comment]
@tonysong185: Thanks for supplying the additional info. We've been able to reproduce the issue on our end with iOS < 9, and are looking at making a fix ASAP. I'll update this thread when the fix is out. Thanks for your patience.

**Comment by tonysong185** [comment]
@scobbe I can also reproduce this issue with iOS 9.0+, from your side can you see the CAPTCHA image with iOS 9.0+?

**Comment by greg-db** [comment]
We're still investigating this, but we don't have a timeline right now. Thanks in advance for your patience.

**Comment by scobbe** [comment]
@tonysong185: Sorry for the long delay. This issue should be fixed now. Would you mind confirming that you can now see the CAPTCHA properly rendered on iOS 8 and iOS 9?

**Comment by tonysong185** [comment]
@scobbe @greg-db 👍 Thanks for your team's hard work, I have confirmed that the CAPTCHA showing normally on iOS 8 and iOS 9.
