### ISSUE TITLE
More modular Pod to speed up compilation times

### ISSUE THREAD

**Issue by bvirlet** [dropbox/dropbox-sdk-obj-c#53]
We use the Dropbox SDK in Genius Scan only to let user export documents to Dropbox. We don't rely on any sharing or team feature. 

The entire SDK contains ~430 Objective-C among which we use very little. This takes a good amount of compilation time.

I would love to see a more modular pod with subspec (https://guides.cocoapods.org/syntax/podspec.html#subspec) to make it lighter.

Thanks!

**Comment by greg-db** [comment]
Thanks for the request! We'll look into it.

**Comment by scobbe** [comment]
Compilation times are now much faster in the latest version of the SDK (v3.0.0), after we consolidated the implementation classes to only a few files, so I'm going to go ahead and close this issue.
