### ISSUE TITLE
How to acquire file metadata based on file id?

### ISSUE THREAD

**Issue by SomersJan** [dropbox/dropbox-sdk-obj-c#55]
I understand that each and every file has an unambiguous identifier.

In my application, when I download a file, I store the file id and other metadata somewhere.

At a given moment I want to get an updated metadata result for this file. How do I do this? I've searched the sdk and I know you can get the metadata by specifying the path. But what if that path has changed since my last 'save'. 

For instance: My offline reference is /Dropbox/Test/File.pdf but since the last use of the app the file.pdf has been moved to the /Dropbox/OtherFolder map.

Any suggestions? The only thing I really want to know is if my file is up to date or not?

Any help would be greatly appreciated!

**Comment by greg-db** [comment]
You can get the metadata for a file or folder based on its file ID using the `filesRoutes `[`getMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)getMetadata:) method like this:

        [[client.filesRoutes getMetadata:@"id:i8PhgWY5-aAAAAAAAAAAAQ"] response:...];

That is, pass in the item's `id` string as the parameter there.

**Comment by SomersJan** [comment]
Thanks for your reply. I have found this method in the sdk as well but was wondering if there was a direct way or not. Guess I'll have to do 'getMetaData' first and than list the revisions of that file and check afterwards whether I have the most up to date revision.

**Comment by greg-db** [comment]
Generally we recommend storing the `rev` of the copy of the file you have locally. If the `rev` in the returned metadata doesn't match the `rev` you have stored locally, you know your copy may not up be up to date.

**Comment by shoaibhassanWhizpool** [comment]
greg-db is there  a way to get files created date and check whether it is file or folder.

**Comment by greg-db** [comment]
@shoaibhassanWhizpool The Dropbox API doesn't return file creation date, but I'll pass this along as a feature request. 

You can determine if a [`DBFILESMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESMetadata.html) is a file or folder by using `isKindOfClass` as shown here:

https://github.com/dropbox/dropbox-sdk-obj-c#response-handling-edge-cases

Also, your questions here don't seem related to the original question, so for future reference please either [open a new issue](https://github.com/dropbox/dropbox-sdk-obj-c/issues/new) or a new thread on [our forum](https://www.dropboxforum.com/t5/API-support/bd-p/101000014) if you can't find a relevant issue or thread.
