### ISSUE TITLE
uncatched exception

### ISSUE THREAD

**Issue by wws13** [dropbox/dropbox-sdk-obj-c#59]
Hi
method +[NSJSONSerialization JSONObjectWithData:options:error:]
generate exception when data is nil
so possible need add check for data is nil in method -[DBTask deserializeHttpData:] ?

possible fix (DBTask.m):
```
- (NSDictionary *)deserializeHttpData:(NSData *)data {
    if (!data)
        return nil;
    NSError *error;
    return [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingMutableContainers error:&error];
}
```

**Comment by greg-db** [comment]
Thanks for the report @wws13 ! Can you share the steps to reproduce this `nil` `data`, as well as the exception you're getting? Thanks in advance!

**Comment by wws13** [comment]
whe I try rename any file on dropbox account with zero space available with method -[DBFILESRoutes move: toPath:]
I receive ecxeption:

**Comment by greg-db** [comment]
Thanks! That's helpful. We're looking into it.

**Comment by scobbe** [comment]
@wws13: Thanks for pointing this out. 3a49c2d fixes this. We should have a new version out shortly.
