### ISSUE TITLE
Could you please support in-app authentication?

### ISSUE THREAD

**Issue by magicboker** [dropbox/dropbox-sdk-obj-c#61]
I tried to migrate my old apps to use the v2 API, but my old apps didn't enable background mode, which means it need to authenticate with dropbox in app (without going to background).
Is there any way to do in-app authentication without using the openURL way to callback the app for authentication?

**Comment by greg-db** [comment]
Hi @magicboker , I'm not sure I fully understand the problem you're running in to. Can you elaborate, and include the relevant code, etc?

This API v2 Objective-C SDK offers the same app authorization flow as the old SDKs, with additional control over whether or not to allow authentication in the browser:

https://github.com/dropbox/dropbox-sdk-obj-c#handling-the-authorization-flow

**Comment by magicboker** [comment]
I already modified the source codes of your SDK successfully to achieve authentication without UIApplication openURL callback on my apps. close this issue now.
