### ISSUE TITLE
Latest Pod version doesn't compile

### ISSUE THREAD

**Issue by xaphod** [dropbox/dropbox-sdk-obj-c#64]
I really hope this is me, but...

Line 5 of source->ObjectiveDropboxOfficial_iOS/DBOAuthMobile.m is to import DBOAuth.h
... which doesn't exist.

So I did a pod update and ObjectiveDropboxOfficial no longer compiles (from version 1.1.3 to 1.1.4).
What gives?

**Comment by greg-db** [comment]
Thanks for the report! I just tried a `pod update` from 1.1.3 to 1.1.4 though, and I can't seem to reproduce this. I do get a DBOAuth.h and DBOAuth.m in both.

Can you try cleaning/cleaning your build folder, if you haven't already? What versions of CocoaPods and Xcode are you using?

**Comment by xaphod** [comment]
Hi, Greg
I tried cleaning, cleaning build folder, restarting xcode, rebooting,
redoing the pods (pod install again), and a few other things.
Cocoapods is newest stable (as per sudo gem update yesterday), xcode is
newest from app store as of today.
thanks
-tim

**Comment by greg-db** [comment]
Thanks! We'll look into it.

**Comment by strike65** [comment]
Same problem here... My Project doesn't compile anymore. 
![dropboxerror](https://cloud.githubusercontent.com/assets/2091178/20601440/e760ffc4-b258-11e6-93e7-de27dfaa747c.png)

Regards!
strike

**Comment by scobbe** [comment]
@xaphod: Sorry you're running into issues. Would you try pulling the (just-released) latest version of the SDK (2.0.0) and see if you still experience these issues? Thanks for your patience!

**Comment by xaphod** [comment]
@scobbe Thanks yes now your Pod compiles.
One question for the migration - when uploading a file in the new 2.x world of this Pod, where does one specify DBFilesWriteMode and autorename? For example, my old code is:

            [[[client.filesRoutes uploadUrl:[subfolderName stringByAppendingPathComponent:filename] mode:[[DBFILESWriteMode alloc] initWithAdd] autorename:@YES clientModified:nil mute:nil inputUrl:fileURL] response:[NSOperationQueue new] response:^(DBFILESFileMetadata * _Nullable result, DBFILESUploadError * _Nullable routeError, DBError * _Nullable error) {
                // stuff
            }] progress:^(int64_t a, int64_t b, int64_t c) { }];

... the new code so far:


               [[client.filesRoutes uploadUrl:[subfolderName stringByAppendingPathComponent:filename] inputUrl:fileURL] response:[NSOperationQueue new] response:^(DBFILESFileMetadata * _Nullable result, DBFILESUploadError * _Nullable routeError, DBRequestError * _Nullable error) {
               // stuff
               }];
               
... but where do I specify the equivalent of `mode:[[DBFILESWriteMode alloc] initWithAdd] autorename:@YES` ?

thanks.

**Comment by scobbe** [comment]
@xaphod: Thanks for your quick reply. For version 2.0.1 of the SDK, I created a sample project and integrated via CocoaPods. I was able to successfully compile the following code:

```
DropboxClient *client = [[DropboxClient alloc] initWithAccessToken:@""];
    
    [[client.filesRoutes uploadUrl:@"/" mode:[[DBFILESWriteMode alloc] initWithOverwrite] autorename:@(YES) clientModified:nil mute:@(NO) inputUrl:[NSURL URLWithString:@""]]
     response:^(DBFILESFileMetadata *result, DBFILESUploadError *routeError, DBRequestError *error) {
         if (result) {
             NSLog(@"%@", result);
         } else {
             NSLog(@"%@ %@", routeError, error);
         }
     }];
```

The `uploadUrl` method to which you're referring should still be around [here](https://github.com/dropbox/dropbox-sdk-obj-c/blob/09bc158eb09e40d3e7e846753da4616705da9d6d/Source/ObjectiveDropboxOfficial/Shared/Generated/Routes/DBFILESRoutes.h#L1043).

Are you able to locate this method in your .xcodeproj?

**Comment by xaphod** [comment]
I "appleogize", my mistake: must have been some indexing problem with my project. As soon as i restarted xcode it compiled :)

Original issue fixed in latest pod so closing. Thanks

**Comment by scobbe** [comment]
Great to hear! Let us know if anything else comes up :)
