### ISSUE TITLE
incompatible block pointer types

### ISSUE THREAD

**Issue by richardwilliamson** [dropbox/dropbox-sdk-obj-c#66]
I'm getting an error:

"Incompatible block pointer types sending 'void (^)(...' to parameter of type 'void(^Nonnull)(..."
With the code

`[[client.filesRoutes listFolder:@""]
	 response:^(DBFILESListFolderResult *result, DBFILESListFolderError *routeError, DBError *error) {
//	   if (result) {
//		 NSLog(@"got something");
//	   }

	 }];`

Any ideas?

**Comment by richardwilliamson** [comment]
Actually fixed it - seems to be a bug/change in the API that hasn't been update in the examples..

Examples show the equavalent of 
`[[client.filesRoutes listFolder:@""] response:^(DBFILESListFolderResult *result, DBFILESListFolderError *routeError, DBError *error) {`

but API requires
`	[[client.filesRoutes listFolder:@""] response:^(DBFILESListFolderResult *result, DBFILESListFolderError *routeError, DBRequestError *error) {`

**Comment by scobbe** [comment]
@richardwilliamson: Sorry about that. 2a21821 should fix the README here.
