### ISSUE TITLE
Errors when submitting to app store

### ISSUE THREAD

**Issue by richardwilliamson** [dropbox/dropbox-sdk-obj-c#67]
Hello

Followed instructions to use Carthage on the readme - although had to add the framework to "Embedded Binaries" rather than "Linked Frameworks and Libraries" to get the app to build - I am assuming this is an error in the documentation?

All works fine both in simulator and on device when tested locally, however when trying to upload a build to ITC I am getting a load of errors which I have copied below - I assume I need to re-build the frameworks somehow?

ERROR ITMS-90087: "Unsupported Architectures. The executable for MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework contains unsupported architectures '[x86_64, i386]’."

ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.”

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.”

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.”

WARNING ITMS-90080: "The executable 'Payload/MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."
WARNING ITMS-90080: "The executable 'Payload/MYAPP.app/Frameworks/ObjectiveDropboxOfficial.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

**Comment by richardwilliamson** [comment]
I should add this is quite an old app which was started around 2012 - I wasn't able to get dropbox to integrate with cocoapods which I think may have been to do with some legacy settings in the app, but I have been unable to work this out yet

**Comment by scobbe** [comment]
@richardwilliamson: Sorry that you're running into issues. 

As far as the README, it is not an error when it says you should add the `ObjectiveDropboxOfficial.framework` to **Linked Frameworks and Libraries** rather than **Embedded Binaries**. If your target is < iOS 8, you may run into issues linking as a framework here.

What exactly is the error message you receive when you try to add the ObjectiveDropbox framework via **Linked Frameworks and Libraries**?

Please also ensure that you follow the instructions to include a "New Run Script Phase" otherwise you'll have problems submitting to the App Store.

**Comment by richardwilliamson** [comment]
@scobbe Thanks for coming back to me - weirdly if I now move the framework back to link from embedded it seems to work, previously I was getting an error on the import <object..> lines as if the compiler couldn't find the libraries but that now seems to be fine - not sure what I did there..

And doing that seems to fix all my other issues - so I'm obviously just dim!! Thanks for your help

**Comment by scobbe** [comment]
@richardwilliamson: Haha no worries. Reach out to us if anything else comes up!

**Comment by Allan-Nava** [comment]
I have this problem when I i try to upload the Archive Release.
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."

I use this script:
```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

I use ionic cordova build ios --release and it works "build succeeded", but when I try to upload to app store I have this problem:
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."

**Comment by greg-db** [comment]
@Allan-Nava Based on your output, it looks like the error is referring to 'GoogleCast.framework', which isn't made by Dropbox, so I'm afraid we can't offer help for that.

**Comment by Allan-Nava** [comment]
@greg-db Ok, sorry :(

**Comment by jerry-jpreng** [comment]
I am having a similar (but not identical) problem to that of the original poster. Followed instructions to use Carthage on the readme. Had to add the framework to "Embedded Binaries" **as well as** "Linked Frameworks and Libraries" to get the app to build.

All works fine both in simulator and on device when tested locally, but when trying to upload a build to ITC I get the following errors during validation...

<iTunes Store Operation Failed
description length:217572

iTunes Store Operation Failed
ERROR ITMS-90087: "Unsupported Architectures. The executable for OutlinesOutloud.app/Frameworks/ObjectiveDropboxOfficial.framework contains unsupported architectures '[x86_64, i386]'."

iTunes Store Operation Failed
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'OutlinesOutloud.app/Frameworks/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

iTunes Store Operation Failed
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

iTunes Store Operation Failed
WARNING ITMS-90080: "The executable 'Payload/OutlinesOutloud.app/Frameworks/ObjectiveDropboxOfficial.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library.">

Also, am seeing this when archiving (don't know if it's relevant)...

<warning: skipping copy phase strip, binary is code signed: /Users/studyoutloud/git/OutlinesOutloud_iOS/OutlinesOutloud/Code/SpeakOutliner/Carthage/Build/iOS/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial>

I've attached screen grabs of the relevant sections from the General and Build Phases tabs for verification that everything looks as if it's set up correctly..

![from general tab - 1](https://user-images.githubusercontent.com/5157574/32080130-d2ea60fe-ba62-11e7-8c89-5e0c8e65406a.png)
![screen shot 2017-10-26 at 3 10 29 pm](https://user-images.githubusercontent.com/5157574/32080131-d3109620-ba62-11e7-9343-77f461329b85.png)
![screen shot 2017-10-26 at 3 10 48 pm](https://user-images.githubusercontent.com/5157574/32080132-d334f5c4-ba62-11e7-9a0e-351b859896e0.png)
![screen shot 2017-10-26 at 3 11 29 pm](https://user-images.githubusercontent.com/5157574/32080133-d354c552-ba62-11e7-90cf-84134b929fc0.png)
![screen shot 2017-10-26 at 3 12 49 pm](https://user-images.githubusercontent.com/5157574/32080134-d3773e7a-ba62-11e7-889f-c5dbf37b5472.png)

Not sure what to try next.

**Comment by scobbe** [comment]
@jerry-jpreng: Have you tried using the build script suggested in [this SO post](https://github.com/dropbox/dropbox-sdk-obj-c/issues/67#issuecomment-339820109)?

**Comment by jerry-jpreng** [comment]
That did it! Thanks for your help, @scobbe.

**Comment by scobbe** [comment]
@jerry-jpreng: Amazing! Good luck 👍
