### ISSUE TITLE
Still making requests to /1/

### ISSUE THREAD

**Issue by xaphod** [dropbox/dropbox-sdk-obj-c#68]
This API still makes requests to /1/ (API v1). For example in DBOAuth.m, `components.path = @"/1/oauth2/authorize";` is wrong per [https://www.dropbox.com/developers/reference/migration-guide](https://www.dropbox.com/developers/reference/migration-guide)

**Comment by scobbe** [comment]
@xaphod: Thanks for pointing this out. 54b1f8f fixes this. It will appear in the next release.
