### ISSUE TITLE
Update README / instructions to not use deprecated iOS UIApplicationDelegate method

### ISSUE THREAD

**Issue by xaphod** [dropbox/dropbox-sdk-obj-c#70]
Minor nit...
Per the apple reference doc: https://developer.apple.com/reference/uikit/uiapplicationdelegate
`- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url` is deprecated. So you should remove that from your README/instructions, and reference the new one instead:

`- (BOOL)application:(UIApplication *)app 
            openURL:(NSURL *)url 
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options;`

**Comment by scobbe** [comment]
@xaphod: Good suggestion, thanks for brining this up. 984920f should address this. Given that we support iOS > 8, I left `application:handleOpenURL:url` because it's the only option for iOS 8 targets, but also added `application:openURL:options` as well.
