### ISSUE TITLE
pod install documentation missing open newly created .xcworkspace

### ISSUE THREAD

**Issue by arunrajagopalan** [dropbox/dropbox-sdk-obj-c#71]
The reference documentation at http://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/ is missing the following step after pod install

"Once this command completes, open the newly create .xcworkspace file. Your project should now be successfully integrated with the the SDK."

This is correctly present in README.md file on Github but is missing in the  docs here http://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/

**Comment by scobbe** [comment]
@arunrajagopalan: Thanks for bringing this up. I'll be sure to update the documentation for the next release!
