### ISSUE TITLE
unknow name "DBRequestError"

### ISSUE THREAD

**Issue by jigarviprak** [dropbox/dropbox-sdk-obj-c#73]
gettiing error

unknow name "DBRequestError"
 [[[client.filesRoutes downloadData:@"/test/path"]
'void (^)(DBFILESFileMetadata *__strong, DBFILESDownloadError *__strong, int *, NSData *__strong)' to parameter of type 'void (^ _Nonnull)(DBFILESFileMetadata * _Nullable __strong, DBFILESDownloadError * _Nullable __strong, DBError * _Nullable __strong, NSData * _Nonnull __strong)'

**Comment by scobbe** [comment]
@jigarviprak: Are you using CocoaPods or Carthage? What version of the SDK are you using?

Could you also share your code where you make the `[[[client.filesRoutes downloadData:@"/test/path"]` call?

**Comment by jigarviprak** [comment]
i am using cocoapods and verssion 1.1.1
also xcode:8.1

mycode:
DropboxClient *client = [DropboxClientsManager authorizedClient];
    
    // Download to NSData
    [[[client.filesRoutes downloadData:@"/test/path"]
      response:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *error, NSData *fileContents) {
          if (result) {
              NSLog(@"%@\n", result);
              NSString *dataStr = [[NSString alloc]initWithData:fileContents encoding:NSUTF8StringEncoding];
              NSLog(@"%@\n", dataStr);
          } else {
              NSLog(@"%@\n%@\n", routeError, error);
          }
      }] progress:^(int64_t bytesDownloaded, int64_t totalBytesDownloaded, int64_t totalBytesExpectedToDownload) {
          NSLog(@"%lld\n%lld\n%lld\n", bytesDownloaded, totalBytesDownloaded, totalBytesExpectedToDownload);
      }];

**Comment by greg-db** [comment]
Do you mean you're using version 1.1.1 of SwiftyDropbox or version 1.1.1 of CocoaPods itself? (Stephen was asking what version of SwiftyDropbox you're using.)

If you're using version 1.1.1 of SwiftyDropbox, it won't have `DBRequestError`. `DBError` was renamed to `DBRequestError` in version 2.0.0 of SwiftyDropbox. Please update to the latest version of SwiftyDropbox (using `pod update`) and let us know if you're still seeing this issue.

**Comment by jigarviprak** [comment]
i am using ObjectiveDropboxOfficial  version 2.0.6 in objective -C at that time given error..

**Comment by jigarviprak** [comment]
isssue fixed but we can't get file..return path not found..

**Comment by greg-db** [comment]
I'm glad to hear that issue is fixed.

If you're running in to a different problem, please [open a new issue](https://github.com/dropbox/dropbox-sdk-obj-c/issues/new) with the details (steps to reproduce the issue, the code, and the full error).
