### ISSUE TITLE
Error of canOpenURL: failed for URL: "dbapi-8-emm"

### ISSUE THREAD

**Issue by wangbourne** [dropbox/dropbox-sdk-obj-c#74]
I'm quite sure that i have added in plist:

```
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbauth</string>
		<string>dbapi-2</string>
		<string>dbapi-8-emm</string>
	</array>
```

However, I still could see this error in my app: 
canOpenURL: failed for URL: "dbapi-8-emm://1/connect" - error: "(null)"

More strange thing is there's no message related to "This app is not allowed to query for scheme dbapi-2", which are mentioned by a lot of articles.

Appreciate if anyone could point out the root cause.

Thanks

**Comment by greg-db** [comment]
HI @wangbourne , iOS is unfortunately somewhat noisy around this, but if you're getting "error: "(null)"" there actually isn't any issue. 

If the actual functionality isn't working as expected, feel free to reopen this, but it sounds like this just some extra console logging in this case.
