### ISSUE TITLE
DBTasks cannot be cancelled anymore

### ISSUE THREAD

**Issue by goetzf** [dropbox/dropbox-sdk-obj-c#76]
Previously, running instances of `DBTasks` subclasses could be cancelled by calling `-cancel`. However, with the restructuring in commit [dc4714f](https://github.com/dropbox/dropbox-sdk-obj-c/commit/dc4714f9f82e2612c15319df054c09902e3e58ee), calling `-cancel` throws an exception because the method is not implemented in the concrete subclass. The only subclass that implements  this method is `DBBatchUploadTask` (which also declares the method again in the `DBTasksImpl.h`). Are the other subclasses missing an implementation of this method?

The same problem also applies to the methods `-suspend`, `-resume` and `-start`.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by goetzf** [comment]
Thanks! :)

**Comment by Twv** [comment]
As of today (f0383852f0383852babf0311074a788a671dccf31b71fcf2) DBDownloadDataTask still does not have the cancel implemented. Any ETA on delivery?

**Comment by greg-db** [comment]
I don't have an ETA unfortunately. I'll follow up here once I have an update.

**Comment by paulbeadle** [comment]
Hi Greg. This problem is preventing us from moving to the new API (and time is running out). We either need this one fixed or alternatively a way to chunk download requests using the ObjC API (as is currently possible with uploads). Which is more likely?

**Comment by greg-db** [comment]
Thanks for checking in on this. This should be getting fixed, but I don't have an ETA right now.

**Comment by scobbe** [comment]
@paulbeadle @Twv: Apologies for the long delay here. This should be fixed now in the latest version of the SDK (v3.0.0).
