### ISSUE TITLE
Downloading file not supported in an app extension?

### ISSUE THREAD

**Issue by tererecool** [dropbox/dropbox-sdk-obj-c#78]
Hello, should downloading a file be supported in an App extension? We work intensively with Dropbox APIs and in the app itself downloading a file from Dropbox with following code part is not a problem, now, in an app extension where a file from Dropbox can be selected the same code is called but we are getting an error code -955, navigating through the folders works though:

`DBDownloadDataTask *downloadTask = [[[[[DropboxClientsManager authorizedClient] filesRoutes] downloadData:pathUTF8] response:^(DBFILESFileMetadata *meta, DBFILESDownloadError *downloadError, DBRequestError *error, NSData *data) {`

**Comment by greg-db** [comment]
While the SDK does try to be safe for app extensions (e.g., [here](https://github.com/dropbox/dropbox-sdk-obj-c/blob/bf9c5dca9d602bf0b95a6bf26e05d7eb2787bcbd/Source/ObjectiveDropboxOfficial/ObjectiveDropboxOfficial_iOS/DBOAuthMobile-iOS.m#L25)) unfortunately I don't believe it has any specific support or documentation for using it with extensions in particular. (I'll be sure to pass this along as a feature request.)

We'll still be happy to look into this issue though. Can you share the full error/output for reference? Thanks in advance!

**Comment by tererecool** [comment]
downloadError = nil
error = DropboxClientError[{
    NSError = "Error Domain=NSURLErrorDomain Code=-995 \"(null)\"";
}];

**Comment by tererecool** [comment]
We came across a solution that I am still evaluating, not sure about the impact:

`DBTransportClient *dbTransport = nil;
        
#if defined(ISAPPEX)
        // when running in the context of an app extension, we cannot upload/download in the background
        dbTransport = [[DBTransportClient alloc] initWithForceForegroundSession];
#endif
        
        // tell the Dropbox SDK that our app wants to use it
        [DropboxClientsManager setupWithAppKey:MYAPP_DB_APP_KEY transportClient:dbTransport];
`

Using a foreground session instead of a background session it works now, but not sure if there is a drawback with this solution, UI seems not to be blocking.

**Comment by greg-db** [comment]
Thanks! That error output isn't as helpful as I hoped, but it looks like the error code corresponds to [`NSURLErrorBackgroundSessionRequiresSharedContainer`](https://developer.apple.com/reference/foundation/1508628-url_loading_system_error_codes/nsurlerrorbackgroundsessionrequiressharedcontainer?language=objc). 

Anyway, I'm glad to hear you got this working. As far as the Dropbox SDK is concerned, using that option should be fine. 

The error itself seems to imply that another solution would be to use a shared container.
