### ISSUE TITLE
Which class is the replacement of CLASS DBFileSystem ?

### ISSUE THREAD

**Issue by yupliang** [dropbox/dropbox-sdk-obj-c#79]
Which class is the replacement of CLASS DBFileSystem ? In the elder version, I used this method to assure if the file exist in the path: 
```
DBFile *existingFile = [[DBFileSystem sharedFilesystem] openFile:filePath error:nil];
if (existingFile) {nslog("File Exist");}
```
but now with this new version, how could i replace this snipper?

**Comment by greg-db** [comment]
It looks like you're referring to the old [Sync SDK](https://www.dropbox.com/developers-v1/sync/sdks/ios). The new API v2 SDKs offer a different abstraction, and offer more control over the API calls made.

To check if a particular file exists, and to get its metadata if so, you can use the [`getMetadata`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)getMetadata:) method. To access file content, you can use the [`downloadData`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)downloadData:) or [`downloadUrl`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)downloadUrl:overwrite:destination:) methods.
