### ISSUE TITLE
Make session configuration customizable

### ISSUE THREAD

**Issue by tobihagemann** [dropbox/dropbox-sdk-obj-c#80]
I'd like to customize `NSURLSessionConfiguration` of `DBTransportClient`. My use case is that I have to add a `sharedContainerIdentifier` in order to make Dropbox work in an app extension.

Initially I tried to implement something like [GTMSessionFetcher.m#L598](https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionFetcher.m#L598). But then I realized that this won't work, because the session config is already being set up in the initializer of `DBTransportClient`. Which means that I'd have to add a bunch of initializers way up to `DropboxClient`, `DropboxClientsManager`, and I actually don't know where to go on from there.

**Comment by greg-db** [comment]
HI @tobihagemann I think you should be able to do something like this:

    DBTransportClient *transportClient = [[DBTransportClient alloc] initWithAccessToken:accessToken];
    transportClient.session = urlSession; // whatever NSURLSession you want here.
    DropboxClient *client = [[DropboxClient alloc] initWithTransportClient:transportClient];

Give that a try and let me know if it doesn't work for you.

**Comment by tobihagemann** [comment]
Thank you for your quick feedback! This is what I came up with:

```objc
DBTransportClient *transportClient = [DropboxClientsManager authorizedClient].transportClient;
if (transportClient) {
  NSURLSessionConfiguration *sessionConfig = [NSURLSessionConfiguration defaultSessionConfiguration];
  sessionConfig.sharedContainerIdentifier = @"…";
  transportClient.session = [NSURLSession sessionWithConfiguration:sessionConfig delegate:transportClient.delegate delegateQueue:transportClient.delegateQueue];
  
  NSString *backgroundId = [NSString stringWithFormat:@"%@.%@", @"com.dropbox.dropbox_sdk_obj_c_background", [NSUUID UUID].UUIDString];
  NSURLSessionConfiguration *backgroundSessionConfig = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:backgroundId];
  backgroundSessionConfig.sharedContainerIdentifier = @"…";
  transportClient.backgroundSession = [NSURLSession sessionWithConfiguration:backgroundSessionConfig delegate:transportClient.delegate delegateQueue:transportClient.delegateQueue];
}
```

Some of it is copy/paste code from [DBTransportClient.m#L84](https://github.com/dropbox/dropbox-sdk-obj-c/blob/master/Source/ObjectiveDropboxOfficial/Shared/Handwritten/Networking/DBTransportClient.m#L84) with the extra `sharedContainerIdentifier` I wanted. I'm not creating a new client, but customizing `[DropboxClientsManager authorizedClient].transportClient` instead.

Is this what you had in mind? Basically, I have to call this method right after `+[DropboxClientsManager setupWithAppKey:]` and after a successful authentication of `+[DropboxClientsManager authorizeFromController:controller:openURL:browserAuth:]`. Correct?

Too bad I can't use KVO here, because `authorizedClient` of `DropboxClientsManager` is a static variable.

Another thing I've tried: Re-using the session configurations of `transportClient`. But the problem boiled down to needing a new `backgroundId` for `backgroundSession`. Can't re-use it even after invalidating the old session with `-[NSURLSession invalidateAndCancel]`.

If you don't see any improvements I can make, you can close this issue. :) Thanks for your help!

**Comment by tobihagemann** [comment]
Ah, just saw that `sharedContainerIdentifier` is now being exposed beginning with version 3.0.4. Thanks for the addition @scobbe! :+1:
