### ISSUE TITLE
Please get rid of the DB prefix

### ISSUE THREAD

**Issue by sevaa** [dropbox/dropbox-sdk-obj-c#82]
DB stands for "database" first and foremost, for "Dropbox" as a distant second. As a result, the potential for name clashes with existing database related code in user projects is tremendous.

In my case, the project had a class called "DBBase".

**Comment by greg-db** [comment]
Thanks! I'll send this along to the team.

**Comment by scobbe** [comment]
@sevaa: Apologies for the delay here. I understand where you're coming from with the `DB` prefix. I'm not sure if we'll be able to entirely switch over from `DB` to something less likely to result in a naming-collision.

But what we have done is renamed classes that are likely to result in a name collision (like `DBBase`), so hopefully that will resolve the issue for you. Sorry for the inconvenience!

Let us know if there are any other name-collisions you encounter.
