### ISSUE TITLE
When app authorization is revoked, the API doesn't report that

### ISSUE THREAD

**Issue by sevaa** [dropbox/dropbox-sdk-obj-c#83]
Authorize an iOS app. Revoke said authorization in Dropbox settings. Try downloading a file.

The download errors out, but the SDK still considers the client authorized. Subsequent calls to [NSClientsManager authorizedClient] return a nonnil. That's wrong.

**Comment by greg-db** [comment]
You can break out the specific errors, such as an invalid/revoked access token, like this:

    [[client.filesRoutes downloadData:@"/test.txt"] response:^(DBFILESFileMetadata *metadata, DBFILESDownloadError *downloadError, DBRequestError *error, NSData *data) {
        if (metadata) {
            NSLog(@"%@", metadata);
        } else if (downloadError) {
            NSLog(@"%@", downloadError);
        } else if (error) {
            if (error.isAuthError && error.structuredAuthError.isInvalidAccessToken) {
                NSLog(@"Invalid access token");
            } else  {
                NSLog(@"%@", error);
            }
        }
    }];

Hope this helps!

**Comment by sevaa** [comment]
Not in my testing. _tag is null, instead nsError is set. The condition that works goes:

error && error.nsError &&
                    [error.nsError.domain isEqualToString:@"NSURLErrorDomain"] &&
                    error.nsError.code == NSURLErrorUserAuthenticationRequired

**Comment by greg-db** [comment]
You shouldn't have to check the tag yourself. The SDK translates that for you. I tried the code I posted and it worked properly for me. 

If my code example doesn't work for you, please share the following so we can try to reproduce the issue and look into it:
- how you revoked the token specifically (it sounds like you used https://www.dropbox.com/account/security ?)
- the version number of the SDK you have installed
- the rest of the code you're using to make the call
- the full output when you log out `error`

Thanks in advance!

**Comment by sevaa** [comment]
- Via https://www.dropbox.com/account/security ?)
 - v2.0.6, straight from the GitHub tag
 - "The rest of code" is a lot of code. Don't you have a sample iOS app?
 - It goes:

DropboxClientError[{
    NSError = "Error Domain=NSURLErrorDomain Code=-1013 \"The operation couldn\U2019t be completed. (NSURLErrorDomain error -1013.)\" UserInfo=0x7fcfb4a4e6d0 {NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/download, NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/download}";

**Comment by greg-db** [comment]
Thanks! I didn't mean the rest of the code for your app, just the code for the download call itself, like my example earlier, in case there's something different about how you're calling it.

Anyway, I can't seem to reproduce this behavior unfortunately, even though I'm using 2.0.6 as well, and also revoked access via https://www.dropbox.com/account/security .

For reference, you can also break out client errors like this:

    [[client.filesRoutes downloadData:@"/test.txt"] response:^(DBFILESFileMetadata *metadata, DBFILESDownloadError *downloadError, DBRequestError *error, NSData *data) {
        if (metadata) {
            NSLog(@"%@", metadata);
        } else if (downloadError) {
            NSLog(@"%@", downloadError);
        } else if (error) {
            if (error.isAuthError && error.structuredAuthError.isInvalidAccessToken) {
                NSLog(@"Invalid access token");
            } if (error.isClientError) {
                NSLog(@"%@", error.asClientError.nsError);
            } else  {
                NSLog(@"%@", error);
            }
        }
    }];

That's not the expected error for this scenario though, so we'll have to keep investigating to see why you're getting that. Perhaps it's related to the version of iOS. What version(s) of iOS are you seeing this on?
