### ISSUE TITLE
Document and embrace "locale" on /oauth2/authorize

### ISSUE THREAD

**Issue by sevaa** [dropbox/dropbox-sdk-obj-c#84]
The Web page at https://www.dropbox.com/oauth2/authorize accepts "locale" as a query string parameter. It's extremely useful. Please document and embrace.

**Comment by greg-db** [comment]
Thanks! I'll send this request along to the team.

**Comment by scobbe** [comment]
@sevaa: Apologies for the delay here. This should be fixed in the 3.0.0 version of the SDK.

**Comment by scobbe** [comment]
Actually, sorry, @sevaa, would you clarify if you wanted this "locale" field exposed to the consumer of the SDK, or are ok with the SDK simply passing `[[NSLocale currentLocale] localeIdentifier]`?

**Comment by sevaa** [comment]
Better be exposed to the consumer of the SDK. The effective language of the app UI may not match the system locale. If the Dropbox logon page comes up in English for an otherwise localized app, that's jarring.

I've ended up patching the DBOAuthManager class - added a NSString property "locale", and made the method [DBOAuthManager authURL] look at it and add it to the query string, if nonnil:

```
if(self.locale)
      components.queryItems = [components.queryItems arrayByAddingObject:
        [NSURLQueryItem queryItemWithName:@"locale" value: self.locale]];
```

**Comment by scobbe** [comment]
@sevaa: Ok, thanks for clarifying. I added what you described with 4c980e3. This will be in the next release of the SDK, which will come out shortly. Thanks for your advice! Let us know if you see other parts of the SDK that can be improved.
