### ISSUE TITLE
Specify parent revision on file upload

### ISSUE THREAD

**Issue by SDPrio** [dropbox/dropbox-sdk-obj-c#86]
In API v1 one could (had to) specify the parent revision when uploading a file:
`
[restClient uploadFile:destFileName toPath:destFileDir withParentRev:revision fromPath:localPath]`

The new API v2 does not seem to have this option:

`[[[dropboxClient.filesRoutes uploadUrl:destPath mode:[[DBFILESWriteMode alloc] initWithOverwrite] autorename:@(NO) clientModified:nil mute:@(YES) inputUrl:localeURL]...`

Is this not necessary anymore to avoid/solve conflicts or am I missing something?

**Comment by greg-db** [comment]
In API v2, the equivalent is [`DBFILESWriteMode initWithUpdate:`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESWriteMode.html#/c:objc(cs)DBFILESWriteMode(im)initWithUpdate:), which lets you specify the parent `rev`.
