### ISSUE TITLE
Update API spec to include Paper

### ISSUE THREAD

**Issue by posita** [dropbox/dropbox-sdk-obj-c#99]
There's a new API spec (dropbox/dropbox-api-spec@4483042b0016788742a1c4233a56e163e65b3121) that contains the paper endpoints. Consider updating this SDK.

**Comment by scobbe** [comment]
Thanks @posita. 730753 added this already

**Comment by posita** [comment]
Ah! Sorry. 😞 I should have paid closer attention!
